In [1]:
! python3 ../arelleCmdLine.py --plugins=saveLoadableOIM --saveLoadableOIM=msft.json -f https://www.sec.gov/Archives/edgar/data/789019/000156459018019062/msft-20180630.xml

[info] Activation of plug-in Save Loadable OIM successful, version 1.2. - saveLoadableOIM
[info] loaded in 3.44 secs at 2022-05-26T22:36:16 - https://www.sec.gov/Archives/edgar/data/789019/000156459018019062/msft-20180630.xml

In [2]:
from IPython.display import display, HTML
import json

with open('msft.json') as f:
    gMSFT_XBRL_JSON = json.load(f)

In [3]:
gMSFT_XBRL_JSON.keys()

dict_keys(['documentInfo', 'facts'])

In [4]:
gMSFT_XBRL_JSON['documentInfo']

{'documentType': 'https://xbrl.org/2021/xbrl-json',
 'features': {'xbrl:canonicalValues': True},
 'namespaces': {'cik': 'http://www.sec.gov/CIK',
  'country': 'http://xbrl.sec.gov/country/2017-01-31',
  'dei': 'http://xbrl.sec.gov/dei/2018-01-31',
  'invest': 'http://xbrl.sec.gov/invest/2013-01-31',
  'iso4217': 'http://www.xbrl.org/2003/iso4217',
  'msft': 'http://www.microsoft.com/20180630',
  'srt': 'http://fasb.org/srt/2018-01-31',
  'us-gaap': 'http://fasb.org/us-gaap/2018-01-31',
  'xbrl': 'https://xbrl.org/2021',
  'xbrli': 'http://www.xbrl.org/2003/instance'},
 'linkTypes': {'ftTyp_fact-footnote': 'http://www.xbrl.org/2003/arcrole/fact-footnote'},
 'linkGroups': {'ftGrp_default': 'http://www.xbrl.org/2003/role/link'},
 'taxonomy': ['https://www.sec.gov/Archives/edgar/data/789019/000156459018019062/msft-20180630.xsd']}

In [5]:
gFacts = gMSFT_XBRL_JSON['facts']

In [6]:
gNBFacts = len(gFacts.keys())
gNBFacts

2320

In [7]:
list(gFacts.keys())[:10], list(gFacts.keys())[-10:]

(['F_000000',
  'F_000001',
  'F_000002',
  'F_000003',
  'F_000004',
  'F_000005',
  'F_000006',
  'F_000007',
  'F_000008',
  'F_000009'],
 ['f35991',
  'f36063',
  'f36066',
  'f36014',
  'f36069',
  'f36126',
  'f36072',
  'f36121',
  'f35997',
  'f36000'])

In [8]:
def pretty_print(iFact):
    print(iFact)
    
def dump_fact(iFactIdx):
    lFact = gFacts[list(gFacts.keys())[iFactIdx]]
    pretty_print(lFact)

In [9]:
dump_fact(0)

{'value': '10-K', 'dimensions': {'concept': 'dei:DocumentType', 'entity': 'cik:0000789019', 'period': '2017-07-01T00:00:00/2018-07-01T00:00:00'}}

In [10]:
dump_fact(gNBFacts - 1)

{'value': 'Reflects the net charge (benefit) related to the TCJA of $13.8 billion for the second quarter, $(104) million for the fourth quarter, and $13.7 billion for fiscal year 2018.', 'dimensions': {'concept': 'xbrl:note', 'noteId': 'f36000', 'language': 'en-us'}}

In [11]:
def add_dimensions():
    lDict = {}
    for lFactIdx in range(gNBFacts):
        lFact = gFacts[list(gFacts.keys())[lFactIdx]]
        # print(lFact)
        # print(str(lFact.get('value', ''))[:30], lFact['dimensions'])
        lDict2 = {}
        for (k, v) in lFact['dimensions'].items():
            lDict2[k] = v
        lDict2['value'] = str(lFact.get('value', ''))[:30]
        lConcept = lDict2.get('concept')
        lDict[lConcept] = lDict.get(lConcept , {})
        lDict[lConcept][lFactIdx] = lDict2
    return lDict

In [12]:
gFacts2 = add_dimensions()

In [13]:
import numpy as np
import pandas as pd
lDataFrameByConcept = {}
for (lConcept, lDict) in gFacts2.items():
    lDataFrameByConcept[lConcept] = pd.DataFrame.from_dict(lDict, orient='index')
    display(lDataFrameByConcept[lConcept])

,concept,entity,period,value
0,dei:DocumentType,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,10-K

,concept,entity,period,value
1,dei:AmendmentFlag,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,false

,concept,entity,period,value
2,dei:DocumentPeriodEndDate,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,2018-06-30

,concept,entity,period,value
3,dei:DocumentFiscalYearFocus,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,2018

,concept,entity,period,value
4,dei:DocumentFiscalPeriodFocus,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,FY

,concept,entity,period,value
5,dei:TradingSymbol,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,MSFT

,concept,entity,period,value
6,dei:EntityRegistrantName,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,MICROSOFT CORPORATION

,concept,entity,period,value
7,dei:EntityCentralIndexKey,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,0000789019

,concept,entity,period,value
8,dei:CurrentFiscalYearEndDate,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,--06-30

,concept,entity,period,value
9,dei:EntityWellKnownSeasonedIssuer,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,Yes

,concept,entity,period,value
10,dei:EntityCurrentReportingStatus,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,Yes

,concept,entity,period,value
11,dei:EntityVoluntaryFilers,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,No

,concept,entity,period,value
12,dei:EntityFilerCategory,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,Large Accelerated Filer

,concept,entity,period,unit,value
13,dei:EntityListingParValuePerShare,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD/xbrli:shares,0.00000625

,concept,entity,period,unit,value
14,dei:EntityCommonStockSharesOutstanding,cik:0000789019,2018-08-01T00:00:00,xbrli:shares,7668217316

,concept,entity,period,unit,value
15,dei:EntityPublicFloat,cik:0000789019,2018-01-01T00:00:00,iso4217:USD,650100000000

,concept,entity,period,value
16,dei:EntityTaxIdentificationNumber,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,911144442

,concept,entity,period,srt:ProductOrServiceAxis,unit,value,srt:RestatementAxis,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis,us-gaap:StatementBusinessSegmentsAxis,srt:StatementGeographicalAxis,msft:ProductsOrServicesSecondaryCategorizationAxis
17,us-gaap:RevenueFromContractWithCustomerExcludi...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:ProductMember,iso4217:USD,64497000000,NaN,NaN,NaN,NaN,NaN
18,us-gaap:RevenueFromContractWithCustomerExcludi...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:ProductMember,iso4217:USD,63811000000,NaN,NaN,NaN,NaN,NaN
19,us-gaap:RevenueFromContractWithCustomerExcludi...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:ProductMember,iso4217:USD,67336000000,NaN,NaN,NaN,NaN,NaN
20,us-gaap:RevenueFromContractWithCustomerExcludi...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:ServiceOtherMember,iso4217:USD,45863000000,NaN,NaN,NaN,NaN,NaN
21,us-gaap:RevenueFromContractWithCustomerExcludi...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:ServiceOtherMember,iso4217:USD,32760000000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2255,us-gaap:RevenueFromContractWithCustomerExcludi...,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,NaN,iso4217:USD,30085000000,NaN,NaN,NaN,NaN,NaN
2276,us-gaap:RevenueFromContractWithCustomerExcludi...,cik:0000789019,2016-07-02T00:00:00/2016-10-01T00:00:00,NaN,iso4217:USD,21928000000,NaN,NaN,NaN,NaN,NaN
2277,us-gaap:RevenueFromContractWithCustomerExcludi...,cik:0000789019,2016-10-01T00:00:00/2017-01-01T00:00:00,NaN,iso4217:USD,25826000000,NaN,NaN,NaN,NaN,NaN
2278,us-gaap:RevenueFromContractWithCustomerExcludi...,cik:0000789019,2017-01-01T00:00:00/2017-04-01T00:00:00,NaN,iso4217:USD,23212000000,NaN,NaN,NaN,NaN,NaN
2279,us-gaap:RevenueFromContractWithCustomerExcludi...,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,NaN,iso4217:USD,25605000000,NaN,NaN,NaN,NaN,NaN

,concept,entity,period,srt:ProductOrServiceAxis,unit,value
26,us-gaap:CostOfGoodsAndServicesSold,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:ProductMember,iso4217:USD,15420000000
27,us-gaap:CostOfGoodsAndServicesSold,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:ProductMember,iso4217:USD,15175000000
28,us-gaap:CostOfGoodsAndServicesSold,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:ProductMember,iso4217:USD,17880000000
29,us-gaap:CostOfGoodsAndServicesSold,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:ServiceOtherMember,iso4217:USD,22933000000
30,us-gaap:CostOfGoodsAndServicesSold,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:ServiceOtherMember,iso4217:USD,19086000000
31,us-gaap:CostOfGoodsAndServicesSold,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:ServiceOtherMember,iso4217:USD,14900000000
32,us-gaap:CostOfGoodsAndServicesSold,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,iso4217:USD,38353000000
33,us-gaap:CostOfGoodsAndServicesSold,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,NaN,iso4217:USD,34261000000
34,us-gaap:CostOfGoodsAndServicesSold,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,NaN,iso4217:USD,32780000000

,concept,entity,period,unit,value
35,us-gaap:GrossProfit,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,72007000000
36,us-gaap:GrossProfit,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,62310000000
37,us-gaap:GrossProfit,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,58374000000
2256,us-gaap:GrossProfit,cik:0000789019,2017-07-01T00:00:00/2017-10-01T00:00:00,iso4217:USD,16260000000
2257,us-gaap:GrossProfit,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,iso4217:USD,17854000000
2258,us-gaap:GrossProfit,cik:0000789019,2018-01-01T00:00:00/2018-04-01T00:00:00,iso4217:USD,17550000000
2259,us-gaap:GrossProfit,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,20343000000
2280,us-gaap:GrossProfit,cik:0000789019,2016-07-02T00:00:00/2016-10-01T00:00:00,iso4217:USD,14084000000
2281,us-gaap:GrossProfit,cik:0000789019,2016-10-01T00:00:00/2017-01-01T00:00:00,iso4217:USD,15925000000
2282,us-gaap:GrossProfit,cik:0000789019,2017-01-01T00:00:00/2017-04-01T00:00:00,iso4217:USD,15152000000
2283,us-gaap:GrossProfit,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,17149000000

,concept,entity,period,unit,value
38,us-gaap:ResearchAndDevelopmentExpense,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,14726000000
39,us-gaap:ResearchAndDevelopmentExpense,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,13037000000
40,us-gaap:ResearchAndDevelopmentExpense,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,11988000000

,concept,entity,period,unit,value
41,us-gaap:SellingAndMarketingExpense,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,17469000000
42,us-gaap:SellingAndMarketingExpense,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,15461000000
43,us-gaap:SellingAndMarketingExpense,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,14635000000

,concept,entity,period,unit,value
44,us-gaap:GeneralAndAdministrativeExpense,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,4754000000
45,us-gaap:GeneralAndAdministrativeExpense,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,4481000000
46,us-gaap:GeneralAndAdministrativeExpense,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,4563000000

,concept,entity,period,unit,value
47,msft:ImpairmentAndRestructuringExpenses,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,0
48,msft:ImpairmentAndRestructuringExpenses,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,306000000
49,msft:ImpairmentAndRestructuringExpenses,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,1110000000

,concept,entity,period,unit,value,srt:ConsolidationItemsAxis,us-gaap:StatementBusinessSegmentsAxis
50,us-gaap:OperatingIncomeLoss,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,35058000000,NaN,NaN
51,us-gaap:OperatingIncomeLoss,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,29025000000,NaN,NaN
52,us-gaap:OperatingIncomeLoss,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,26078000000,NaN,NaN
2188,us-gaap:OperatingIncomeLoss,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,12924000000,us-gaap:OperatingSegmentsMember,msft:ProductivityAndBusinessProcessesMember
2189,us-gaap:OperatingIncomeLoss,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,11389000000,us-gaap:OperatingSegmentsMember,msft:ProductivityAndBusinessProcessesMember
2190,us-gaap:OperatingIncomeLoss,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,11756000000,us-gaap:OperatingSegmentsMember,msft:ProductivityAndBusinessProcessesMember
2191,us-gaap:OperatingIncomeLoss,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,11524000000,us-gaap:OperatingSegmentsMember,msft:IntelligentCloudMember
2192,us-gaap:OperatingIncomeLoss,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,9127000000,us-gaap:OperatingSegmentsMember,msft:IntelligentCloudMember
2193,us-gaap:OperatingIncomeLoss,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,9249000000,us-gaap:OperatingSegmentsMember,msft:IntelligentCloudMember
2194,us-gaap:OperatingIncomeLoss,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,10610000000,us-gaap:OperatingSegmentsMember,msft:MorePersonalComputingMember
2195,us-gaap:OperatingIncomeLoss,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,8815000000,us-gaap:OperatingSegmentsMember,msft:MorePersonalComputingMember
2196,us-gaap:OperatingIncomeLoss,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,6183000000,us-gaap:OperatingSegmentsMember,msft:MorePersonalComputingMember
2197,us-gaap:OperatingIncomeLoss,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,0,msft:CorporateAndReconcilingItemsMember,NaN
2198,us-gaap:OperatingIncomeLoss,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-306000000,msft:CorporateAndReconcilingItemsMember,NaN
2199,us-gaap:OperatingIncomeLoss,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-1110000000,msft:CorporateAndReconcilingItemsMember,NaN
2260,us-gaap:OperatingIncomeLoss,cik:0000789019,2017-07-01T00:00:00/2017-10-01T00:00:00,iso4217:USD,7708000000,NaN,NaN
2261,us-gaap:OperatingIncomeLoss,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,iso4217:USD,8679000000,NaN,NaN
2262,us-gaap:OperatingIncomeLoss,cik:0000789019,2018-01-01T00:00:00/2018-04-01T00:00:00,iso4217:USD,8292000000,NaN,NaN
2263,us-gaap:OperatingIncomeLoss,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,10379000000,NaN,NaN
2284,us-gaap:OperatingIncomeLoss,cik:0000789019,2016-07-02T00:00:00/2016-10-01T00:00:00,iso4217:USD,6715000000,NaN,NaN
2285,us-gaap:OperatingIncomeLoss,cik:0000789019,2016-10-01T00:00:00/2017-01-01T00:00:00,iso4217:USD,7905000000,NaN,NaN
2286,us-gaap:OperatingIncomeLoss,cik:0000789019,2017-01-01T00:00:00/2017-04-01T00:00:00,iso4217:USD,6723000000,NaN,NaN
2287,us-gaap:OperatingIncomeLoss,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,7682000000,NaN,NaN

,concept,entity,period,unit,value
53,us-gaap:NonoperatingIncomeExpense,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,1416000000
54,us-gaap:NonoperatingIncomeExpense,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,876000000
55,us-gaap:NonoperatingIncomeExpense,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-439000000

,concept,entity,period,unit,value
56,us-gaap:IncomeLossFromContinuingOperationsBefo...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,36474000000
57,us-gaap:IncomeLossFromContinuingOperationsBefo...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,29901000000
58,us-gaap:IncomeLossFromContinuingOperationsBefo...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,25639000000

,concept,entity,period,unit,value,srt:RestatementAxis,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis,us-gaap:IncomeTaxAuthorityAxis
59,us-gaap:IncomeTaxExpenseBenefit,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,19903000000,NaN,NaN,NaN
60,us-gaap:IncomeTaxExpenseBenefit,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,4412000000,NaN,NaN,NaN
61,us-gaap:IncomeTaxExpenseBenefit,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,5100000000,NaN,NaN,NaN
450,us-gaap:IncomeTaxExpenseBenefit,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1945000000,srt:ScenarioPreviouslyReportedMember,NaN,NaN
451,us-gaap:IncomeTaxExpenseBenefit,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,2467000000,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201409Member,NaN
458,us-gaap:IncomeTaxExpenseBenefit,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,2953000000,srt:ScenarioPreviouslyReportedMember,NaN,NaN
459,us-gaap:IncomeTaxExpenseBenefit,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,2147000000,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201409Member,NaN
1742,us-gaap:IncomeTaxExpenseBenefit,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,13700000000,NaN,NaN,msft:TaxCutsAndJobsActMember
2300,us-gaap:IncomeTaxExpenseBenefit,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,iso4217:USD,13800000000,NaN,NaN,msft:TaxCutsAndJobsActMember
2301,us-gaap:IncomeTaxExpenseBenefit,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-104000000,NaN,NaN,msft:TaxCutsAndJobsActMember

,concept,entity,period,unit,value,us-gaap:StatementEquityComponentsAxis,srt:RestatementAxis,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis
62,us-gaap:NetIncomeLoss,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,16571000000,NaN,NaN,NaN
63,us-gaap:NetIncomeLoss,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,25489000000,NaN,NaN,NaN
64,us-gaap:NetIncomeLoss,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,20539000000,NaN,NaN,NaN
290,us-gaap:NetIncomeLoss,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,16571000000,us-gaap:RetainedEarningsMember,NaN,NaN
291,us-gaap:NetIncomeLoss,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,25489000000,us-gaap:RetainedEarningsMember,NaN,NaN
292,us-gaap:NetIncomeLoss,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,20539000000,us-gaap:RetainedEarningsMember,NaN,NaN
452,us-gaap:NetIncomeLoss,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,21204000000,NaN,srt:ScenarioPreviouslyReportedMember,NaN
453,us-gaap:NetIncomeLoss,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,4285000000,NaN,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201409Member
460,us-gaap:NetIncomeLoss,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,16798000000,NaN,srt:ScenarioPreviouslyReportedMember,NaN
461,us-gaap:NetIncomeLoss,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,3741000000,NaN,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201409Member
2264,us-gaap:NetIncomeLoss,cik:0000789019,2017-07-01T00:00:00/2017-10-01T00:00:00,iso4217:USD,6576000000,NaN,NaN,NaN
2265,us-gaap:NetIncomeLoss,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,iso4217:USD,-6302000000,NaN,NaN,NaN
2266,us-gaap:NetIncomeLoss,cik:0000789019,2018-01-01T00:00:00/2018-04-01T00:00:00,iso4217:USD,7424000000,NaN,NaN,NaN
2267,us-gaap:NetIncomeLoss,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,8873000000,NaN,NaN,NaN
2288,us-gaap:NetIncomeLoss,cik:0000789019,2016-07-02T00:00:00/2016-10-01T00:00:00,iso4217:USD,5667000000,NaN,NaN,NaN
2289,us-gaap:NetIncomeLoss,cik:0000789019,2016-10-01T00:00:00/2017-01-01T00:00:00,iso4217:USD,6267000000,NaN,NaN,NaN
2290,us-gaap:NetIncomeLoss,cik:0000789019,2017-01-01T00:00:00/2017-04-01T00:00:00,iso4217:USD,5486000000,NaN,NaN,NaN
2291,us-gaap:NetIncomeLoss,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,8069000000,NaN,NaN,NaN

,concept,entity,period,unit,value
65,us-gaap:EarningsPerShareBasic,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD/xbrli:shares,2.15
66,us-gaap:EarningsPerShareBasic,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD/xbrli:shares,3.29
67,us-gaap:EarningsPerShareBasic,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD/xbrli:shares,2.59
2268,us-gaap:EarningsPerShareBasic,cik:0000789019,2017-07-01T00:00:00/2017-10-01T00:00:00,iso4217:USD/xbrli:shares,0.85
2269,us-gaap:EarningsPerShareBasic,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,iso4217:USD/xbrli:shares,-0.82
2270,us-gaap:EarningsPerShareBasic,cik:0000789019,2018-01-01T00:00:00/2018-04-01T00:00:00,iso4217:USD/xbrli:shares,0.96
2271,us-gaap:EarningsPerShareBasic,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,iso4217:USD/xbrli:shares,1.15
2292,us-gaap:EarningsPerShareBasic,cik:0000789019,2016-07-02T00:00:00/2016-10-01T00:00:00,iso4217:USD/xbrli:shares,0.73
2293,us-gaap:EarningsPerShareBasic,cik:0000789019,2016-10-01T00:00:00/2017-01-01T00:00:00,iso4217:USD/xbrli:shares,0.81
2294,us-gaap:EarningsPerShareBasic,cik:0000789019,2017-01-01T00:00:00/2017-04-01T00:00:00,iso4217:USD/xbrli:shares,0.71
2295,us-gaap:EarningsPerShareBasic,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,iso4217:USD/xbrli:shares,1.05

,concept,entity,period,unit,value,srt:RestatementAxis,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis
68,us-gaap:EarningsPerShareDiluted,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD/xbrli:shares,2.13,NaN,NaN
69,us-gaap:EarningsPerShareDiluted,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD/xbrli:shares,3.25,NaN,NaN
70,us-gaap:EarningsPerShareDiluted,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD/xbrli:shares,2.56,NaN,NaN
454,us-gaap:EarningsPerShareDiluted,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD/xbrli:shares,2.71,srt:ScenarioPreviouslyReportedMember,NaN
455,us-gaap:EarningsPerShareDiluted,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD/xbrli:shares,0.54,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201409Member
462,us-gaap:EarningsPerShareDiluted,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD/xbrli:shares,2.10,srt:ScenarioPreviouslyReportedMember,NaN
463,us-gaap:EarningsPerShareDiluted,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD/xbrli:shares,0.46,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201409Member
2272,us-gaap:EarningsPerShareDiluted,cik:0000789019,2017-07-01T00:00:00/2017-10-01T00:00:00,iso4217:USD/xbrli:shares,0.84,NaN,NaN
2273,us-gaap:EarningsPerShareDiluted,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,iso4217:USD/xbrli:shares,-0.82,NaN,NaN
2274,us-gaap:EarningsPerShareDiluted,cik:0000789019,2018-01-01T00:00:00/2018-04-01T00:00:00,iso4217:USD/xbrli:shares,0.95,NaN,NaN
2275,us-gaap:EarningsPerShareDiluted,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,iso4217:USD/xbrli:shares,1.14,NaN,NaN
2296,us-gaap:EarningsPerShareDiluted,cik:0000789019,2016-07-02T00:00:00/2016-10-01T00:00:00,iso4217:USD/xbrli:shares,0.72,NaN,NaN
2297,us-gaap:EarningsPerShareDiluted,cik:0000789019,2016-10-01T00:00:00/2017-01-01T00:00:00,iso4217:USD/xbrli:shares,0.80,NaN,NaN
2298,us-gaap:EarningsPerShareDiluted,cik:0000789019,2017-01-01T00:00:00/2017-04-01T00:00:00,iso4217:USD/xbrli:shares,0.70,NaN,NaN
2299,us-gaap:EarningsPerShareDiluted,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,iso4217:USD/xbrli:shares,1.03,NaN,NaN

,concept,entity,period,unit,value
71,us-gaap:WeightedAverageNumberOfSharesOutstandi...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,xbrli:shares,7700000000
72,us-gaap:WeightedAverageNumberOfSharesOutstandi...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,xbrli:shares,7746000000
73,us-gaap:WeightedAverageNumberOfSharesOutstandi...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,xbrli:shares,7925000000

,concept,entity,period,unit,value
74,us-gaap:WeightedAverageNumberOfDilutedSharesOu...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,xbrli:shares,7794000000
75,us-gaap:WeightedAverageNumberOfDilutedSharesOu...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,xbrli:shares,7832000000
76,us-gaap:WeightedAverageNumberOfDilutedSharesOu...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,xbrli:shares,8013000000

,concept,entity,period,unit,value
77,us-gaap:CommonStockDividendsPerShareDeclared,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD/xbrli:shares,1.68
78,us-gaap:CommonStockDividendsPerShareDeclared,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD/xbrli:shares,1.56
79,us-gaap:CommonStockDividendsPerShareDeclared,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD/xbrli:shares,1.44
2025,us-gaap:CommonStockDividendsPerShareDeclared,cik:0000789019,2017-07-01T00:00:00/2017-10-01T00:00:00,iso4217:USD/xbrli:shares,0.42
2026,us-gaap:CommonStockDividendsPerShareDeclared,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,iso4217:USD/xbrli:shares,0.42
2027,us-gaap:CommonStockDividendsPerShareDeclared,cik:0000789019,2018-01-01T00:00:00/2018-04-01T00:00:00,iso4217:USD/xbrli:shares,0.42
2028,us-gaap:CommonStockDividendsPerShareDeclared,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,iso4217:USD/xbrli:shares,0.42
2029,us-gaap:CommonStockDividendsPerShareDeclared,cik:0000789019,2016-07-02T00:00:00/2016-10-01T00:00:00,iso4217:USD/xbrli:shares,0.39
2030,us-gaap:CommonStockDividendsPerShareDeclared,cik:0000789019,2016-10-01T00:00:00/2017-01-01T00:00:00,iso4217:USD/xbrli:shares,0.39
2031,us-gaap:CommonStockDividendsPerShareDeclared,cik:0000789019,2017-01-01T00:00:00/2017-04-01T00:00:00,iso4217:USD/xbrli:shares,0.39
2032,us-gaap:CommonStockDividendsPerShareDeclared,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,iso4217:USD/xbrli:shares,0.39

,concept,entity,period,unit,value
80,us-gaap:OtherComprehensiveIncomeLossDerivative...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,39000000
81,us-gaap:OtherComprehensiveIncomeLossDerivative...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-218000000
82,us-gaap:OtherComprehensiveIncomeLossDerivative...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-238000000

,concept,entity,period,unit,value
83,us-gaap:OtherComprehensiveIncomeLossAvailableF...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-2717000000
84,us-gaap:OtherComprehensiveIncomeLossAvailableF...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-1116000000
85,us-gaap:OtherComprehensiveIncomeLossAvailableF...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-228000000

,concept,entity,period,unit,value
86,us-gaap:OtherComprehensiveIncomeLossForeignCur...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-178000000
87,us-gaap:OtherComprehensiveIncomeLossForeignCur...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,167000000
88,us-gaap:OtherComprehensiveIncomeLossForeignCur...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-262000000

,concept,entity,period,unit,value,us-gaap:StatementEquityComponentsAxis
89,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-2856000000,NaN
90,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-1167000000,NaN
91,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-728000000,NaN
306,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-2856000000,us-gaap:AccumulatedOtherComprehensiveIncomeMember
307,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-1167000000,us-gaap:AccumulatedOtherComprehensiveIncomeMember
308,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-728000000,us-gaap:AccumulatedOtherComprehensiveIncomeMember
2072,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,39000000,us-gaap:AccumulatedNetGainLossFromDesignatedOr...
2073,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-218000000,us-gaap:AccumulatedNetGainLossFromDesignatedOr...
2074,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-238000000,us-gaap:AccumulatedNetGainLossFromDesignatedOr...
2091,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-2717000000,msft:AccumulatedNetUnrealizedGainLossOnInvestm...
2092,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-1116000000,msft:AccumulatedNetUnrealizedGainLossOnInvestm...
2093,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-228000000,msft:AccumulatedNetUnrealizedGainLossOnInvestm...
2098,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-178000000,msft:AccumulatedTranslationAdjustmentAndOtherM...
2099,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,167000000,msft:AccumulatedTranslationAdjustmentAndOtherM...
2100,us-gaap:OtherComprehensiveIncomeLossNetOfTaxPo...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-262000000,msft:AccumulatedTranslationAdjustmentAndOtherM...

,concept,entity,period,unit,value
92,us-gaap:ComprehensiveIncomeNetOfTax,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,13715000000
93,us-gaap:ComprehensiveIncomeNetOfTax,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,24322000000
94,us-gaap:ComprehensiveIncomeNetOfTax,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,19811000000

,concept,entity,period,unit,value,us-gaap:InvestmentTypeAxis
95,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,11946000000,NaN
96,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,7663000000,NaN
269,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,6510000000,NaN
270,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2015-07-01T00:00:00,iso4217:USD,5595000000,NaN
528,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,3942000000,us-gaap:CashMember
571,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,246000000,us-gaap:MoneyMarketFundsMember
572,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,2215000000,us-gaap:CommercialPaperMember
573,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1865000000,us-gaap:CertificatesOfDepositMember
574,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,3678000000,us-gaap:USGovernmentAgenciesDebtSecuritiesMember
575,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:ForeignGovernmentDebtSecuritiesMember
576,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:AssetBackedSecuritiesMember
577,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:CorporateDebtSecuritiesMember
578,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:USStatesAndPoliticalSubdivisionsMember
579,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:EquitySecuritiesMember
602,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,msft:OtherSecurityInvestmentsMember
608,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,3624000000,us-gaap:CashMember
651,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,1478000000,us-gaap:MoneyMarketFundsMember
652,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,69000000,us-gaap:CommercialPaperMember
653,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,972000000,us-gaap:CertificatesOfDepositMember
654,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,16000000,us-gaap:USGovernmentAgenciesDebtSecuritiesMember
655,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,1504000000,us-gaap:ForeignGovernmentDebtSecuritiesMember
656,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:AssetBackedSecuritiesMember
657,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:CorporateDebtSecuritiesMember
658,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:USStatesAndPoliticalSubdivisionsMember
659,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:EquitySecuritiesMember
682,us-gaap:CashAndCashEquivalentsAtCarryingValue,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,msft:OtherSecurityInvestmentsMember

,concept,entity,period,unit,value,us-gaap:InvestmentTypeAxis
97,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,121822000000,NaN
98,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,125318000000,NaN
529,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:CashMember
580,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:MoneyMarketFundsMember
581,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,298000000,us-gaap:CommercialPaperMember
582,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,193000000,us-gaap:CertificatesOfDepositMember
583,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,105079000000,us-gaap:USGovernmentAgenciesDebtSecuritiesMember
584,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,5173000000,us-gaap:ForeignGovernmentDebtSecuritiesMember
585,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,3859000000,us-gaap:AssetBackedSecuritiesMember
586,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,6912000000,us-gaap:CorporateDebtSecuritiesMember
587,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,307000000,us-gaap:USStatesAndPoliticalSubdivisionsMember
588,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:EquitySecuritiesMember
603,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1000000,msft:OtherSecurityInvestmentsMember
609,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:CashMember
660,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:MoneyMarketFundsMember
661,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,250000000,us-gaap:CommercialPaperMember
662,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,386000000,us-gaap:CertificatesOfDepositMember
663,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,111828000000,us-gaap:USGovernmentAgenciesDebtSecuritiesMember
664,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,3761000000,us-gaap:ForeignGovernmentDebtSecuritiesMember
665,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,3931000000,us-gaap:AssetBackedSecuritiesMember
666,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,4835000000,us-gaap:CorporateDebtSecuritiesMember
667,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,327000000,us-gaap:USStatesAndPoliticalSubdivisionsMember
668,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:EquitySecuritiesMember
683,us-gaap:AvailableForSaleSecuritiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,msft:OtherSecurityInvestmentsMember

,concept,entity,period,unit,value
99,us-gaap:CashCashEquivalentsAndShortTermInvestm...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,133768000000
100,us-gaap:CashCashEquivalentsAndShortTermInvestm...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,132981000000

,concept,entity,period,unit,value,srt:RestatementAxis,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis
101,us-gaap:AccountsReceivableNetCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,26481000000,NaN,NaN
102,us-gaap:AccountsReceivableNetCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,22431000000,NaN,NaN
464,us-gaap:AccountsReceivableNetCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,19792000000,srt:ScenarioPreviouslyReportedMember,NaN
465,us-gaap:AccountsReceivableNetCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,2639000000,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201409Member
466,us-gaap:AccountsReceivableNetCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201602Member

,concept,entity,period,unit,value
103,us-gaap:InventoryNet,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,2662000000
104,us-gaap:InventoryNet,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,2181000000

,concept,entity,period,unit,value,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis,us-gaap:StatementScenarioAxis
105,us-gaap:OtherAssetsCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,6751000000,NaN,NaN
106,us-gaap:OtherAssetsCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,5103000000,NaN,NaN
494,us-gaap:OtherAssetsCurrent,cik:0000789019,2018-07-02T00:00:00,iso4217:USD,-150000000,us-gaap:AccountingStandardsUpdate201616Member,us-gaap:ScenarioPlanMember

,concept,entity,period,unit,value
107,us-gaap:AssetsCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,169662000000
108,us-gaap:AssetsCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,162696000000

,concept,entity,period,unit,value,us-gaap:LeaseArrangementTypeAxis
109,us-gaap:PropertyPlantAndEquipmentNet,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,29460000000,NaN
110,us-gaap:PropertyPlantAndEquipmentNet,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,23734000000,NaN
1939,us-gaap:PropertyPlantAndEquipmentNet,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,4139000000,msft:FinanceLeaseMember
1940,us-gaap:PropertyPlantAndEquipmentNet,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,2497000000,msft:FinanceLeaseMember

,concept,entity,period,unit,value,srt:RestatementAxis,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis
111,us-gaap:OperatingLeaseRightOfUseAsset,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,6686000000,NaN,NaN
112,us-gaap:OperatingLeaseRightOfUseAsset,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,6555000000,NaN,NaN
467,us-gaap:OperatingLeaseRightOfUseAsset,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,srt:ScenarioPreviouslyReportedMember,NaN
468,us-gaap:OperatingLeaseRightOfUseAsset,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201409Member
469,us-gaap:OperatingLeaseRightOfUseAsset,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,6555000000,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201602Member

,concept,entity,period,unit,value,us-gaap:InvestmentTypeAxis
113,us-gaap:LongTermInvestments,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1862000000,NaN
114,us-gaap:LongTermInvestments,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,6023000000,NaN
530,us-gaap:LongTermInvestments,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:CashMember
589,us-gaap:LongTermInvestments,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:MoneyMarketFundsMember
590,us-gaap:LongTermInvestments,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:CommercialPaperMember
591,us-gaap:LongTermInvestments,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:CertificatesOfDepositMember
592,us-gaap:LongTermInvestments,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:USGovernmentAgenciesDebtSecuritiesMember
593,us-gaap:LongTermInvestments,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:ForeignGovernmentDebtSecuritiesMember
594,us-gaap:LongTermInvestments,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:AssetBackedSecuritiesMember
595,us-gaap:LongTermInvestments,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:CorporateDebtSecuritiesMember
596,us-gaap:LongTermInvestments,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0,us-gaap:USStatesAndPoliticalSubdivisionsMember
597,us-gaap:LongTermInvestments,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1305000000,us-gaap:EquitySecuritiesMember
604,us-gaap:LongTermInvestments,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,557000000,msft:OtherSecurityInvestmentsMember
610,us-gaap:LongTermInvestments,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:CashMember
669,us-gaap:LongTermInvestments,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:MoneyMarketFundsMember
670,us-gaap:LongTermInvestments,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:CommercialPaperMember
671,us-gaap:LongTermInvestments,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:CertificatesOfDepositMember
672,us-gaap:LongTermInvestments,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:USGovernmentAgenciesDebtSecuritiesMember
673,us-gaap:LongTermInvestments,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:ForeignGovernmentDebtSecuritiesMember
674,us-gaap:LongTermInvestments,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:AssetBackedSecuritiesMember
675,us-gaap:LongTermInvestments,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:CorporateDebtSecuritiesMember
676,us-gaap:LongTermInvestments,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,us-gaap:USStatesAndPoliticalSubdivisionsMember
677,us-gaap:LongTermInvestments,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,5500000000,us-gaap:EquitySecuritiesMember
684,us-gaap:LongTermInvestments,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,523000000,msft:OtherSecurityInvestmentsMember

,concept,entity,period,unit,value,us-gaap:BusinessAcquisitionAxis,us-gaap:StatementBusinessSegmentsAxis
115,us-gaap:Goodwill,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,35683000000,NaN,NaN
116,us-gaap:Goodwill,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,35122000000,NaN,NaN
1221,us-gaap:Goodwill,cik:0000789019,2016-12-09T00:00:00,iso4217:USD,16803000000,msft:LinkedInCorporationMember,NaN
1250,us-gaap:Goodwill,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,6678000000,NaN,msft:ProductivityAndBusinessProcessesMember
1251,us-gaap:Goodwill,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,5467000000,NaN,msft:IntelligentCloudMember
1252,us-gaap:Goodwill,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,5727000000,NaN,msft:MorePersonalComputingMember
1253,us-gaap:Goodwill,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,17872000000,NaN,NaN
1262,us-gaap:Goodwill,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,23739000000,NaN,msft:ProductivityAndBusinessProcessesMember
1263,us-gaap:Goodwill,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,5555000000,NaN,msft:IntelligentCloudMember
1264,us-gaap:Goodwill,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,5828000000,NaN,msft:MorePersonalComputingMember
1273,us-gaap:Goodwill,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,23823000000,NaN,msft:ProductivityAndBusinessProcessesMember
1274,us-gaap:Goodwill,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,5703000000,NaN,msft:IntelligentCloudMember
1275,us-gaap:Goodwill,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,6157000000,NaN,msft:MorePersonalComputingMember

,concept,entity,period,unit,value,us-gaap:FiniteLivedIntangibleAssetsByMajorClassAxis
117,us-gaap:FiniteLivedIntangibleAssetsNet,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,8053000000,NaN
118,us-gaap:FiniteLivedIntangibleAssetsNet,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,10106000000,NaN
1291,us-gaap:FiniteLivedIntangibleAssetsNet,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,2202000000,us-gaap:TechnologyBasedIntangibleAssetsMember
1292,us-gaap:FiniteLivedIntangibleAssetsNet,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,2826000000,us-gaap:CustomerRelationshipsMember
1293,us-gaap:FiniteLivedIntangibleAssetsNet,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,2935000000,us-gaap:MarketingRelatedIntangibleAssetsMember
1294,us-gaap:FiniteLivedIntangibleAssetsNet,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,90000000,us-gaap:ContractualRightsMember
1305,us-gaap:FiniteLivedIntangibleAssetsNet,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,3447000000,us-gaap:TechnologyBasedIntangibleAssetsMember
1306,us-gaap:FiniteLivedIntangibleAssetsNet,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,3353000000,us-gaap:CustomerRelationshipsMember
1307,us-gaap:FiniteLivedIntangibleAssetsNet,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,3187000000,us-gaap:MarketingRelatedIntangibleAssetsMember
1308,us-gaap:FiniteLivedIntangibleAssetsNet,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,119000000,us-gaap:ContractualRightsMember

,concept,entity,period,unit,value
119,us-gaap:OtherAssetsNoncurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,7442000000
120,us-gaap:OtherAssetsNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,6076000000

,concept,entity,period,unit,value
121,us-gaap:Assets,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,258848000000
122,us-gaap:Assets,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,250312000000

,concept,entity,period,unit,value
123,us-gaap:AccountsPayableCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,8617000000
124,us-gaap:AccountsPayableCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,7390000000

,concept,entity,period,unit,value
125,us-gaap:ShortTermBorrowings,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0
126,us-gaap:ShortTermBorrowings,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,9072000000

,concept,entity,period,unit,value
127,us-gaap:LongTermDebtCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,3998000000
128,us-gaap:LongTermDebtCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,1049000000

,concept,entity,period,unit,value
129,us-gaap:EmployeeRelatedLiabilitiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,6103000000
130,us-gaap:EmployeeRelatedLiabilitiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,5819000000

,concept,entity,period,unit,value
131,us-gaap:AccruedIncomeTaxesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,2121000000
132,us-gaap:AccruedIncomeTaxesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,718000000

,concept,entity,period,unit,value
133,us-gaap:ContractWithCustomerLiabilityCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,28905000000
134,us-gaap:ContractWithCustomerLiabilityCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,24013000000

,concept,entity,period,unit,value
135,us-gaap:OtherLiabilitiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,8744000000
136,us-gaap:OtherLiabilitiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,7684000000

,concept,entity,period,unit,value
137,us-gaap:LiabilitiesCurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,58488000000
138,us-gaap:LiabilitiesCurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,55745000000

,concept,entity,period,unit,value
139,us-gaap:LongTermDebtNoncurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,72242000000
140,us-gaap:LongTermDebtNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,76073000000

,concept,entity,period,unit,value,srt:RestatementAxis
141,us-gaap:AccruedIncomeTaxesNoncurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,30265000000,NaN
142,us-gaap:AccruedIncomeTaxesNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,13485000000,NaN
445,us-gaap:AccruedIncomeTaxesNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,srt:ScenarioPreviouslyReportedMember

,concept,entity,period,unit,value
143,us-gaap:ContractWithCustomerLiabilityNoncurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,3815000000
144,us-gaap:ContractWithCustomerLiabilityNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,2643000000

,concept,entity,period,unit,value,srt:RestatementAxis,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis,us-gaap:StatementScenarioAxis,us-gaap:BalanceSheetLocationAxis
145,us-gaap:DeferredTaxLiabilitiesNoncurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,541000000,NaN,NaN,NaN,NaN
146,us-gaap:DeferredTaxLiabilitiesNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,5734000000,NaN,NaN,NaN,NaN
478,us-gaap:DeferredTaxLiabilitiesNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,531000000,srt:ScenarioPreviouslyReportedMember,NaN,NaN,NaN
479,us-gaap:DeferredTaxLiabilitiesNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,5203000000,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201409Member,NaN,NaN
480,us-gaap:DeferredTaxLiabilitiesNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201602Member,NaN,NaN
493,us-gaap:DeferredTaxLiabilitiesNoncurrent,cik:0000789019,2018-07-02T00:00:00,iso4217:USD,2100000000,NaN,us-gaap:AccountingStandardsUpdate201616Member,us-gaap:ScenarioPlanMember,NaN
1814,us-gaap:DeferredTaxLiabilitiesNoncurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,541000000,NaN,NaN,NaN,msft:DeferredIncomeTaxLiabilitiesNoncurrentMember
1831,us-gaap:DeferredTaxLiabilitiesNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,5734000000,NaN,NaN,NaN,msft:DeferredIncomeTaxLiabilitiesNoncurrentMember

,concept,entity,period,unit,value,srt:RestatementAxis,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis
147,us-gaap:OperatingLeaseLiabilityNoncurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,5568000000,NaN,NaN
148,us-gaap:OperatingLeaseLiabilityNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,5372000000,NaN,NaN
481,us-gaap:OperatingLeaseLiabilityNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,srt:ScenarioPreviouslyReportedMember,NaN
482,us-gaap:OperatingLeaseLiabilityNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201409Member
483,us-gaap:OperatingLeaseLiabilityNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,5372000000,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201602Member

,concept,entity,period,unit,value,srt:RestatementAxis
149,us-gaap:OtherLiabilitiesNoncurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,5211000000,NaN
150,us-gaap:OtherLiabilitiesNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,3549000000,NaN
446,us-gaap:OtherLiabilitiesNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,17034000000,srt:ScenarioPreviouslyReportedMember

,concept,entity,period,unit,value
151,us-gaap:Liabilities,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,176130000000
152,us-gaap:Liabilities,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,162601000000

,concept,entity,period,unit,value
153,us-gaap:CommitmentsAndContingencies,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,None
154,us-gaap:CommitmentsAndContingencies,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,None

,concept,entity,period,unit,value
155,us-gaap:CommonStocksIncludingAdditionalPaidInC...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,71223000000
156,us-gaap:CommonStocksIncludingAdditionalPaidInC...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,69315000000

,concept,entity,period,unit,value,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis,us-gaap:StatementScenarioAxis
157,us-gaap:RetainedEarningsAccumulatedDeficit,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,13682000000,NaN,NaN
158,us-gaap:RetainedEarningsAccumulatedDeficit,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,17769000000,NaN,NaN
491,us-gaap:RetainedEarningsAccumulatedDeficit,cik:0000789019,2018-07-02T00:00:00,iso4217:USD,550000000,us-gaap:AccountingStandardsUpdate201616Member,us-gaap:ScenarioPlanMember

,concept,entity,period,unit,value
159,us-gaap:AccumulatedOtherComprehensiveIncomeLos...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,-2187000000
160,us-gaap:AccumulatedOtherComprehensiveIncomeLos...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,627000000

,concept,entity,period,unit,value,us-gaap:StatementEquityComponentsAxis,srt:RestatementAxis,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis
161,us-gaap:StockholdersEquity,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,82718000000,NaN,NaN,NaN
162,us-gaap:StockholdersEquity,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,87711000000,NaN,NaN,NaN
271,us-gaap:StockholdersEquity,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,69315000000,us-gaap:CommonStockIncludingAdditionalPaidInCa...,NaN,NaN
272,us-gaap:StockholdersEquity,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,68178000000,us-gaap:CommonStockIncludingAdditionalPaidInCa...,NaN,NaN
273,us-gaap:StockholdersEquity,cik:0000789019,2015-07-01T00:00:00,iso4217:USD,68465000000,us-gaap:CommonStockIncludingAdditionalPaidInCa...,NaN,NaN
286,us-gaap:StockholdersEquity,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,71223000000,us-gaap:CommonStockIncludingAdditionalPaidInCa...,NaN,NaN
287,us-gaap:StockholdersEquity,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,17769000000,us-gaap:RetainedEarningsMember,NaN,NaN
288,us-gaap:StockholdersEquity,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,13118000000,us-gaap:RetainedEarningsMember,NaN,NaN
289,us-gaap:StockholdersEquity,cik:0000789019,2015-07-01T00:00:00,iso4217:USD,16191000000,us-gaap:RetainedEarningsMember,NaN,NaN
302,us-gaap:StockholdersEquity,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,13682000000,us-gaap:RetainedEarningsMember,NaN,NaN
303,us-gaap:StockholdersEquity,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,627000000,us-gaap:AccumulatedOtherComprehensiveIncomeMember,NaN,NaN
304,us-gaap:StockholdersEquity,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,1794000000,us-gaap:AccumulatedOtherComprehensiveIncomeMember,NaN,NaN
305,us-gaap:StockholdersEquity,cik:0000789019,2015-07-01T00:00:00,iso4217:USD,2522000000,us-gaap:AccumulatedOtherComprehensiveIncomeMember,NaN,NaN
312,us-gaap:StockholdersEquity,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,-2187000000,us-gaap:AccumulatedOtherComprehensiveIncomeMember,NaN,NaN
313,us-gaap:StockholdersEquity,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,83090000000,NaN,NaN,NaN
488,us-gaap:StockholdersEquity,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,72394000000,NaN,srt:ScenarioPreviouslyReportedMember,NaN
489,us-gaap:StockholdersEquity,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,15317000000,NaN,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201409Member
490,us-gaap:StockholdersEquity,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,0,NaN,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201602Member
2057,us-gaap:StockholdersEquity,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,134000000,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,NaN,NaN
2058,us-gaap:StockholdersEquity,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,352000000,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,NaN,NaN
2059,us-gaap:StockholdersEquity,cik:0000789019,2015-07-01T00:00:00,iso4217:USD,590000000,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,NaN,NaN
2075,us-gaap:StockholdersEquity,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,173000000,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,NaN,NaN
2076,us-gaap:StockholdersEquity,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,1825000000,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,NaN,NaN
2077,us-gaap:StockholdersEquity,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,2941000000,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,NaN,NaN
2078,us-gaap:StockholdersEquity,cik:0000789019,2015-07-01T00:00:00,iso4217:USD,3169000000,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,NaN,NaN
2094,us-gaap:StockholdersEquity,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,-892000000,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,NaN,NaN
2095,us-gaap:StockholdersEquity,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,-1332000000,msft:AccumulatedTranslationAdjustmentAndOtherM...,NaN,NaN
2096,us-gaap:StockholdersEquity,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,-1499000000,msft:AccumulatedTranslationAdjustmentAndOtherM...,NaN,NaN
2097,us-gaap:StockholdersEquity,cik:0000789019,2015-07-01T00:00:00,iso4217:USD,-1237000000,msft:AccumulatedTranslationAdjustmentAndOtherM...,NaN,NaN
2101,us-gaap:StockholdersEquity,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,-1510000000,msft:AccumulatedTranslationAdjustmentAndOtherM...,NaN,NaN

,concept,entity,period,unit,value
163,us-gaap:LiabilitiesAndStockholdersEquity,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,258848000000
164,us-gaap:LiabilitiesAndStockholdersEquity,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,250312000000

,concept,entity,period,unit,value
165,us-gaap:AllowanceForDoubtfulAccountsReceivable...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,377000000
166,us-gaap:AllowanceForDoubtfulAccountsReceivable...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,345000000

,concept,entity,period,unit,value,us-gaap:LeaseArrangementTypeAxis
167,us-gaap:AccumulatedDepreciationDepletionAndAmo...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,29223000000,NaN
168,us-gaap:AccumulatedDepreciationDepletionAndAmo...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,24179000000,NaN
1937,us-gaap:AccumulatedDepreciationDepletionAndAmo...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,404000000,msft:FinanceLeaseMember
1938,us-gaap:AccumulatedDepreciationDepletionAndAmo...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,161000000,msft:FinanceLeaseMember

,concept,entity,period,unit,value
169,us-gaap:CommonStockSharesAuthorized,cik:0000789019,2018-07-01T00:00:00,xbrli:shares,24000000000
170,us-gaap:CommonStockSharesAuthorized,cik:0000789019,2017-07-01T00:00:00,xbrli:shares,24000000000

,concept,entity,period,unit,value
171,us-gaap:CommonStockSharesOutstanding,cik:0000789019,2018-07-01T00:00:00,xbrli:shares,7677000000
172,us-gaap:CommonStockSharesOutstanding,cik:0000789019,2017-07-01T00:00:00,xbrli:shares,7708000000
1979,us-gaap:CommonStockSharesOutstanding,cik:0000789019,2016-07-01T00:00:00,xbrli:shares,7808000000
1980,us-gaap:CommonStockSharesOutstanding,cik:0000789019,2015-07-01T00:00:00,xbrli:shares,8027000000

,concept,entity,period,unit,value
173,us-gaap:AssetImpairmentCharges,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,0
174,us-gaap:AssetImpairmentCharges,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,0
175,us-gaap:AssetImpairmentCharges,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,630000000

,concept,entity,period,unit,value
176,msft:DepreciationAmortizationAndOther,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,10261000000
177,msft:DepreciationAmortizationAndOther,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,8778000000
178,msft:DepreciationAmortizationAndOther,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,6622000000

,concept,entity,period,unit,value
179,us-gaap:ShareBasedCompensation,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,3940000000
180,us-gaap:ShareBasedCompensation,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,3266000000
181,us-gaap:ShareBasedCompensation,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,2668000000

,concept,entity,period,unit,value
182,msft:GainLossOnInvestmentsAndDerivativeInstrum...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,2212000000
183,msft:GainLossOnInvestmentsAndDerivativeInstrum...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,2073000000
184,msft:GainLossOnInvestmentsAndDerivativeInstrum...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,223000000

,concept,entity,period,unit,value
185,us-gaap:DeferredIncomeTaxExpenseBenefit,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-5143000000
186,us-gaap:DeferredIncomeTaxExpenseBenefit,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-829000000
187,us-gaap:DeferredIncomeTaxExpenseBenefit,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,2479000000

,concept,entity,period,unit,value
188,us-gaap:IncreaseDecreaseInAccountsReceivable,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,3862000000
189,us-gaap:IncreaseDecreaseInAccountsReceivable,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1216000000
190,us-gaap:IncreaseDecreaseInAccountsReceivable,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-562000000

,concept,entity,period,unit,value
191,us-gaap:IncreaseDecreaseInInventories,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,465000000
192,us-gaap:IncreaseDecreaseInInventories,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-50000000
193,us-gaap:IncreaseDecreaseInInventories,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-600000000

,concept,entity,period,unit,value
194,us-gaap:IncreaseDecreaseInOtherCurrentAssets,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,952000000
195,us-gaap:IncreaseDecreaseInOtherCurrentAssets,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-1028000000
196,us-gaap:IncreaseDecreaseInOtherCurrentAssets,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,1212000000

,concept,entity,period,unit,value
197,us-gaap:IncreaseDecreaseInOtherNoncurrentAssets,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,285000000
198,us-gaap:IncreaseDecreaseInOtherNoncurrentAssets,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,917000000
199,us-gaap:IncreaseDecreaseInOtherNoncurrentAssets,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,1110000000

,concept,entity,period,unit,value
200,us-gaap:IncreaseDecreaseInAccountsPayable,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,1148000000
201,us-gaap:IncreaseDecreaseInAccountsPayable,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,81000000
202,us-gaap:IncreaseDecreaseInAccountsPayable,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,88000000

,concept,entity,period,unit,value
203,us-gaap:IncreaseDecreaseInContractWithCustomer...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,5922000000
204,us-gaap:IncreaseDecreaseInContractWithCustomer...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,3820000000
205,us-gaap:IncreaseDecreaseInContractWithCustomer...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,2565000000

,concept,entity,period,unit,value
206,us-gaap:IncreaseDecreaseInAccruedIncomeTaxesPa...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,18183000000
207,us-gaap:IncreaseDecreaseInAccruedIncomeTaxesPa...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1792000000
208,us-gaap:IncreaseDecreaseInAccruedIncomeTaxesPa...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-298000000

,concept,entity,period,unit,value
209,us-gaap:IncreaseDecreaseInOtherCurrentLiabilities,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,798000000
210,us-gaap:IncreaseDecreaseInOtherCurrentLiabilities,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,356000000
211,us-gaap:IncreaseDecreaseInOtherCurrentLiabilities,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-179000000

,concept,entity,period,unit,value
212,us-gaap:IncreaseDecreaseInOtherNoncurrentLiabi...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-20000000
213,us-gaap:IncreaseDecreaseInOtherNoncurrentLiabi...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-118000000
214,us-gaap:IncreaseDecreaseInOtherNoncurrentLiabi...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-406000000

,concept,entity,period,unit,value
215,us-gaap:NetCashProvidedByUsedInOperatingActivi...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,43884000000
216,us-gaap:NetCashProvidedByUsedInOperatingActivi...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,39507000000
217,us-gaap:NetCashProvidedByUsedInOperatingActivi...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,33325000000

,concept,entity,period,unit,value
218,us-gaap:ProceedsFromRepaymentsOfShortTermDebtM...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-7324000000
219,us-gaap:ProceedsFromRepaymentsOfShortTermDebtM...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-4963000000
220,us-gaap:ProceedsFromRepaymentsOfShortTermDebtM...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,7195000000

,concept,entity,period,unit,value
221,us-gaap:ProceedsFromDebtMaturingInMoreThanThre...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,7183000000
222,us-gaap:ProceedsFromDebtMaturingInMoreThanThre...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,44344000000
223,us-gaap:ProceedsFromDebtMaturingInMoreThanThre...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,13884000000

,concept,entity,period,unit,value
224,us-gaap:RepaymentsOfDebtMaturingInMoreThanThre...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,10060000000
225,us-gaap:RepaymentsOfDebtMaturingInMoreThanThre...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,7922000000
226,us-gaap:RepaymentsOfDebtMaturingInMoreThanThre...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,2796000000

,concept,entity,period,unit,value
227,us-gaap:ProceedsFromIssuanceOfCommonStock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,1002000000
228,us-gaap:ProceedsFromIssuanceOfCommonStock,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,772000000
229,us-gaap:ProceedsFromIssuanceOfCommonStock,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,668000000

,concept,entity,period,unit,value
230,us-gaap:PaymentsForRepurchaseOfCommonStock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,10721000000
231,us-gaap:PaymentsForRepurchaseOfCommonStock,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,11788000000
232,us-gaap:PaymentsForRepurchaseOfCommonStock,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,15969000000

,concept,entity,period,unit,value
233,us-gaap:PaymentsOfDividendsCommonStock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,12699000000
234,us-gaap:PaymentsOfDividendsCommonStock,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,11845000000
235,us-gaap:PaymentsOfDividendsCommonStock,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,11006000000

,concept,entity,period,unit,value
236,us-gaap:ProceedsFromPaymentsForOtherFinancingA...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-971000000
237,us-gaap:ProceedsFromPaymentsForOtherFinancingA...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-190000000
238,us-gaap:ProceedsFromPaymentsForOtherFinancingA...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-369000000

,concept,entity,period,unit,value
239,us-gaap:NetCashProvidedByUsedInFinancingActivi...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-33590000000
240,us-gaap:NetCashProvidedByUsedInFinancingActivi...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,8408000000
241,us-gaap:NetCashProvidedByUsedInFinancingActivi...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-8393000000

,concept,entity,period,unit,value
242,us-gaap:PaymentsToAcquirePropertyPlantAndEquip...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,11632000000
243,us-gaap:PaymentsToAcquirePropertyPlantAndEquip...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,8129000000
244,us-gaap:PaymentsToAcquirePropertyPlantAndEquip...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,8343000000

,concept,entity,period,unit,value
245,msft:AcquisitionsNetOfCashAcquiredAndPurchases...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,888000000
246,msft:AcquisitionsNetOfCashAcquiredAndPurchases...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,25944000000
247,msft:AcquisitionsNetOfCashAcquiredAndPurchases...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,1393000000

,concept,entity,period,unit,value
248,us-gaap:PaymentsToAcquireInvestments,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,137380000000
249,us-gaap:PaymentsToAcquireInvestments,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,176905000000
250,us-gaap:PaymentsToAcquireInvestments,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,129758000000

,concept,entity,period,unit,value
251,us-gaap:ProceedsFromMaturitiesPrepaymentsAndCa...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,26360000000
252,us-gaap:ProceedsFromMaturitiesPrepaymentsAndCa...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,28044000000
253,us-gaap:ProceedsFromMaturitiesPrepaymentsAndCa...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,22054000000

,concept,entity,period,unit,value
254,us-gaap:ProceedsFromSaleOfAvailableForSaleSecu...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,117577000000
255,us-gaap:ProceedsFromSaleOfAvailableForSaleSecu...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,136350000000
256,us-gaap:ProceedsFromSaleOfAvailableForSaleSecu...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,93287000000

,concept,entity,period,unit,value
257,us-gaap:IncreaseDecreaseInCollateralHeldUnderS...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,98000000
258,us-gaap:IncreaseDecreaseInCollateralHeldUnderS...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,197000000
259,us-gaap:IncreaseDecreaseInCollateralHeldUnderS...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-203000000

,concept,entity,period,unit,value
260,us-gaap:NetCashProvidedByUsedInInvestingActivi...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-6061000000
261,us-gaap:NetCashProvidedByUsedInInvestingActivi...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-46781000000
262,us-gaap:NetCashProvidedByUsedInInvestingActivi...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-23950000000

,concept,entity,period,unit,value
263,us-gaap:EffectOfExchangeRateOnCashAndCashEquiv...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,50000000
264,us-gaap:EffectOfExchangeRateOnCashAndCashEquiv...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,19000000
265,us-gaap:EffectOfExchangeRateOnCashAndCashEquiv...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-67000000

,concept,entity,period,unit,value
266,us-gaap:CashAndCashEquivalentsPeriodIncreaseDe...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,4283000000
267,us-gaap:CashAndCashEquivalentsPeriodIncreaseDe...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1153000000
268,us-gaap:CashAndCashEquivalentsPeriodIncreaseDe...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,915000000

,concept,entity,period,us-gaap:StatementEquityComponentsAxis,unit,value
274,us-gaap:StockIssuedDuringPeriodValueNewIssues,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:CommonStockIncludingAdditionalPaidInCa...,iso4217:USD,1002000000
275,us-gaap:StockIssuedDuringPeriodValueNewIssues,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:CommonStockIncludingAdditionalPaidInCa...,iso4217:USD,772000000
276,us-gaap:StockIssuedDuringPeriodValueNewIssues,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:CommonStockIncludingAdditionalPaidInCa...,iso4217:USD,668000000

,concept,entity,period,us-gaap:StatementEquityComponentsAxis,unit,value,us-gaap:ShareRepurchaseProgramAxis
277,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:CommonStockIncludingAdditionalPaidInCa...,iso4217:USD,3033000000,NaN
278,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:CommonStockIncludingAdditionalPaidInCa...,iso4217:USD,2987000000,NaN
279,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:CommonStockIncludingAdditionalPaidInCa...,iso4217:USD,3689000000,NaN
296,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:RetainedEarningsMember,iso4217:USD,7699000000,NaN
297,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:RetainedEarningsMember,iso4217:USD,8798000000,NaN
298,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:RetainedEarningsMember,iso4217:USD,12283000000,NaN
1994,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2017-07-01T00:00:00/2017-10-01T00:00:00,NaN,iso4217:USD,1600000000,msft:ShareRepurchaseProgramTwentySixteenMember
1995,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,NaN,iso4217:USD,1800000000,msft:ShareRepurchaseProgramTwentySixteenMember
1996,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2018-01-01T00:00:00/2018-04-01T00:00:00,NaN,iso4217:USD,3100000000,msft:ShareRepurchaseProgramTwentySixteenMember
1997,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,NaN,iso4217:USD,2100000000,msft:ShareRepurchaseProgramTwentySixteenMember
1998,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,iso4217:USD,8600000000,NaN
2003,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2016-07-02T00:00:00/2016-10-01T00:00:00,NaN,iso4217:USD,3550000000,msft:ShareRepurchaseProgramTwentyThirteenMember
2004,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2016-10-01T00:00:00/2017-01-01T00:00:00,NaN,iso4217:USD,3533000000,msft:ShareRepurchaseProgramTwentyThirteenMember
2005,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2017-01-01T00:00:00/2017-04-01T00:00:00,NaN,iso4217:USD,1600000000,msft:ShareRepurchaseProgramTwentySixteenMember
2006,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,NaN,iso4217:USD,1600000000,msft:ShareRepurchaseProgramTwentySixteenMember
2007,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,NaN,iso4217:USD,10283000000,NaN
2012,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2015-07-01T00:00:00/2015-10-01T00:00:00,NaN,iso4217:USD,4000000000,msft:ShareRepurchaseProgramTwentyThirteenMember
2013,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2015-10-01T00:00:00/2016-01-01T00:00:00,NaN,iso4217:USD,3600000000,msft:ShareRepurchaseProgramTwentyThirteenMember
2014,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2016-01-01T00:00:00/2016-04-01T00:00:00,NaN,iso4217:USD,3600000000,msft:ShareRepurchaseProgramTwentyThirteenMember
2015,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2016-04-01T00:00:00/2016-07-01T00:00:00,NaN,iso4217:USD,3600000000,msft:ShareRepurchaseProgramTwentyThirteenMember
2016,us-gaap:StockRepurchasedDuringPeriodValue,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,NaN,iso4217:USD,14800000000,NaN

,concept,entity,period,us-gaap:StatementEquityComponentsAxis,unit,value
280,us-gaap:AdjustmentsToAdditionalPaidInCapitalSh...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:CommonStockIncludingAdditionalPaidInCa...,iso4217:USD,3940000000
281,us-gaap:AdjustmentsToAdditionalPaidInCapitalSh...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:CommonStockIncludingAdditionalPaidInCa...,iso4217:USD,3266000000
282,us-gaap:AdjustmentsToAdditionalPaidInCapitalSh...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:CommonStockIncludingAdditionalPaidInCa...,iso4217:USD,2668000000

,concept,entity,period,us-gaap:StatementEquityComponentsAxis,unit,value
283,us-gaap:StockholdersEquityOther,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:CommonStockIncludingAdditionalPaidInCa...,iso4217:USD,1000000
284,us-gaap:StockholdersEquityOther,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:CommonStockIncludingAdditionalPaidInCa...,iso4217:USD,-86000000
285,us-gaap:StockholdersEquityOther,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:CommonStockIncludingAdditionalPaidInCa...,iso4217:USD,-66000000

,concept,entity,period,us-gaap:StatementEquityComponentsAxis,unit,value
293,us-gaap:DividendsCommonStockCash,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:RetainedEarningsMember,iso4217:USD,12917000000
294,us-gaap:DividendsCommonStockCash,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:RetainedEarningsMember,iso4217:USD,12040000000
295,us-gaap:DividendsCommonStockCash,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:RetainedEarningsMember,iso4217:USD,11329000000
2041,us-gaap:DividendsCommonStockCash,cik:0000789019,2017-07-01T00:00:00/2017-10-01T00:00:00,NaN,iso4217:USD,3238000000
2042,us-gaap:DividendsCommonStockCash,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,NaN,iso4217:USD,3232000000
2043,us-gaap:DividendsCommonStockCash,cik:0000789019,2018-01-01T00:00:00/2018-04-01T00:00:00,NaN,iso4217:USD,3226000000
2044,us-gaap:DividendsCommonStockCash,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,NaN,iso4217:USD,3224000000
2045,us-gaap:DividendsCommonStockCash,cik:0000789019,2016-07-02T00:00:00/2016-10-01T00:00:00,NaN,iso4217:USD,3024000000
2046,us-gaap:DividendsCommonStockCash,cik:0000789019,2016-10-01T00:00:00/2017-01-01T00:00:00,NaN,iso4217:USD,3012000000
2047,us-gaap:DividendsCommonStockCash,cik:0000789019,2017-01-01T00:00:00/2017-04-01T00:00:00,NaN,iso4217:USD,3009000000
2048,us-gaap:DividendsCommonStockCash,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,NaN,iso4217:USD,3003000000

,concept,entity,period,us-gaap:StatementEquityComponentsAxis,unit,value,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis
299,msft:TaxCutsAndJobsActReclassificationFromAOCI...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:RetainedEarningsMember,iso4217:USD,-42000000,NaN
300,msft:TaxCutsAndJobsActReclassificationFromAOCI...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:RetainedEarningsMember,iso4217:USD,0,NaN
301,msft:TaxCutsAndJobsActReclassificationFromAOCI...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:RetainedEarningsMember,iso4217:USD,0,NaN
309,msft:TaxCutsAndJobsActReclassificationFromAOCI...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:AccumulatedOtherComprehensiveIncomeMember,iso4217:USD,42000000,NaN
310,msft:TaxCutsAndJobsActReclassificationFromAOCI...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:AccumulatedOtherComprehensiveIncomeMember,iso4217:USD,0,NaN
311,msft:TaxCutsAndJobsActReclassificationFromAOCI...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:AccumulatedOtherComprehensiveIncomeMember,iso4217:USD,0,NaN
447,msft:TaxCutsAndJobsActReclassificationFromAOCI...,cik:0000789019,2018-04-01T00:00:00/2018-04-02T00:00:00,NaN,iso4217:USD,42000000,msft:AccountingStandardsUpdate201802Member

,concept,entity,period,value
314,us-gaap:SignificantAccountingPoliciesTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
315,us-gaap:EarningsPerShareTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
316,us-gaap:OtherNonoperatingIncomeAndExpenseTextB...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
317,us-gaap:InvestmentsInDebtAndEquityInstrumentsC...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
318,us-gaap:DerivativeInstrumentsAndHedgingActivit...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
319,us-gaap:FairValueDisclosuresTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
320,us-gaap:InventoryDisclosureTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
321,us-gaap:PropertyPlantAndEquipmentDisclosureTex...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
322,us-gaap:MergersAcquisitionsAndDispositionsDisc...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
323,us-gaap:GoodwillDisclosureTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
324,us-gaap:IntangibleAssetsDisclosureTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
325,us-gaap:DebtDisclosureTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
326,us-gaap:IncomeTaxDisclosureTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
327,us-gaap:RestructuringAndRelatedActivitiesDiscl...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
328,us-gaap:RevenueFromContractWithCustomerTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
329,us-gaap:LeasesOfLesseeDisclosureTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
330,us-gaap:LegalMattersAndContingenciesTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
331,us-gaap:StockholdersEquityNoteDisclosureTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
332,us-gaap:ComprehensiveIncomeNoteTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
333,us-gaap:CompensationAndEmployeeBenefitPlansTex...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
334,us-gaap:SegmentReportingDisclosureTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
335,us-gaap:QuarterlyFinancialInformationTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ce"

,concept,entity,period,value
336,us-gaap:BasisOfAccountingPolicyPolicyTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
337,us-gaap:ConsolidationPolicyTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
338,us-gaap:UseOfEstimates,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
339,us-gaap:ForeignCurrencyTransactionsAndTranslat...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
340,us-gaap:RevenueFromContractWithCustomerPolicyT...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
341,us-gaap:CostOfSalesPolicyTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
342,us-gaap:StandardProductWarrantyPolicy,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
343,us-gaap:ResearchDevelopmentAndComputerSoftware...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
344,msft:SellingAndMarketingPolicyTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
345,us-gaap:ShareBasedCompensationOptionAndIncenti...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
346,us-gaap:IncomeTaxPolicyTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-top:13"

,concept,entity,period,value
347,us-gaap:FairValueOfFinancialInstrumentsPolicy,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
348,us-gaap:InvestmentPolicyTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
349,us-gaap:DerivativesPolicyTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
350,us-gaap:InventoryPolicyTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
351,us-gaap:PropertyPlantAndEquipmentPolicyTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
352,us-gaap:LesseeLeasesPolicyTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
353,us-gaap:GoodwillAndIntangibleAssetsGoodwillPolicy,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
354,us-gaap:IntangibleAssetsFiniteLivedPolicy,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
355,us-gaap:NewAccountingPronouncementsPolicyPolic...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
356,us-gaap:EarningsPerSharePolicyTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
357,us-gaap:SegmentReportingPolicyPolicyTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
358,us-gaap:ScheduleOfCreditLossesRelatedToFinanci...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
359,us-gaap:ScheduleOfErrorCorrectionsAndPriorPeri...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
360,us-gaap:ScheduleOfNewAccountingPronouncementsA...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ju"

,concept,entity,period,value
361,us-gaap:ScheduleOfEarningsPerShareBasicAndDilu...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
362,us-gaap:ScheduleOfOtherNonoperatingIncomeExpen...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
363,us-gaap:RealizedGainLossOnInvestmentsTableText...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
364,msft:ScheduleOfCashCashEquivalentsAndInvestmen...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
365,us-gaap:ScheduleOfUnrealizedLossOnInvestmentsT...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
366,us-gaap:InvestmentsClassifiedByContractualMatu...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
367,us-gaap:ScheduleOfDerivativeInstrumentsInState...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,us-gaap:DerivativeInstrumentsGainLossByHedgingRelationshipAxis,value,us-gaap:HedgingDesignationAxis
368,us-gaap:ScheduleOfDerivativeInstrumentsGainLos...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:FairValueHedgingMember,"<div>\n\n<p style=""margin-bottom",NaN
369,us-gaap:ScheduleOfDerivativeInstrumentsGainLos...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:CashFlowHedgingMember,"<div>\n\n<p style=""margin-bottom",NaN
370,us-gaap:ScheduleOfDerivativeInstrumentsGainLos...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,"<div>\n\n<p style=""margin-bottom",us-gaap:NondesignatedMember

,concept,entity,period,value
371,us-gaap:ScheduleOfFairValueAssetsAndLiabilitie...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
372,msft:ReconciliationOfAssetsMeasuredAtFairValue...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
373,us-gaap:ScheduleOfInventoryCurrentTableTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
374,us-gaap:PropertyPlantAndEquipmentTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,value
375,us-gaap:ScheduleOfBusinessAcquisitionsByAcquis...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:LinkedInCorporationMember,"<div>\n\n<p style=""text-align:ju"

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,value
376,us-gaap:ScheduleOfAcquiredFiniteLivedIntangibl...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:LinkedInCorporationMember,"<div>\n\n<p style=""text-align:ju"
381,us-gaap:ScheduleOfAcquiredFiniteLivedIntangibl...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,value
377,msft:RevenueAndOperatingLossAttributableToAcqu...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:LinkedInCorporationMember,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,value
378,us-gaap:BusinessAcquisitionProFormaInformation...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:LinkedInCorporationMember,"<div>\n\n<p style=""text-align:ju"

,concept,entity,period,value
379,us-gaap:ScheduleOfGoodwillTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
380,us-gaap:ScheduleOfFiniteLivedIntangibleAssetsT...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
382,us-gaap:ScheduleofFiniteLivedIntangibleAssetsF...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
383,us-gaap:ScheduleOfDebtInstrumentsTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
384,us-gaap:ScheduleOfMaturitiesOfLongTermDebtTabl...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
385,us-gaap:ScheduleOfComponentsOfIncomeTaxExpense...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
386,us-gaap:ScheduleOfIncomeBeforeIncomeTaxDomesti...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
387,us-gaap:ScheduleOfEffectiveIncomeTaxRateReconc...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
388,us-gaap:ScheduleOfDeferredTaxAssetsAndLiabilit...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
389,us-gaap:SummaryOfIncomeTaxContingenciesTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
390,msft:ContractWithCustomerLiabilityBySegmentTab...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ju"

,concept,entity,period,value
391,us-gaap:ContractWithCustomerAssetAndLiabilityT...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
392,us-gaap:LeaseCostTableTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
393,msft:ScheduleOfSupplementalCashFlowInformation...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""text-align:ju"

,concept,entity,period,value
394,msft:ScheduleOfSupplementalBalanceSheetInforma...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
395,msft:ScheduleOfMaturitiesOfOperatingAndFinance...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
396,us-gaap:ScheduleOfCommonStockOutstandingRollFo...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
397,msft:ShareRepurchaseProgramDisclosureTableText...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
398,us-gaap:DividendsDeclaredTableTextBlock,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
399,us-gaap:ScheduleOfAccumulatedOtherComprehensiv...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
400,us-gaap:ScheduleOfCompensationCostForShareBase...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
401,msft:ShareBasedCompensationArrangementByShareB...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
402,us-gaap:DisclosureOfShareBasedCompensationArra...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
403,us-gaap:ScheduleOfShareBasedCompensationEmploy...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
404,us-gaap:ReconciliationOfRevenueFromSegmentsToC...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
405,us-gaap:ReconciliationOfOperatingProfitLossFro...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
406,us-gaap:ScheduleOfRevenueFromExternalCustomers...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
407,us-gaap:ScheduleOfEntityWideInformationRevenue...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
408,us-gaap:ScheduleOfEntityWideDisclosureOnGeogra...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,value
409,us-gaap:ScheduleOfQuarterlyFinancialInformatio...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"<div>\n\n<p style=""margin-bottom"

,concept,entity,period,unit,value
410,us-gaap:AccountsReceivableNet,cik:0000789019,2016-07-02T00:00:00,iso4217:USD,22300000000

,concept,entity,period,unit,value
411,us-gaap:AccountsReceivableNetNoncurrent,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1800000000
412,us-gaap:AccountsReceivableNetNoncurrent,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,1700000000

,concept,entity,period,us-gaap:ValuationAllowancesAndReservesTypeAxis,unit,value,us-gaap:BalanceSheetLocationAxis
413,us-gaap:ValuationAllowancesAndReservesBalance,cik:0000789019,2017-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,361000000,NaN
414,us-gaap:ValuationAllowancesAndReservesBalance,cik:0000789019,2016-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,409000000,NaN
415,us-gaap:ValuationAllowancesAndReservesBalance,cik:0000789019,2015-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,289000000,NaN
422,us-gaap:ValuationAllowancesAndReservesBalance,cik:0000789019,2018-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,397000000,NaN
423,us-gaap:ValuationAllowancesAndReservesBalance,cik:0000789019,2018-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,377000000,msft:AccountsReceivableNetMember
424,us-gaap:ValuationAllowancesAndReservesBalance,cik:0000789019,2017-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,345000000,msft:AccountsReceivableNetMember
425,us-gaap:ValuationAllowancesAndReservesBalance,cik:0000789019,2016-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,392000000,msft:AccountsReceivableNetMember
426,us-gaap:ValuationAllowancesAndReservesBalance,cik:0000789019,2018-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,20000000,us-gaap:OtherNoncurrentAssetsMember
427,us-gaap:ValuationAllowancesAndReservesBalance,cik:0000789019,2017-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,16000000,us-gaap:OtherNoncurrentAssetsMember
428,us-gaap:ValuationAllowancesAndReservesBalance,cik:0000789019,2016-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,17000000,us-gaap:OtherNoncurrentAssetsMember

,concept,entity,period,us-gaap:ValuationAllowancesAndReservesTypeAxis,unit,value
416,msft:ValuationAllowancesAndReservesChargedToCo...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,134000000
417,msft:ValuationAllowancesAndReservesChargedToCo...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,58000000
418,msft:ValuationAllowancesAndReservesChargedToCo...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,175000000

,concept,entity,period,us-gaap:ValuationAllowancesAndReservesTypeAxis,unit,value
419,us-gaap:ValuationAllowancesAndReservesDeductions,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,98000000
420,us-gaap:ValuationAllowancesAndReservesDeductions,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,106000000
421,us-gaap:ValuationAllowancesAndReservesDeductions,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:AllowanceForCreditLossMember,iso4217:USD,55000000

,concept,entity,period,value
429,us-gaap:RevenuePerformanceObligationDescriptio...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,Payment terms and conditions v

,concept,entity,period,unit,value
430,us-gaap:AdvertisingExpense,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,1600000000
431,us-gaap:AdvertisingExpense,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1500000000
432,us-gaap:AdvertisingExpense,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,1600000000

,concept,entity,period,srt:RangeAxis,us-gaap:PropertyPlantAndEquipmentByTypeAxis,value
433,us-gaap:PropertyPlantAndEquipmentUsefulLife,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MinimumMember,us-gaap:SoftwareAndSoftwareDevelopmentCostsMember,P3Y
434,us-gaap:PropertyPlantAndEquipmentUsefulLife,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MaximumMember,us-gaap:SoftwareAndSoftwareDevelopmentCostsMember,P7Y
435,us-gaap:PropertyPlantAndEquipmentUsefulLife,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MinimumMember,us-gaap:ComputerEquipmentMember,P2Y
436,us-gaap:PropertyPlantAndEquipmentUsefulLife,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MaximumMember,us-gaap:ComputerEquipmentMember,P3Y
437,us-gaap:PropertyPlantAndEquipmentUsefulLife,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MinimumMember,us-gaap:BuildingAndBuildingImprovementsMember,P5Y
438,us-gaap:PropertyPlantAndEquipmentUsefulLife,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MaximumMember,us-gaap:BuildingAndBuildingImprovementsMember,P15Y
439,us-gaap:PropertyPlantAndEquipmentUsefulLife,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MinimumMember,us-gaap:LeaseholdImprovementsMember,P3Y
440,us-gaap:PropertyPlantAndEquipmentUsefulLife,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MaximumMember,us-gaap:LeaseholdImprovementsMember,P20Y
441,us-gaap:PropertyPlantAndEquipmentUsefulLife,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MinimumMember,us-gaap:FurnitureAndFixturesMember,P1Y
442,us-gaap:PropertyPlantAndEquipmentUsefulLife,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MaximumMember,us-gaap:FurnitureAndFixturesMember,P10Y

,concept,entity,period,srt:RangeAxis,value
443,us-gaap:FiniteLivedIntangibleAssetUsefulLife,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MinimumMember,P1Y
444,us-gaap:FiniteLivedIntangibleAssetUsefulLife,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MaximumMember,P20Y

,concept,entity,period,srt:RestatementAxis,unit,value,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis
470,us-gaap:OtherAssets,cik:0000789019,2017-07-01T00:00:00,srt:ScenarioPreviouslyReportedMember,iso4217:USD,11147000000,NaN
471,us-gaap:OtherAssets,cik:0000789019,2017-07-01T00:00:00,srt:RestatementAdjustmentMember,iso4217:USD,32000000,us-gaap:AccountingStandardsUpdate201409Member
472,us-gaap:OtherAssets,cik:0000789019,2017-07-01T00:00:00,srt:RestatementAdjustmentMember,iso4217:USD,0,us-gaap:AccountingStandardsUpdate201602Member
473,us-gaap:OtherAssets,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,11179000000,NaN

,concept,entity,period,srt:RestatementAxis,unit,value,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis,us-gaap:StatementBusinessSegmentsAxis
474,us-gaap:ContractWithCustomerLiability,cik:0000789019,2017-07-01T00:00:00,srt:ScenarioPreviouslyReportedMember,iso4217:USD,44479000000,NaN,NaN
475,us-gaap:ContractWithCustomerLiability,cik:0000789019,2017-07-01T00:00:00,srt:RestatementAdjustmentMember,iso4217:USD,-17823000000,us-gaap:AccountingStandardsUpdate201409Member,NaN
476,us-gaap:ContractWithCustomerLiability,cik:0000789019,2017-07-01T00:00:00,srt:RestatementAdjustmentMember,iso4217:USD,0,us-gaap:AccountingStandardsUpdate201602Member,NaN
477,us-gaap:ContractWithCustomerLiability,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,26656000000,NaN,NaN
1884,us-gaap:ContractWithCustomerLiability,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,14864000000,NaN,msft:ProductivityAndBusinessProcessesMember
1885,us-gaap:ContractWithCustomerLiability,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,12692000000,NaN,msft:ProductivityAndBusinessProcessesMember
1886,us-gaap:ContractWithCustomerLiability,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,14706000000,NaN,msft:IntelligentCloudMember
1887,us-gaap:ContractWithCustomerLiability,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,11152000000,NaN,msft:IntelligentCloudMember
1888,us-gaap:ContractWithCustomerLiability,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,3150000000,NaN,msft:MorePersonalComputingMember
1889,us-gaap:ContractWithCustomerLiability,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,2812000000,NaN,msft:MorePersonalComputingMember
1890,us-gaap:ContractWithCustomerLiability,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,32720000000,NaN,NaN
1891,us-gaap:ContractWithCustomerLiability,cik:0000789019,2016-07-02T00:00:00,NaN,iso4217:USD,22200000000,NaN,NaN

,concept,entity,period,srt:RestatementAxis,unit,value,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis
484,us-gaap:OtherLiabilities,cik:0000789019,2017-07-01T00:00:00,srt:ScenarioPreviouslyReportedMember,iso4217:USD,23464000000,NaN
485,us-gaap:OtherLiabilities,cik:0000789019,2017-07-01T00:00:00,srt:RestatementAdjustmentMember,iso4217:USD,-26000000,us-gaap:AccountingStandardsUpdate201409Member
486,us-gaap:OtherLiabilities,cik:0000789019,2017-07-01T00:00:00,srt:RestatementAdjustmentMember,iso4217:USD,1183000000,us-gaap:AccountingStandardsUpdate201602Member
487,us-gaap:OtherLiabilities,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,24621000000,NaN

,concept,entity,period,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis,us-gaap:StatementScenarioAxis,unit,value
492,us-gaap:DeferredTaxAssetsNetNoncurrent,cik:0000789019,2018-07-02T00:00:00,us-gaap:AccountingStandardsUpdate201616Member,us-gaap:ScenarioPlanMember,iso4217:USD,2800000000

,concept,entity,period,unit,value
495,us-gaap:IncrementalCommonSharesAttributableToS...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,xbrli:shares,94000000
496,us-gaap:IncrementalCommonSharesAttributableToS...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,xbrli:shares,86000000
497,us-gaap:IncrementalCommonSharesAttributableToS...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,xbrli:shares,88000000

,concept,entity,period,unit,value
498,us-gaap:InvestmentIncomeNet,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,2214000000
499,us-gaap:InvestmentIncomeNet,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1387000000
500,us-gaap:InvestmentIncomeNet,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,903000000

,concept,entity,period,unit,value
501,us-gaap:InterestExpense,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,2733000000
502,us-gaap:InterestExpense,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,2222000000
503,us-gaap:InterestExpense,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,1243000000

,concept,entity,period,unit,value
504,us-gaap:GainLossOnInvestments,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,2399000000
505,us-gaap:GainLossOnInvestments,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,2583000000
506,us-gaap:GainLossOnInvestments,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,668000000

,concept,entity,period,unit,value
507,us-gaap:GainLossOnDerivativeInstrumentsNetPretax,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-187000000
508,us-gaap:GainLossOnDerivativeInstrumentsNetPretax,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-510000000
509,us-gaap:GainLossOnDerivativeInstrumentsNetPretax,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-443000000

,concept,entity,period,unit,value
510,us-gaap:ForeignCurrencyTransactionGainLossBefo...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-218000000
511,us-gaap:ForeignCurrencyTransactionGainLossBefo...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-111000000
512,us-gaap:ForeignCurrencyTransactionGainLossBefo...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-129000000

,concept,entity,period,unit,value
513,us-gaap:OtherNonoperatingIncomeExpense,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-59000000
514,us-gaap:OtherNonoperatingIncomeExpense,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-251000000
515,us-gaap:OtherNonoperatingIncomeExpense,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,-195000000

,concept,entity,period,unit,value
516,us-gaap:ImpairmentOfInvestments,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,47000000
517,us-gaap:ImpairmentOfInvestments,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,55000000
518,us-gaap:ImpairmentOfInvestments,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,322000000

,concept,entity,period,unit,value
519,us-gaap:AvailableForSaleSecuritiesGrossRealize...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,3478000000
520,us-gaap:AvailableForSaleSecuritiesGrossRealize...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,3064000000
521,us-gaap:AvailableForSaleSecuritiesGrossRealize...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,1376000000

,concept,entity,period,unit,value
522,us-gaap:AvailableForSaleSecuritiesGrossRealize...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,1032000000
523,us-gaap:AvailableForSaleSecuritiesGrossRealize...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,426000000
524,us-gaap:AvailableForSaleSecuritiesGrossRealize...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,386000000

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value,us-gaap:FairValueByMeasurementFrequencyAxis
525,us-gaap:Cash,cik:0000789019,2018-07-01T00:00:00,us-gaap:CashMember,iso4217:USD,3942000000,NaN
605,us-gaap:Cash,cik:0000789019,2017-07-01T00:00:00,us-gaap:CashMember,iso4217:USD,3624000000,NaN
1183,us-gaap:Cash,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,3942000000,us-gaap:FairValueMeasurementsRecurringMember
1184,us-gaap:Cash,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,3624000000,us-gaap:FairValueMeasurementsRecurringMember

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value
526,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CashMember,iso4217:USD,0
541,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:MoneyMarketFundsMember,iso4217:USD,0
542,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CommercialPaperMember,iso4217:USD,0
543,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CertificatesOfDepositMember,iso4217:USD,0
544,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,62000000
545,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,1000000
546,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,4000000
547,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,21000000
548,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,37000000
549,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,95000000
550,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,220000000
599,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,msft:OtherSecurityInvestmentsMember,iso4217:USD,0
606,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CashMember,iso4217:USD,0
621,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:MoneyMarketFundsMember,iso4217:USD,0
622,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CommercialPaperMember,iso4217:USD,0
623,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CertificatesOfDepositMember,iso4217:USD,0
624,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,85000000
625,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,2000000
626,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,14000000
627,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,61000000
628,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,43000000
629,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,3062000000
630,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,3267000000
679,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,msft:OtherSecurityInvestmentsMember,iso4217:USD,0

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value
527,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CashMember,iso4217:USD,0
551,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:MoneyMarketFundsMember,iso4217:USD,0
552,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CommercialPaperMember,iso4217:USD,0
553,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CertificatesOfDepositMember,iso4217:USD,0
554,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,1167000000
555,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,10000000
556,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,13000000
557,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,56000000
558,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,1000000
559,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,10000000
560,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,1257000000
600,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2018-07-01T00:00:00,msft:OtherSecurityInvestmentsMember,iso4217:USD,0
607,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CashMember,iso4217:USD,0
631,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:MoneyMarketFundsMember,iso4217:USD,0
632,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CommercialPaperMember,iso4217:USD,0
633,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CertificatesOfDepositMember,iso4217:USD,0
634,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,360000000
635,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,13000000
636,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,4000000
637,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,12000000
638,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,0
639,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,34000000
640,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,423000000
680,us-gaap:AvailableForSaleSecuritiesAccumulatedG...,cik:0000789019,2017-07-01T00:00:00,msft:OtherSecurityInvestmentsMember,iso4217:USD,0

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value
531,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2018-07-01T00:00:00,us-gaap:MoneyMarketFundsMember,iso4217:USD,246000000
532,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2018-07-01T00:00:00,us-gaap:CommercialPaperMember,iso4217:USD,2513000000
533,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2018-07-01T00:00:00,us-gaap:CertificatesOfDepositMember,iso4217:USD,2058000000
534,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2018-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,109862000000
535,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,5182000000
536,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2018-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,3868000000
537,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2018-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,6947000000
538,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2018-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,271000000
539,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2018-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,1220000000
540,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,136667000000
611,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2017-07-01T00:00:00,us-gaap:MoneyMarketFundsMember,iso4217:USD,1478000000
612,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2017-07-01T00:00:00,us-gaap:CommercialPaperMember,iso4217:USD,319000000
613,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2017-07-01T00:00:00,us-gaap:CertificatesOfDepositMember,iso4217:USD,1358000000
614,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2017-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,112119000000
615,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,5276000000
616,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2017-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,3921000000
617,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2017-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,4786000000
618,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2017-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,284000000
619,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,2472000000
620,us-gaap:AvailableForSaleSecuritiesAmortizedCost,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,136160000000

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value
561,us-gaap:AvailableForSaleSecurities,cik:0000789019,2018-07-01T00:00:00,us-gaap:MoneyMarketFundsMember,iso4217:USD,246000000
562,us-gaap:AvailableForSaleSecurities,cik:0000789019,2018-07-01T00:00:00,us-gaap:CommercialPaperMember,iso4217:USD,2513000000
563,us-gaap:AvailableForSaleSecurities,cik:0000789019,2018-07-01T00:00:00,us-gaap:CertificatesOfDepositMember,iso4217:USD,2058000000
564,us-gaap:AvailableForSaleSecurities,cik:0000789019,2018-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,108757000000
565,us-gaap:AvailableForSaleSecurities,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,5173000000
566,us-gaap:AvailableForSaleSecurities,cik:0000789019,2018-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,3859000000
567,us-gaap:AvailableForSaleSecurities,cik:0000789019,2018-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,6912000000
568,us-gaap:AvailableForSaleSecurities,cik:0000789019,2018-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,307000000
569,us-gaap:AvailableForSaleSecurities,cik:0000789019,2018-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,1305000000
570,us-gaap:AvailableForSaleSecurities,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,135630000000
641,us-gaap:AvailableForSaleSecurities,cik:0000789019,2017-07-01T00:00:00,us-gaap:MoneyMarketFundsMember,iso4217:USD,1478000000
642,us-gaap:AvailableForSaleSecurities,cik:0000789019,2017-07-01T00:00:00,us-gaap:CommercialPaperMember,iso4217:USD,319000000
643,us-gaap:AvailableForSaleSecurities,cik:0000789019,2017-07-01T00:00:00,us-gaap:CertificatesOfDepositMember,iso4217:USD,1358000000
644,us-gaap:AvailableForSaleSecurities,cik:0000789019,2017-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,111844000000
645,us-gaap:AvailableForSaleSecurities,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,5265000000
646,us-gaap:AvailableForSaleSecurities,cik:0000789019,2017-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,3931000000
647,us-gaap:AvailableForSaleSecurities,cik:0000789019,2017-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,4835000000
648,us-gaap:AvailableForSaleSecurities,cik:0000789019,2017-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,327000000
649,us-gaap:AvailableForSaleSecurities,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,5500000000
650,us-gaap:AvailableForSaleSecurities,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,139004000000

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value
598,us-gaap:EquityMethodInvestmentAggregateCost,cik:0000789019,2018-07-01T00:00:00,msft:OtherSecurityInvestmentsMember,iso4217:USD,558000000
678,us-gaap:EquityMethodInvestmentAggregateCost,cik:0000789019,2017-07-01T00:00:00,msft:OtherSecurityInvestmentsMember,iso4217:USD,523000000

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value,us-gaap:FairValueByMeasurementFrequencyAxis
601,us-gaap:EquityMethodInvestments,cik:0000789019,2018-07-01T00:00:00,msft:OtherSecurityInvestmentsMember,iso4217:USD,558000000,NaN
681,us-gaap:EquityMethodInvestments,cik:0000789019,2017-07-01T00:00:00,msft:OtherSecurityInvestmentsMember,iso4217:USD,523000000,NaN
1185,us-gaap:EquityMethodInvestments,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,557000000,us-gaap:FairValueMeasurementsNonrecurringMember
1186,us-gaap:EquityMethodInvestments,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,523000000,us-gaap:FairValueMeasurementsNonrecurringMember

,concept,entity,period,us-gaap:FairValueByMeasurementFrequencyAxis,unit,value
685,us-gaap:CostMethodInvestments,cik:0000789019,2018-07-01T00:00:00,us-gaap:FairValueMeasurementsNonrecurringMember,iso4217:USD,999000000
686,us-gaap:CostMethodInvestments,cik:0000789019,2017-07-01T00:00:00,us-gaap:FairValueMeasurementsNonrecurringMember,iso4217:USD,1073000000

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value
687,us-gaap:SecuritiesReceivedAsCollateral,cik:0000789019,2018-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,1800000000
688,us-gaap:SecuritiesReceivedAsCollateral,cik:0000789019,2017-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,3700000000

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value
689,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,82352000000
690,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,3457000000
691,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,2072000000
692,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,3111000000
693,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,45000000
694,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,75000000
695,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,91112000000
731,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,87558000000
732,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,4006000000
733,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,1068000000
734,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,669000000
735,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,69000000
736,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,93370000000

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value
696,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,1064000000
697,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,7000000
698,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,9000000
699,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,43000000
700,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,1000000
701,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,6000000
702,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,1130000000
737,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,348000000
738,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,2000000
739,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,3000000
740,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,8000000
741,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,6000000
742,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,367000000

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value
703,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,4459000000
704,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,13000000
705,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,96000000
706,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,301000000
707,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,0
708,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,8000000
709,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,4877000000
743,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,371000000
744,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,23000000
745,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,198000000
746,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,177000000
747,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,148000000
748,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,917000000

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value
710,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,103000000
711,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,3000000
712,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,4000000
713,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,13000000
714,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,0
715,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,4000000
716,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,127000000
749,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,12000000
750,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,11000000
751,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,1000000
752,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,4000000
753,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,28000000
754,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,56000000

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value
717,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,86811000000
718,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,3470000000
719,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,2168000000
720,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,3412000000
721,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,45000000
722,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,83000000
723,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,95989000000
755,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,87929000000
756,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,4029000000
757,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,1266000000
758,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,846000000
759,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,217000000
760,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,94287000000

,concept,entity,period,us-gaap:InvestmentTypeAxis,unit,value
724,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,1167000000
725,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,10000000
726,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,13000000
727,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,56000000
728,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:USStatesAndPoliticalSubdivisionsMember,iso4217:USD,1000000
729,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,10000000
730,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,1257000000
761,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:USGovernmentAgenciesDebtSecuritiesMember,iso4217:USD,360000000
762,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignGovernmentDebtSecuritiesMember,iso4217:USD,13000000
763,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:AssetBackedSecuritiesMember,iso4217:USD,4000000
764,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CorporateDebtSecuritiesMember,iso4217:USD,12000000
765,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquitySecuritiesMember,iso4217:USD,34000000
766,us-gaap:AvailableForSaleSecuritiesContinuousUn...,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,423000000

,concept,entity,period,unit,value
767,us-gaap:AvailableForSaleSecuritiesDebtMaturiti...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,31590000000

,concept,entity,period,unit,value
768,us-gaap:AvailableForSaleSecuritiesDebtMaturiti...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,76422000000

,concept,entity,period,unit,value
769,us-gaap:AvailableForSaleSecuritiesDebtMaturiti...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,21765000000

,concept,entity,period,unit,value
770,us-gaap:AvailableForSaleSecuritiesDebtMaturiti...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,924000000

,concept,entity,period,unit,value
771,us-gaap:AvailableForSaleDebtSecuritiesAmortize...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,130701000000

,concept,entity,period,unit,value
772,us-gaap:AvailableForSaleSecuritiesDebtMaturiti...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,31451000000

,concept,entity,period,unit,value
773,us-gaap:AvailableForSaleSecuritiesDebtMaturiti...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,75810000000

,concept,entity,period,unit,value
774,us-gaap:AvailableForSaleSecuritiesDebtMaturiti...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,21396000000

,concept,entity,period,unit,value
775,us-gaap:AvailableForSaleSecuritiesDebtMaturiti...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,922000000

,concept,entity,period,unit,value
776,us-gaap:AvailableForSaleSecuritiesDebtSecurities,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,129579000000

,concept,entity,period,value
777,us-gaap:MaximumLengthOfTimeForeignCurrencyCash...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,P3Y

,concept,entity,period,us-gaap:DerivativeInstrumentRiskAxis,us-gaap:DerivativeInstrumentsGainLossByHedgingRelationshipAxis,us-gaap:PositionAxis,unit,value,us-gaap:HedgingDesignationAxis
778,invest:DerivativeNotionalAmount,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:CashFlowHedgingMember,us-gaap:ShortMember,iso4217:USD,6100000000,NaN
779,invest:DerivativeNotionalAmount,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:CashFlowHedgingMember,us-gaap:ShortMember,iso4217:USD,8900000000,NaN
780,invest:DerivativeNotionalAmount,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:FairValueHedgingMember,us-gaap:ShortMember,iso4217:USD,5000000000,NaN
781,invest:DerivativeNotionalAmount,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:FairValueHedgingMember,us-gaap:ShortMember,iso4217:USD,5100000000,NaN
782,invest:DerivativeNotionalAmount,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,NaN,us-gaap:LongMember,iso4217:USD,9400000000,us-gaap:NondesignatedMember
783,invest:DerivativeNotionalAmount,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,NaN,us-gaap:LongMember,iso4217:USD,8800000000,us-gaap:NondesignatedMember
784,invest:DerivativeNotionalAmount,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,NaN,us-gaap:ShortMember,iso4217:USD,13400000000,us-gaap:NondesignatedMember
785,invest:DerivativeNotionalAmount,cik:0000789019,2017-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,NaN,us-gaap:ShortMember,iso4217:USD,10600000000,us-gaap:NondesignatedMember
786,invest:DerivativeNotionalAmount,cik:0000789019,2018-07-01T00:00:00,us-gaap:EquityContractMember,NaN,us-gaap:LongMember,iso4217:USD,49000000,NaN
787,invest:DerivativeNotionalAmount,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquityContractMember,NaN,us-gaap:LongMember,iso4217:USD,1900000000,NaN
788,invest:DerivativeNotionalAmount,cik:0000789019,2018-07-01T00:00:00,us-gaap:EquityContractMember,NaN,us-gaap:ShortMember,iso4217:USD,5000000,NaN
789,invest:DerivativeNotionalAmount,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquityContractMember,NaN,us-gaap:ShortMember,iso4217:USD,2400000000,NaN
790,invest:DerivativeNotionalAmount,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquityContractMember,NaN,us-gaap:LongMember,iso4217:USD,1600000000,us-gaap:DesignatedAsHedgingInstrumentMember
791,invest:DerivativeNotionalAmount,cik:0000789019,2017-07-01T00:00:00,us-gaap:EquityContractMember,NaN,us-gaap:ShortMember,iso4217:USD,1800000000,us-gaap:DesignatedAsHedgingInstrumentMember
792,invest:DerivativeNotionalAmount,cik:0000789019,2018-07-01T00:00:00,us-gaap:InterestRateContractMember,NaN,us-gaap:LongMember,iso4217:USD,306000000,us-gaap:NondesignatedMember
793,invest:DerivativeNotionalAmount,cik:0000789019,2018-07-01T00:00:00,us-gaap:InterestRateContractMember,NaN,us-gaap:ShortMember,iso4217:USD,390000000,us-gaap:NondesignatedMember
794,invest:DerivativeNotionalAmount,cik:0000789019,2017-07-01T00:00:00,us-gaap:InterestRateContractMember,NaN,us-gaap:LongMember,iso4217:USD,233000000,us-gaap:NondesignatedMember
795,invest:DerivativeNotionalAmount,cik:0000789019,2017-07-01T00:00:00,us-gaap:InterestRateContractMember,NaN,us-gaap:ShortMember,iso4217:USD,352000000,us-gaap:NondesignatedMember
796,invest:DerivativeNotionalAmount,cik:0000789019,2018-07-01T00:00:00,us-gaap:MortgageBackedSecuritiesMember,NaN,us-gaap:LongMember,iso4217:USD,568000000,us-gaap:NondesignatedMember
797,invest:DerivativeNotionalAmount,cik:0000789019,2017-07-01T00:00:00,us-gaap:MortgageBackedSecuritiesMember,NaN,us-gaap:LongMember,iso4217:USD,567000000,us-gaap:NondesignatedMember
798,invest:DerivativeNotionalAmount,cik:0000789019,2018-07-01T00:00:00,us-gaap:CreditRiskContractMember,NaN,us-gaap:LongMember,iso4217:USD,4000000,us-gaap:NondesignatedMember
799,invest:DerivativeNotionalAmount,cik:0000789019,2018-07-01T00:00:00,us-gaap:CreditRiskContractMember,NaN,us-gaap:ShortMember,iso4217:USD,82000000,us-gaap:NondesignatedMember
800,invest:DerivativeNotionalAmount,cik:0000789019,2017-07-01T00:00:00,us-gaap:CreditRiskContractMember,NaN,us-gaap:LongMember,iso4217:USD,267000000,us-gaap:NondesignatedMember
801,invest:DerivativeNotionalAmount,cik:0000789019,2017-07-01T00:00:00,us-gaap:CreditRiskContractMember,NaN,us-gaap:ShortMember,iso4217:USD,63000000,us-gaap:NondesignatedMember

,concept,entity,period,unit,value
802,msft:FinancialInstrumentCovenantMinimumLiquidi...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,1000000000

,concept,entity,period,us-gaap:LongtermDebtTypeAxis,value
803,us-gaap:DebtInstrumentCreditRating,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:UnsecuredDebtMember,AAA

,concept,entity,period,unit,value
804,msft:FinancialInstrumentCovenantMinimumLiquidity,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1000000000

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,us-gaap:DerivativeInstrumentRiskAxis,us-gaap:HedgingDesignationAxis,unit,value,msft:BalanceSheetOffsettingEligibilityAxis
805,us-gaap:DerivativeFairValueOfDerivativeAsset,cik:0000789019,2018-07-01T00:00:00,us-gaap:ShortTermInvestmentsMember,us-gaap:ForeignExchangeContractMember,us-gaap:NondesignatedMember,iso4217:USD,10000000,NaN
806,us-gaap:DerivativeFairValueOfDerivativeAsset,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentAssetsMember,us-gaap:ForeignExchangeContractMember,us-gaap:NondesignatedMember,iso4217:USD,221000000,NaN
807,us-gaap:DerivativeFairValueOfDerivativeAsset,cik:0000789019,2018-07-01T00:00:00,msft:EquityAndOtherInvestmentsMember,us-gaap:ForeignExchangeContractMember,us-gaap:NondesignatedMember,iso4217:USD,0,NaN
808,us-gaap:DerivativeFairValueOfDerivativeAsset,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,us-gaap:ForeignExchangeContractMember,us-gaap:NondesignatedMember,iso4217:USD,25000000,NaN
809,us-gaap:DerivativeFairValueOfDerivativeAsset,cik:0000789019,2018-07-01T00:00:00,us-gaap:ShortTermInvestmentsMember,us-gaap:EquityContractMember,us-gaap:NondesignatedMember,iso4217:USD,2000000,NaN
...,...,...,...,...,...,...,...,...,...
930,us-gaap:DerivativeFairValueOfDerivativeAsset,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,NaN,NaN,iso4217:USD,6000000,NaN
931,us-gaap:DerivativeFairValueOfDerivativeAsset,cik:0000789019,2017-07-01T00:00:00,us-gaap:ShortTermInvestmentsMember,NaN,NaN,iso4217:USD,100000000,msft:EligibleForOffsettingMember
932,us-gaap:DerivativeFairValueOfDerivativeAsset,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentAssetsMember,NaN,NaN,iso4217:USD,336000000,msft:EligibleForOffsettingMember
933,us-gaap:DerivativeFairValueOfDerivativeAsset,cik:0000789019,2017-07-01T00:00:00,msft:EquityAndOtherInvestmentsMember,NaN,NaN,iso4217:USD,67000000,msft:EligibleForOffsettingMember
934,us-gaap:DerivativeFairValueOfDerivativeAsset,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,NaN,NaN,iso4217:USD,6000000,msft:EligibleForOffsettingMember

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,msft:BalanceSheetOffsettingEligibilityAxis,unit,value
845,us-gaap:DerivativeAssetFairValueGrossLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:ShortTermInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,14000000
846,us-gaap:DerivativeAssetFairValueGrossLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,135000000
847,us-gaap:DerivativeAssetFairValueGrossLiability,cik:0000789019,2018-07-01T00:00:00,msft:EquityAndOtherInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
848,us-gaap:DerivativeAssetFairValueGrossLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,3000000
935,us-gaap:DerivativeAssetFairValueGrossLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:ShortTermInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,20000000
936,us-gaap:DerivativeAssetFairValueGrossLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,132000000
937,us-gaap:DerivativeAssetFairValueGrossLiability,cik:0000789019,2017-07-01T00:00:00,msft:EquityAndOtherInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,67000000
938,us-gaap:DerivativeAssetFairValueGrossLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,8000000

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,msft:BalanceSheetOffsettingEligibilityAxis,unit,value
849,msft:DerivativeAssetsNetAmountsPresentedInBala...,cik:0000789019,2018-07-01T00:00:00,us-gaap:ShortTermInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,99000000
850,msft:DerivativeAssetsNetAmountsPresentedInBala...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,260000000
851,msft:DerivativeAssetsNetAmountsPresentedInBala...,cik:0000789019,2018-07-01T00:00:00,msft:EquityAndOtherInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
852,msft:DerivativeAssetsNetAmountsPresentedInBala...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,22000000
939,msft:DerivativeAssetsNetAmountsPresentedInBala...,cik:0000789019,2017-07-01T00:00:00,us-gaap:ShortTermInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,80000000
940,msft:DerivativeAssetsNetAmountsPresentedInBala...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,204000000
941,msft:DerivativeAssetsNetAmountsPresentedInBala...,cik:0000789019,2017-07-01T00:00:00,msft:EquityAndOtherInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
942,msft:DerivativeAssetsNetAmountsPresentedInBala...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,-2000000

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,msft:BalanceSheetOffsettingEligibilityAxis,unit,value
853,msft:DerivativeFairValueOfDerivativeAssetAmoun...,cik:0000789019,2018-07-01T00:00:00,us-gaap:ShortTermInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
854,msft:DerivativeFairValueOfDerivativeAssetAmoun...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
855,msft:DerivativeFairValueOfDerivativeAssetAmoun...,cik:0000789019,2018-07-01T00:00:00,msft:EquityAndOtherInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
856,msft:DerivativeFairValueOfDerivativeAssetAmoun...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
943,msft:DerivativeFairValueOfDerivativeAssetAmoun...,cik:0000789019,2017-07-01T00:00:00,us-gaap:ShortTermInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
944,msft:DerivativeFairValueOfDerivativeAssetAmoun...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
945,msft:DerivativeFairValueOfDerivativeAssetAmoun...,cik:0000789019,2017-07-01T00:00:00,msft:EquityAndOtherInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
946,msft:DerivativeFairValueOfDerivativeAssetAmoun...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,0

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,msft:BalanceSheetOffsettingEligibilityAxis,unit,value
857,us-gaap:DerivativeCollateralRightToReclaimCash,cik:0000789019,2018-07-01T00:00:00,us-gaap:ShortTermInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
858,us-gaap:DerivativeCollateralRightToReclaimCash,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
859,us-gaap:DerivativeCollateralRightToReclaimCash,cik:0000789019,2018-07-01T00:00:00,msft:EquityAndOtherInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
860,us-gaap:DerivativeCollateralRightToReclaimCash,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
947,us-gaap:DerivativeCollateralRightToReclaimCash,cik:0000789019,2017-07-01T00:00:00,us-gaap:ShortTermInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
948,us-gaap:DerivativeCollateralRightToReclaimCash,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
949,us-gaap:DerivativeCollateralRightToReclaimCash,cik:0000789019,2017-07-01T00:00:00,msft:EquityAndOtherInvestmentsMember,msft:EligibleForOffsettingMember,iso4217:USD,0
950,us-gaap:DerivativeCollateralRightToReclaimCash,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,msft:EligibleForOffsettingMember,iso4217:USD,0

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,unit,value
861,msft:DerivativeAssetsPotentialNetAmountsNotPre...,cik:0000789019,2018-07-01T00:00:00,us-gaap:ShortTermInvestmentsMember,iso4217:USD,99000000
862,msft:DerivativeAssetsPotentialNetAmountsNotPre...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentAssetsMember,iso4217:USD,260000000
863,msft:DerivativeAssetsPotentialNetAmountsNotPre...,cik:0000789019,2018-07-01T00:00:00,msft:EquityAndOtherInvestmentsMember,iso4217:USD,0
864,msft:DerivativeAssetsPotentialNetAmountsNotPre...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,iso4217:USD,22000000
951,msft:DerivativeAssetsPotentialNetAmountsNotPre...,cik:0000789019,2017-07-01T00:00:00,us-gaap:ShortTermInvestmentsMember,iso4217:USD,80000000
952,msft:DerivativeAssetsPotentialNetAmountsNotPre...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentAssetsMember,iso4217:USD,204000000
953,msft:DerivativeAssetsPotentialNetAmountsNotPre...,cik:0000789019,2017-07-01T00:00:00,msft:EquityAndOtherInvestmentsMember,iso4217:USD,0
954,msft:DerivativeAssetsPotentialNetAmountsNotPre...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,iso4217:USD,-2000000

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,us-gaap:DerivativeInstrumentRiskAxis,us-gaap:HedgingDesignationAxis,unit,value,msft:BalanceSheetOffsettingEligibilityAxis
865,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,us-gaap:ForeignExchangeContractMember,us-gaap:NondesignatedMember,iso4217:USD,193000000,NaN
866,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,us-gaap:ForeignExchangeContractMember,us-gaap:NondesignatedMember,iso4217:USD,4000000,NaN
867,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,us-gaap:EquityContractMember,us-gaap:NondesignatedMember,iso4217:USD,7000000,NaN
868,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,us-gaap:EquityContractMember,us-gaap:NondesignatedMember,iso4217:USD,0,NaN
869,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,us-gaap:InterestRateContractMember,us-gaap:NondesignatedMember,iso4217:USD,2000000,NaN
870,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,us-gaap:InterestRateContractMember,us-gaap:NondesignatedMember,iso4217:USD,0,NaN
871,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,us-gaap:CreditRiskContractMember,us-gaap:NondesignatedMember,iso4217:USD,1000000,NaN
872,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,us-gaap:CreditRiskContractMember,us-gaap:NondesignatedMember,iso4217:USD,0,NaN
873,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,NaN,us-gaap:NondesignatedMember,iso4217:USD,203000000,NaN
874,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,NaN,us-gaap:NondesignatedMember,iso4217:USD,4000000,NaN
875,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,0,NaN
876,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,0,NaN
877,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,us-gaap:EquityContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,0,NaN
878,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,us-gaap:EquityContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,0,NaN
879,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,NaN,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,0,NaN
880,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,NaN,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,0,NaN
881,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,NaN,NaN,iso4217:USD,203000000,NaN
882,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,NaN,NaN,iso4217:USD,4000000,NaN
883,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,NaN,NaN,iso4217:USD,203000000,msft:EligibleForOffsettingMember
884,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,NaN,NaN,iso4217:USD,4000000,msft:EligibleForOffsettingMember
955,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,us-gaap:ForeignExchangeContractMember,us-gaap:NondesignatedMember,iso4217:USD,134000000,NaN
956,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,us-gaap:ForeignExchangeContractMember,us-gaap:NondesignatedMember,iso4217:USD,8000000,NaN
957,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,us-gaap:EquityContractMember,us-gaap:NondesignatedMember,iso4217:USD,6000000,NaN
958,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,us-gaap:EquityContractMember,us-gaap:NondesignatedMember,iso4217:USD,0,NaN
959,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,us-gaap:InterestRateContractMember,us-gaap:NondesignatedMember,iso4217:USD,7000000,NaN
960,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,us-gaap:InterestRateContractMember,us-gaap:NondesignatedMember,iso4217:USD,0,NaN
961,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,us-gaap:CreditRiskContractMember,us-gaap:NondesignatedMember,iso4217:USD,1000000,NaN
962,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,us-gaap:CreditRiskContractMember,us-gaap:NondesignatedMember,iso4217:USD,0,NaN
963,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,NaN,us-gaap:NondesignatedMember,iso4217:USD,148000000,NaN
964,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,NaN,us-gaap:NondesignatedMember,iso4217:USD,8000000,NaN
965,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,3000000,NaN
966,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,0,NaN
967,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,us-gaap:EquityContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,186000000,NaN
968,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,us-gaap:EquityContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,0,NaN
969,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,NaN,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,189000000,NaN
970,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,NaN,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,0,NaN
971,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,NaN,NaN,iso4217:USD,337000000,NaN
972,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,NaN,NaN,iso4217:USD,8000000,NaN
973,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,NaN,NaN,iso4217:USD,334000000,msft:EligibleForOffsettingMember
974,us-gaap:DerivativeFairValueOfDerivativeLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,NaN,NaN,iso4217:USD,8000000,msft:EligibleForOffsettingMember

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,msft:BalanceSheetOffsettingEligibilityAxis,unit,value
885,us-gaap:DerivativeLiabilityFairValueGrossAsset,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,150000000
886,us-gaap:DerivativeLiabilityFairValueGrossAsset,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,3000000
975,us-gaap:DerivativeLiabilityFairValueGrossAsset,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,221000000
976,us-gaap:DerivativeLiabilityFairValueGrossAsset,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,7000000

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,msft:BalanceSheetOffsettingEligibilityAxis,unit,value
887,msft:DerivativeLiabilitiesNetAmountsPresentedI...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,53000000
888,msft:DerivativeLiabilitiesNetAmountsPresentedI...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,1000000
977,msft:DerivativeLiabilitiesNetAmountsPresentedI...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,113000000
978,msft:DerivativeLiabilitiesNetAmountsPresentedI...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,1000000

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,msft:BalanceSheetOffsettingEligibilityAxis,unit,value
889,msft:DerivativeFairValueOfDerivativeLiabilityA...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,0
890,msft:DerivativeFairValueOfDerivativeLiabilityA...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,0
979,msft:DerivativeFairValueOfDerivativeLiabilityA...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,0
980,msft:DerivativeFairValueOfDerivativeLiabilityA...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,0

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,msft:BalanceSheetOffsettingEligibilityAxis,unit,value
891,us-gaap:DerivativeCollateralObligationToReturn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,235000000
892,us-gaap:DerivativeCollateralObligationToReturn...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,0
981,us-gaap:DerivativeCollateralObligationToReturn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,228000000
982,us-gaap:DerivativeCollateralObligationToReturn...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,msft:EligibleForOffsettingMember,iso4217:USD,0

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,unit,value
893,msft:DerivativeLiabilitiesPotentialNetAmountsN...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,iso4217:USD,288000000
894,msft:DerivativeLiabilitiesPotentialNetAmountsN...,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,iso4217:USD,1000000
983,msft:DerivativeLiabilitiesPotentialNetAmountsN...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,iso4217:USD,341000000
984,msft:DerivativeLiabilitiesPotentialNetAmountsN...,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,iso4217:USD,1000000

,concept,entity,period,us-gaap:DerivativeInstrumentRiskAxis,unit,value
985,us-gaap:ChangeInUnrealizedGainLossOnFairValueH...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,iso4217:USD,25000000
986,us-gaap:ChangeInUnrealizedGainLossOnFairValueH...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,iso4217:USD,441000000
987,us-gaap:ChangeInUnrealizedGainLossOnFairValueH...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,iso4217:USD,-797000000
994,us-gaap:ChangeInUnrealizedGainLossOnFairValueH...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,-324000000
995,us-gaap:ChangeInUnrealizedGainLossOnFairValueH...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,-74000000
996,us-gaap:ChangeInUnrealizedGainLossOnFairValueH...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,-76000000

,concept,entity,period,us-gaap:DerivativeInstrumentRiskAxis,unit,value
988,us-gaap:ChangeInUnrealizedGainLossOnHedgedItem...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,iso4217:USD,78000000
989,us-gaap:ChangeInUnrealizedGainLossOnHedgedItem...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,iso4217:USD,-386000000
990,us-gaap:ChangeInUnrealizedGainLossOnHedgedItem...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,iso4217:USD,838000000
997,us-gaap:ChangeInUnrealizedGainLossOnHedgedItem...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,324000000
998,us-gaap:ChangeInUnrealizedGainLossOnHedgedItem...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,74000000
999,us-gaap:ChangeInUnrealizedGainLossOnHedgedItem...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,76000000

,concept,entity,period,us-gaap:DerivativeInstrumentRiskAxis,unit,value
991,us-gaap:GainLossOnFairValueHedgeIneffectivenes...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,iso4217:USD,103000000
992,us-gaap:GainLossOnFairValueHedgeIneffectivenes...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,iso4217:USD,55000000
993,us-gaap:GainLossOnFairValueHedgeIneffectivenes...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,iso4217:USD,41000000
1000,us-gaap:GainLossOnFairValueHedgeIneffectivenes...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,0
1001,us-gaap:GainLossOnFairValueHedgeIneffectivenes...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,0
1002,us-gaap:GainLossOnFairValueHedgeIneffectivenes...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,0

,concept,entity,period,us-gaap:DerivativeInstrumentRiskAxis,unit,value
1003,us-gaap:GainLossFromComponentsExcludedFromAsse...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,80000000
1004,us-gaap:GainLossFromComponentsExcludedFromAsse...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,-80000000
1005,us-gaap:GainLossFromComponentsExcludedFromAsse...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,-10000000

,concept,entity,period,us-gaap:DerivativeInstrumentRiskAxis,us-gaap:HedgingDesignationAxis,unit,value
1006,us-gaap:OtherComprehensiveIncomeUnrealizedGain...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,219000000
1007,us-gaap:OtherComprehensiveIncomeUnrealizedGain...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,328000000
1008,us-gaap:OtherComprehensiveIncomeUnrealizedGain...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,351000000

,concept,entity,period,us-gaap:DerivativeInstrumentRiskAxis,us-gaap:HedgingDesignationAxis,unit,value
1009,us-gaap:ForeignCurrencyCashFlowHedgeGainLossRe...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,185000000
1010,us-gaap:ForeignCurrencyCashFlowHedgeGainLossRe...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,555000000
1011,us-gaap:ForeignCurrencyCashFlowHedgeGainLossRe...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,625000000

,concept,entity,period,us-gaap:DerivativeInstrumentRiskAxis,us-gaap:HedgingDesignationAxis,unit,value
1012,us-gaap:DerivativeInstrumentsGainLossRecognize...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,-255000000
1013,us-gaap:DerivativeInstrumentsGainLossRecognize...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,-389000000
1014,us-gaap:DerivativeInstrumentsGainLossRecognize...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,-354000000

,concept,entity,period,us-gaap:DerivativeInstrumentRiskAxis,us-gaap:HedgingDesignationAxis,unit,value
1015,us-gaap:OtherComprehensiveIncomeUnrealizedGain...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,11000000
1016,us-gaap:OtherComprehensiveIncomeUnrealizedGain...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,4000000
1017,us-gaap:OtherComprehensiveIncomeUnrealizedGain...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,us-gaap:DesignatedAsHedgingInstrumentMember,iso4217:USD,24000000

,concept,entity,period,unit,value
1018,us-gaap:ForeignCurrencyCashFlowHedgeGainLossTo...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,179000000

,concept,entity,period,us-gaap:DerivativeInstrumentRiskAxis,unit,value
1019,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,iso4217:USD,-33000000
1020,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,iso4217:USD,-117000000
1021,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:ForeignExchangeContractMember,iso4217:USD,-55000000
1022,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,-87000000
1023,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,-114000000
1024,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:EquityContractMember,iso4217:USD,-21000000
1025,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:InterestRateContractMember,iso4217:USD,-15000000
1026,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:InterestRateContractMember,iso4217:USD,14000000
1027,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:InterestRateContractMember,iso4217:USD,10000000
1028,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:CreditRiskContractMember,iso4217:USD,-2000000
1029,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:CreditRiskContractMember,iso4217:USD,5000000
1030,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:CreditRiskContractMember,iso4217:USD,-1000000
1031,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:OtherContractMember,iso4217:USD,0
1032,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:OtherContractMember,iso4217:USD,-22000000
1033,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:OtherContractMember,iso4217:USD,-87000000
1034,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,iso4217:USD,-137000000
1035,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,NaN,iso4217:USD,-234000000
1036,us-gaap:DerivativeInstrumentsNotDesignatedAsHe...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,NaN,iso4217:USD,-154000000

,concept,entity,period,us-gaap:FairValueByAssetClassAxis,us-gaap:FairValueByFairValueHierarchyLevelAxis,us-gaap:FairValueByMeasurementFrequencyAxis,msft:RightOfOffsetAndNettingAxis,unit,value
1037,us-gaap:AssetsFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,us-gaap:MoneyMarketFundsMember,us-gaap:FairValueInputsLevel1Member,us-gaap:FairValueMeasurementsRecurringMember,msft:GrossMember,iso4217:USD,246000000
1038,us-gaap:AssetsFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,us-gaap:MoneyMarketFundsMember,us-gaap:FairValueInputsLevel2Member,us-gaap:FairValueMeasurementsRecurringMember,msft:GrossMember,iso4217:USD,0
1039,us-gaap:AssetsFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,us-gaap:MoneyMarketFundsMember,us-gaap:FairValueInputsLevel3Member,us-gaap:FairValueMeasurementsRecurringMember,msft:GrossMember,iso4217:USD,0
1040,us-gaap:AssetsFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,us-gaap:MoneyMarketFundsMember,NaN,us-gaap:FairValueMeasurementsRecurringMember,msft:GrossMember,iso4217:USD,246000000
1041,us-gaap:AssetsFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,us-gaap:MoneyMarketFundsMember,NaN,us-gaap:FairValueMeasurementsRecurringMember,msft:NettingMember,iso4217:USD,0
...,...,...,...,...,...,...,...,...,...
1172,us-gaap:AssetsFairValueDisclosure,cik:0000789019,2017-07-01T00:00:00,NaN,NaN,us-gaap:FairValueMeasurementsRecurringMember,msft:GrossMember,iso4217:USD,134212000000
1173,us-gaap:AssetsFairValueDisclosure,cik:0000789019,2017-07-01T00:00:00,NaN,NaN,us-gaap:FairValueMeasurementsRecurringMember,msft:NettingMember,iso4217:USD,-227000000
1174,us-gaap:AssetsFairValueDisclosure,cik:0000789019,2017-07-01T00:00:00,NaN,NaN,us-gaap:FairValueMeasurementsRecurringMember,msft:NetMember,iso4217:USD,133985000000
1181,us-gaap:AssetsFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,NaN,NaN,us-gaap:FairValueMeasurementsRecurringMember,NaN,iso4217:USD,130412000000
1182,us-gaap:AssetsFairValueDisclosure,cik:0000789019,2017-07-01T00:00:00,NaN,NaN,us-gaap:FairValueMeasurementsRecurringMember,NaN,iso4217:USD,133985000000

,concept,entity,period,us-gaap:FairValueByFairValueHierarchyLevelAxis,us-gaap:FairValueByLiabilityClassAxis,us-gaap:FairValueByMeasurementFrequencyAxis,msft:RightOfOffsetAndNettingAxis,unit,value
1103,us-gaap:LiabilitiesFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,us-gaap:FairValueInputsLevel1Member,us-gaap:DerivativeFinancialInstrumentsLiabilit...,us-gaap:FairValueMeasurementsRecurringMember,msft:GrossMember,iso4217:USD,1000000
1104,us-gaap:LiabilitiesFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,us-gaap:FairValueInputsLevel2Member,us-gaap:DerivativeFinancialInstrumentsLiabilit...,us-gaap:FairValueMeasurementsRecurringMember,msft:GrossMember,iso4217:USD,206000000
1105,us-gaap:LiabilitiesFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,us-gaap:FairValueInputsLevel3Member,us-gaap:DerivativeFinancialInstrumentsLiabilit...,us-gaap:FairValueMeasurementsRecurringMember,msft:GrossMember,iso4217:USD,0
1106,us-gaap:LiabilitiesFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,NaN,us-gaap:DerivativeFinancialInstrumentsLiabilit...,us-gaap:FairValueMeasurementsRecurringMember,msft:GrossMember,iso4217:USD,207000000
1107,us-gaap:LiabilitiesFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,NaN,us-gaap:DerivativeFinancialInstrumentsLiabilit...,us-gaap:FairValueMeasurementsRecurringMember,msft:NettingMember,iso4217:USD,-153000000
1108,us-gaap:LiabilitiesFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,NaN,us-gaap:DerivativeFinancialInstrumentsLiabilit...,us-gaap:FairValueMeasurementsRecurringMember,msft:NetMember,iso4217:USD,54000000
1175,us-gaap:LiabilitiesFairValueDisclosure,cik:0000789019,2017-07-01T00:00:00,us-gaap:FairValueInputsLevel1Member,us-gaap:DerivativeFinancialInstrumentsLiabilit...,us-gaap:FairValueMeasurementsRecurringMember,msft:GrossMember,iso4217:USD,0
1176,us-gaap:LiabilitiesFairValueDisclosure,cik:0000789019,2017-07-01T00:00:00,us-gaap:FairValueInputsLevel2Member,us-gaap:DerivativeFinancialInstrumentsLiabilit...,us-gaap:FairValueMeasurementsRecurringMember,msft:GrossMember,iso4217:USD,345000000
1177,us-gaap:LiabilitiesFairValueDisclosure,cik:0000789019,2017-07-01T00:00:00,us-gaap:FairValueInputsLevel3Member,us-gaap:DerivativeFinancialInstrumentsLiabilit...,us-gaap:FairValueMeasurementsRecurringMember,msft:GrossMember,iso4217:USD,39000000
1178,us-gaap:LiabilitiesFairValueDisclosure,cik:0000789019,2017-07-01T00:00:00,NaN,us-gaap:DerivativeFinancialInstrumentsLiabilit...,us-gaap:FairValueMeasurementsRecurringMember,msft:GrossMember,iso4217:USD,384000000
1179,us-gaap:LiabilitiesFairValueDisclosure,cik:0000789019,2017-07-01T00:00:00,NaN,us-gaap:DerivativeFinancialInstrumentsLiabilit...,us-gaap:FairValueMeasurementsRecurringMember,msft:NettingMember,iso4217:USD,-228000000
1180,us-gaap:LiabilitiesFairValueDisclosure,cik:0000789019,2017-07-01T00:00:00,NaN,us-gaap:DerivativeFinancialInstrumentsLiabilit...,us-gaap:FairValueMeasurementsRecurringMember,msft:NetMember,iso4217:USD,156000000

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,unit,value
1187,us-gaap:DerivativeAssets,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherAssetsMember,iso4217:USD,282000000
1188,us-gaap:DerivativeAssets,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherAssetsMember,iso4217:USD,202000000

,concept,entity,period,unit,value
1189,us-gaap:OtherAssetsFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,2000000
1190,us-gaap:OtherAssetsFairValueDisclosure,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,1000000

,concept,entity,period,unit,value
1191,us-gaap:InventoryRawMaterialsNetOfReserves,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,655000000
1192,us-gaap:InventoryRawMaterialsNetOfReserves,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,797000000

,concept,entity,period,unit,value
1193,us-gaap:InventoryWorkInProcessNetOfReserves,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,54000000
1194,us-gaap:InventoryWorkInProcessNetOfReserves,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,145000000

,concept,entity,period,unit,value
1195,us-gaap:InventoryFinishedGoodsNetOfReserves,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1953000000
1196,us-gaap:InventoryFinishedGoodsNetOfReserves,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,1239000000

,concept,entity,period,unit,value
1197,us-gaap:Land,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1254000000
1198,us-gaap:Land,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,1107000000

,concept,entity,period,unit,value
1199,us-gaap:BuildingsAndImprovementsGross,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,20604000000
1200,us-gaap:BuildingsAndImprovementsGross,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,16284000000

,concept,entity,period,unit,value
1201,us-gaap:LeaseholdImprovementsGross,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,4735000000
1202,us-gaap:LeaseholdImprovementsGross,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,5064000000

,concept,entity,period,unit,value
1203,msft:ComputerHardwareAndSoftware,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,27633000000
1204,msft:ComputerHardwareAndSoftware,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,21414000000

,concept,entity,period,unit,value
1205,us-gaap:FurnitureAndFixturesGross,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,4457000000
1206,us-gaap:FurnitureAndFixturesGross,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,4044000000

,concept,entity,period,unit,value,us-gaap:LeaseArrangementTypeAxis
1207,us-gaap:PropertyPlantAndEquipmentGross,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,58683000000,NaN
1208,us-gaap:PropertyPlantAndEquipmentGross,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,47913000000,NaN
1935,us-gaap:PropertyPlantAndEquipmentGross,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,4543000000,msft:FinanceLeaseMember
1936,us-gaap:PropertyPlantAndEquipmentGross,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,2658000000,msft:FinanceLeaseMember

,concept,entity,period,unit,value
1209,us-gaap:Depreciation,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,7700000000
1210,us-gaap:Depreciation,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,6100000000
1211,us-gaap:Depreciation,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,4900000000

,concept,entity,period,us-gaap:LongTermPurchaseCommitmentByCategoryOfItemPurchasedAxis,unit,value
1212,us-gaap:CommitmentsFairValueDisclosure,cik:0000789019,2018-07-01T00:00:00,msft:BuildingBuildingImprovementsAndLeaseholdI...,iso4217:USD,1900000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,value
1213,us-gaap:BusinessAcquisitionEffectiveDateOfAcqu...,cik:0000789019,2016-12-07T00:00:00/2016-12-09T00:00:00,msft:LinkedInCorporationMember,2016-12-08

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1214,us-gaap:BusinessCombinationConsiderationTransf...,cik:0000789019,2016-12-07T00:00:00/2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,27000000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1215,us-gaap:PaymentsToAcquireBusinessesGross,cik:0000789019,2016-12-07T00:00:00/2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,26900000000
1249,us-gaap:PaymentsToAcquireBusinessesGross,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:OtherAcquisitionsMember,iso4217:USD,948000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1216,us-gaap:BusinessCombinationRecognizedIdentifia...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,1328000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1217,us-gaap:BusinessCombinationRecognizedIdentifia...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,2110000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1218,us-gaap:BusinessCombinationRecognizedIdentifia...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,697000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1219,us-gaap:BusinessCombinationRecognizedIdentifia...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,1529000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value,us-gaap:FiniteLivedIntangibleAssetsByMajorClassAxis
1220,us-gaap:BusinessCombinationRecognizedIdentifia...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,7887000000,NaN
1229,us-gaap:BusinessCombinationRecognizedIdentifia...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,3607000000,us-gaap:CustomerRelationshipsMember
1230,us-gaap:BusinessCombinationRecognizedIdentifia...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,2148000000,us-gaap:MarketingRelatedIntangibleAssetsMember
1231,us-gaap:BusinessCombinationRecognizedIdentifia...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,2109000000,us-gaap:TechnologyBasedIntangibleAssetsMember
1232,us-gaap:BusinessCombinationRecognizedIdentifia...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,23000000,us-gaap:ContractualRightsMember

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1222,msft:BusinessCombinationRecognizedIdentifiable...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,1323000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1223,us-gaap:BusinessCombinationRecognizedIdentifia...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,1117000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1224,us-gaap:BusinessCombinationRecognizedIdentifia...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,774000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1225,msft:BusinessCombinationRecognizedIdentifiable...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,131000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1226,us-gaap:BusinessCombinationRecognizedIdentifia...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,27009000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1227,us-gaap:BusinessAcquisitionPurchasePriceAlloca...,cik:0000789019,2016-12-09T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,0

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value,us-gaap:DebtInstrumentAxis
1228,us-gaap:DebtInstrumentFaceAmount,cik:0000789019,2017-07-01T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,18000000,NaN
1450,us-gaap:DebtInstrumentFaceAmount,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,0,msft:NotesZeroPointEightSevenFivePercentDueNov...
1451,us-gaap:DebtInstrumentFaceAmount,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,0,msft:NotesOnePointZeroPercentDueMayOneTwentyEi...
1452,us-gaap:DebtInstrumentFaceAmount,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,1750000000,msft:NotesOnePointThreeZeroPercentDueNovemberT...
1453,us-gaap:DebtInstrumentFaceAmount,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,1250000000,msft:NotesOnePointSixTwoFivePercentDueDecember...
...,...,...,...,...,...,...,...
1539,us-gaap:DebtInstrumentFaceAmount,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,2250000000,msft:NotesFourPercentDueFebruaryTwelveTwentyFi...
1540,us-gaap:DebtInstrumentFaceAmount,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,1000000000,msft:NotesFourPointSevenFivePercentDueNovember...
1541,us-gaap:DebtInstrumentFaceAmount,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,2250000000,msft:NotesThreePointNineFivePercentDueAugustEi...
1542,us-gaap:DebtInstrumentFaceAmount,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,2000000000,msft:NotesFourPointFivePercentDueFebruarySixTw...
1543,us-gaap:DebtInstrumentFaceAmount,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,77837000000,NaN

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,us-gaap:FiniteLivedIntangibleAssetsByMajorClassAxis,value
1233,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2016-12-07T00:00:00/2016-12-09T00:00:00,msft:LinkedInCorporationMember,us-gaap:CustomerRelationshipsMember,P7Y
1234,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2016-12-07T00:00:00/2016-12-09T00:00:00,msft:LinkedInCorporationMember,us-gaap:MarketingRelatedIntangibleAssetsMember,P20Y
1235,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2016-12-07T00:00:00/2016-12-09T00:00:00,msft:LinkedInCorporationMember,us-gaap:TechnologyBasedIntangibleAssetsMember,P3Y
1236,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2016-12-07T00:00:00/2016-12-09T00:00:00,msft:LinkedInCorporationMember,us-gaap:ContractualRightsMember,P5Y
1237,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2016-12-07T00:00:00/2016-12-09T00:00:00,msft:LinkedInCorporationMember,NaN,P9Y
1315,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,us-gaap:TechnologyBasedIntangibleAssetsMember,P4Y
1316,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,us-gaap:MarketingRelatedIntangibleAssetsMember,P5Y
1317,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,us-gaap:ContractualRightsMember,P4Y
1318,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,us-gaap:CustomerRelationshipsMember,P5Y
1319,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,NaN,P5Y
1325,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,NaN,us-gaap:TechnologyBasedIntangibleAssetsMember,P2Y
1326,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,NaN,us-gaap:MarketingRelatedIntangibleAssetsMember,P19Y
1327,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,NaN,us-gaap:ContractualRightsMember,P6Y
1328,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,NaN,us-gaap:CustomerRelationshipsMember,P7Y
1329,us-gaap:AcquiredFiniteLivedIntangibleAssetsWei...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,NaN,NaN,P9Y

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1238,us-gaap:BusinessCombinationProFormaInformation...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,2271000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1239,us-gaap:BusinessCombinationProFormaInformation...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,-924000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1240,us-gaap:BusinessAcquisitionsProFormaRevenue,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,98291000000
1241,us-gaap:BusinessAcquisitionsProFormaRevenue,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,94490000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1242,us-gaap:BusinessAcquisitionsProFormaNetIncomeLoss,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,25179000000
1243,us-gaap:BusinessAcquisitionsProFormaNetIncomeLoss,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,msft:LinkedInCorporationMember,iso4217:USD,19128000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1244,us-gaap:BusinessAcquisitionProFormaEarningsPer...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:LinkedInCorporationMember,iso4217:USD/xbrli:shares,3.21
1245,us-gaap:BusinessAcquisitionProFormaEarningsPer...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,msft:LinkedInCorporationMember,iso4217:USD/xbrli:shares,2.38

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,value
1246,us-gaap:BusinessAcquisitionDateOfAcquisitionAg...,cik:0000789019,2018-06-04T00:00:00/2018-06-05T00:00:00,msft:GitHubIncMember,2018-06-04

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1247,msft:BusinessCombinationConsiderationToBeTrans...,cik:0000789019,2018-06-04T00:00:00/2018-06-05T00:00:00,msft:GitHubIncMember,iso4217:USD,7500000000

,concept,entity,period,us-gaap:BusinessAcquisitionAxis,unit,value
1248,us-gaap:NumberOfBusinessesAcquired,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:OtherAcquisitionsMember,msft:Acquisition,9

,concept,entity,period,us-gaap:StatementBusinessSegmentsAxis,unit,value
1254,us-gaap:GoodwillAcquiredDuringPeriod,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:ProductivityAndBusinessProcessesMember,iso4217:USD,17072000000
1255,us-gaap:GoodwillAcquiredDuringPeriod,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:IntelligentCloudMember,iso4217:USD,49000000
1256,us-gaap:GoodwillAcquiredDuringPeriod,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:MorePersonalComputingMember,iso4217:USD,115000000
1257,us-gaap:GoodwillAcquiredDuringPeriod,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,NaN,iso4217:USD,17236000000
1265,us-gaap:GoodwillAcquiredDuringPeriod,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:ProductivityAndBusinessProcessesMember,iso4217:USD,72000000
1266,us-gaap:GoodwillAcquiredDuringPeriod,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:IntelligentCloudMember,iso4217:USD,164000000
1267,us-gaap:GoodwillAcquiredDuringPeriod,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:MorePersonalComputingMember,iso4217:USD,394000000
1268,us-gaap:GoodwillAcquiredDuringPeriod,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,iso4217:USD,630000000

,concept,entity,period,us-gaap:StatementBusinessSegmentsAxis,unit,value
1258,us-gaap:GoodwillOtherIncreaseDecrease,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:ProductivityAndBusinessProcessesMember,iso4217:USD,-11000000
1259,us-gaap:GoodwillOtherIncreaseDecrease,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:IntelligentCloudMember,iso4217:USD,39000000
1260,us-gaap:GoodwillOtherIncreaseDecrease,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:MorePersonalComputingMember,iso4217:USD,-14000000
1261,us-gaap:GoodwillOtherIncreaseDecrease,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,NaN,iso4217:USD,14000000
1269,us-gaap:GoodwillOtherIncreaseDecrease,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:ProductivityAndBusinessProcessesMember,iso4217:USD,12000000
1270,us-gaap:GoodwillOtherIncreaseDecrease,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:IntelligentCloudMember,iso4217:USD,-16000000
1271,us-gaap:GoodwillOtherIncreaseDecrease,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:MorePersonalComputingMember,iso4217:USD,-65000000
1272,us-gaap:GoodwillOtherIncreaseDecrease,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,iso4217:USD,-69000000

,concept,entity,period,unit,value
1276,us-gaap:GoodwillImpairedAccumulatedImpairmentLoss,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,11300000000
1277,us-gaap:GoodwillImpairedAccumulatedImpairmentLoss,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,11300000000

,concept,entity,period,unit,value
1278,us-gaap:GoodwillImpairmentLoss,cik:0000789019,2018-05-01T00:00:00/2018-05-02T00:00:00,iso4217:USD,0
1279,us-gaap:GoodwillImpairmentLoss,cik:0000789019,2017-05-01T00:00:00/2017-05-02T00:00:00,iso4217:USD,0
1280,us-gaap:GoodwillImpairmentLoss,cik:0000789019,2016-05-01T00:00:00/2016-05-02T00:00:00,iso4217:USD,0

,concept,entity,period,us-gaap:FiniteLivedIntangibleAssetsByMajorClassAxis,unit,value
1281,us-gaap:FiniteLivedIntangibleAssetsGross,cik:0000789019,2018-07-01T00:00:00,us-gaap:TechnologyBasedIntangibleAssetsMember,iso4217:USD,7220000000
1282,us-gaap:FiniteLivedIntangibleAssetsGross,cik:0000789019,2018-07-01T00:00:00,us-gaap:CustomerRelationshipsMember,iso4217:USD,4031000000
1283,us-gaap:FiniteLivedIntangibleAssetsGross,cik:0000789019,2018-07-01T00:00:00,us-gaap:MarketingRelatedIntangibleAssetsMember,iso4217:USD,4006000000
1284,us-gaap:FiniteLivedIntangibleAssetsGross,cik:0000789019,2018-07-01T00:00:00,us-gaap:ContractualRightsMember,iso4217:USD,679000000
1285,us-gaap:FiniteLivedIntangibleAssetsGross,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,15936000000
1295,us-gaap:FiniteLivedIntangibleAssetsGross,cik:0000789019,2017-07-01T00:00:00,us-gaap:TechnologyBasedIntangibleAssetsMember,iso4217:USD,7765000000
1296,us-gaap:FiniteLivedIntangibleAssetsGross,cik:0000789019,2017-07-01T00:00:00,us-gaap:CustomerRelationshipsMember,iso4217:USD,4045000000
1297,us-gaap:FiniteLivedIntangibleAssetsGross,cik:0000789019,2017-07-01T00:00:00,us-gaap:MarketingRelatedIntangibleAssetsMember,iso4217:USD,4016000000
1298,us-gaap:FiniteLivedIntangibleAssetsGross,cik:0000789019,2017-07-01T00:00:00,us-gaap:ContractualRightsMember,iso4217:USD,841000000
1299,us-gaap:FiniteLivedIntangibleAssetsGross,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,16667000000

,concept,entity,period,us-gaap:FiniteLivedIntangibleAssetsByMajorClassAxis,unit,value
1286,us-gaap:FiniteLivedIntangibleAssetsAccumulated...,cik:0000789019,2018-07-01T00:00:00,us-gaap:TechnologyBasedIntangibleAssetsMember,iso4217:USD,5018000000
1287,us-gaap:FiniteLivedIntangibleAssetsAccumulated...,cik:0000789019,2018-07-01T00:00:00,us-gaap:CustomerRelationshipsMember,iso4217:USD,1205000000
1288,us-gaap:FiniteLivedIntangibleAssetsAccumulated...,cik:0000789019,2018-07-01T00:00:00,us-gaap:MarketingRelatedIntangibleAssetsMember,iso4217:USD,1071000000
1289,us-gaap:FiniteLivedIntangibleAssetsAccumulated...,cik:0000789019,2018-07-01T00:00:00,us-gaap:ContractualRightsMember,iso4217:USD,589000000
1290,us-gaap:FiniteLivedIntangibleAssetsAccumulated...,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,7883000000
1300,us-gaap:FiniteLivedIntangibleAssetsAccumulated...,cik:0000789019,2017-07-01T00:00:00,us-gaap:TechnologyBasedIntangibleAssetsMember,iso4217:USD,4318000000
1301,us-gaap:FiniteLivedIntangibleAssetsAccumulated...,cik:0000789019,2017-07-01T00:00:00,us-gaap:CustomerRelationshipsMember,iso4217:USD,692000000
1302,us-gaap:FiniteLivedIntangibleAssetsAccumulated...,cik:0000789019,2017-07-01T00:00:00,us-gaap:MarketingRelatedIntangibleAssetsMember,iso4217:USD,829000000
1303,us-gaap:FiniteLivedIntangibleAssetsAccumulated...,cik:0000789019,2017-07-01T00:00:00,us-gaap:ContractualRightsMember,iso4217:USD,722000000
1304,us-gaap:FiniteLivedIntangibleAssetsAccumulated...,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,6561000000

,concept,entity,period,us-gaap:StatementBusinessSegmentsAxis,unit,value
1309,us-gaap:ImpairmentOfIntangibleAssetsFinitelived,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,msft:DevicesMember,iso4217:USD,480000000

,concept,entity,period,us-gaap:FiniteLivedIntangibleAssetsByMajorClassAxis,unit,value
1310,msft:AcquiredFiniteLivedIntangibleAssets,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:TechnologyBasedIntangibleAssetsMember,iso4217:USD,178000000
1311,msft:AcquiredFiniteLivedIntangibleAssets,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:MarketingRelatedIntangibleAssetsMember,iso4217:USD,14000000
1312,msft:AcquiredFiniteLivedIntangibleAssets,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:ContractualRightsMember,iso4217:USD,14000000
1313,msft:AcquiredFiniteLivedIntangibleAssets,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:CustomerRelationshipsMember,iso4217:USD,13000000
1314,msft:AcquiredFiniteLivedIntangibleAssets,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,iso4217:USD,219000000
1320,msft:AcquiredFiniteLivedIntangibleAssets,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:TechnologyBasedIntangibleAssetsMember,iso4217:USD,2265000000
1321,msft:AcquiredFiniteLivedIntangibleAssets,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:MarketingRelatedIntangibleAssetsMember,iso4217:USD,2148000000
1322,msft:AcquiredFiniteLivedIntangibleAssets,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:ContractualRightsMember,iso4217:USD,63000000
1323,msft:AcquiredFiniteLivedIntangibleAssets,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:CustomerRelationshipsMember,iso4217:USD,3607000000
1324,msft:AcquiredFiniteLivedIntangibleAssets,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,NaN,iso4217:USD,8083000000

,concept,entity,period,unit,value
1330,us-gaap:AmortizationOfIntangibleAssets,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,2200000000
1331,us-gaap:AmortizationOfIntangibleAssets,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1700000000
1332,us-gaap:AmortizationOfIntangibleAssets,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,978000000

,concept,entity,period,unit,value
1333,us-gaap:CapitalizedComputerSoftwareAmortization1,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,54000000
1334,us-gaap:CapitalizedComputerSoftwareAmortization1,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,55000000
1335,us-gaap:CapitalizedComputerSoftwareAmortization1,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,69000000

,concept,entity,period,unit,value
1336,us-gaap:FiniteLivedIntangibleAssetsAmortizatio...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1785000000

,concept,entity,period,unit,value
1337,us-gaap:FiniteLivedIntangibleAssetsAmortizatio...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1260000000

,concept,entity,period,unit,value
1338,us-gaap:FiniteLivedIntangibleAssetsAmortizatio...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1043000000

,concept,entity,period,unit,value
1339,us-gaap:FiniteLivedIntangibleAssetsAmortizatio...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,949000000

,concept,entity,period,unit,value
1340,us-gaap:FiniteLivedIntangibleAssetsAmortizatio...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,806000000

,concept,entity,period,unit,value
1341,us-gaap:FiniteLivedIntangibleAssetsAmortizatio...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,2210000000

,concept,entity,period,unit,value
1342,us-gaap:CommercialPaper,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0
1343,us-gaap:CommercialPaper,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,9100000000

,concept,entity,period,us-gaap:ShortTermDebtTypeAxis,value
1344,us-gaap:ShortTermDebtWeightedAverageInterestRate,cik:0000789019,2017-07-01T00:00:00,us-gaap:CommercialPaperMember,0.0101

,concept,entity,period,srt:RangeAxis,us-gaap:ShortTermDebtTypeAxis,value
1345,us-gaap:DebtInstrumentTerm,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,srt:MinimumMember,us-gaap:CommercialPaperMember,P25D
1346,us-gaap:DebtInstrumentTerm,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,srt:MaximumMember,us-gaap:CommercialPaperMember,P264D

,concept,entity,period,us-gaap:DebtInstrumentAxis,unit,value
1347,us-gaap:LineOfCreditFacilityMaximumBorrowingCa...,cik:0000789019,2017-11-01T00:00:00,msft:CreditFacilityExpireOnOctoberThirtyTwenty...,iso4217:USD,5000000000
1349,us-gaap:LineOfCreditFacilityMaximumBorrowingCa...,cik:0000789019,2017-11-01T00:00:00,msft:CreditFacilityExpireOnOctoberThirtyFirstT...,iso4217:USD,5000000000

,concept,entity,period,us-gaap:DebtInstrumentAxis,value
1348,us-gaap:LineOfCreditFacilityExpirationDate1,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:CreditFacilityExpireOnOctoberThirtyTwenty...,2018-10-30
1350,us-gaap:LineOfCreditFacilityExpirationDate1,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:CreditFacilityExpireOnOctoberThirtyFirstT...,2022-10-31

,concept,entity,period,value
1351,us-gaap:LineOfCreditFacilityCovenantCompliance,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,"As of June 30, 2018, we were i"

,concept,entity,period,unit,value
1352,us-gaap:ProceedsFromLinesOfCredit,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,0
1353,us-gaap:ProceedsFromLinesOfCredit,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,0

,concept,entity,period,unit,value
1354,us-gaap:LongTermDebt,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,76200000000
1355,us-gaap:LongTermDebt,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,77100000000

,concept,entity,period,unit,value
1356,us-gaap:LongTermDebtFairValue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,77500000000
1357,us-gaap:LongTermDebtFairValue,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,80300000000

,concept,entity,period,us-gaap:DebtInstrumentAxis,value
1358,us-gaap:DebtInstrumentMaturityDate,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:NotesZeroPointEightSevenFivePercentDueNov...,2017-11-15
1359,us-gaap:DebtInstrumentMaturityDate,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:NotesOnePointZeroPercentDueMayOneTwentyEi...,2018-05-01
1360,us-gaap:DebtInstrumentMaturityDate,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:NotesOnePointThreeZeroPercentDueNovemberT...,2018-11-03
1361,us-gaap:DebtInstrumentMaturityDate,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:NotesOnePointSixTwoFivePercentDueDecember...,2018-12-06
1362,us-gaap:DebtInstrumentMaturityDate,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:NotesFourPointTwoPercentDueJuneOneTwentyN...,2019-06-01
...,...,...,...,...,...
1445,us-gaap:DebtInstrumentMaturityDate,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:NotesFourPointTwoFivePercentDueFebruarySi...,2047-02-06
1446,us-gaap:DebtInstrumentMaturityDate,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:NotesFourPercentDueFebruaryTwelveTwentyFi...,2055-02-12
1447,us-gaap:DebtInstrumentMaturityDate,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:NotesFourPointSevenFivePercentDueNovember...,2055-11-03
1448,us-gaap:DebtInstrumentMaturityDate,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:NotesThreePointNineFivePercentDueAugustEi...,2056-08-08
1449,us-gaap:DebtInstrumentMaturityDate,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:NotesFourPointFivePercentDueFebruarySixTw...,2057-02-06

,concept,entity,period,us-gaap:DebtInstrumentAxis,value
1544,us-gaap:DebtInstrumentInterestRateStatedPercen...,cik:0000789019,2018-07-01T00:00:00,msft:NotesZeroPointEightSevenFivePercentDueNov...,0.00875
1545,us-gaap:DebtInstrumentInterestRateStatedPercen...,cik:0000789019,2018-07-01T00:00:00,msft:NotesOnePointZeroPercentDueMayOneTwentyEi...,0.01000
1546,us-gaap:DebtInstrumentInterestRateStatedPercen...,cik:0000789019,2018-07-01T00:00:00,msft:NotesOnePointThreeZeroPercentDueNovemberT...,0.01300
1547,us-gaap:DebtInstrumentInterestRateStatedPercen...,cik:0000789019,2018-07-01T00:00:00,msft:NotesOnePointSixTwoFivePercentDueDecember...,0.01625
1548,us-gaap:DebtInstrumentInterestRateStatedPercen...,cik:0000789019,2018-07-01T00:00:00,msft:NotesFourPointTwoPercentDueJuneOneTwentyN...,0.04200
...,...,...,...,...,...
1677,us-gaap:DebtInstrumentInterestRateStatedPercen...,cik:0000789019,2017-07-01T00:00:00,msft:NotesFourPointTwoFivePercentDueFebruarySi...,0.04250
1678,us-gaap:DebtInstrumentInterestRateStatedPercen...,cik:0000789019,2017-07-01T00:00:00,msft:NotesFourPercentDueFebruaryTwelveTwentyFi...,0.04000
1679,us-gaap:DebtInstrumentInterestRateStatedPercen...,cik:0000789019,2017-07-01T00:00:00,msft:NotesFourPointSevenFivePercentDueNovember...,0.04750
1680,us-gaap:DebtInstrumentInterestRateStatedPercen...,cik:0000789019,2017-07-01T00:00:00,msft:NotesThreePointNineFivePercentDueAugustEi...,0.03950
1681,us-gaap:DebtInstrumentInterestRateStatedPercen...,cik:0000789019,2017-07-01T00:00:00,msft:NotesFourPointFivePercentDueFebruarySixTw...,0.04500

,concept,entity,period,us-gaap:DebtInstrumentAxis,value
1590,us-gaap:DebtInstrumentInterestRateEffectivePer...,cik:0000789019,2018-07-01T00:00:00,msft:NotesZeroPointEightSevenFivePercentDueNov...,0.01084
1591,us-gaap:DebtInstrumentInterestRateEffectivePer...,cik:0000789019,2018-07-01T00:00:00,msft:NotesOnePointZeroPercentDueMayOneTwentyEi...,0.01106
1592,us-gaap:DebtInstrumentInterestRateEffectivePer...,cik:0000789019,2018-07-01T00:00:00,msft:NotesOnePointThreeZeroPercentDueNovemberT...,0.01396
1593,us-gaap:DebtInstrumentInterestRateEffectivePer...,cik:0000789019,2018-07-01T00:00:00,msft:NotesOnePointSixTwoFivePercentDueDecember...,0.01824
1594,us-gaap:DebtInstrumentInterestRateEffectivePer...,cik:0000789019,2018-07-01T00:00:00,msft:NotesFourPointTwoPercentDueJuneOneTwentyN...,0.04379
...,...,...,...,...,...
1723,us-gaap:DebtInstrumentInterestRateEffectivePer...,cik:0000789019,2017-07-01T00:00:00,msft:NotesFourPointTwoFivePercentDueFebruarySi...,0.04287
1724,us-gaap:DebtInstrumentInterestRateEffectivePer...,cik:0000789019,2017-07-01T00:00:00,msft:NotesFourPercentDueFebruaryTwelveTwentyFi...,0.04063
1725,us-gaap:DebtInstrumentInterestRateEffectivePer...,cik:0000789019,2017-07-01T00:00:00,msft:NotesFourPointSevenFivePercentDueNovember...,0.04782
1726,us-gaap:DebtInstrumentInterestRateEffectivePer...,cik:0000789019,2017-07-01T00:00:00,msft:NotesThreePointNineFivePercentDueAugustEi...,0.04033
1727,us-gaap:DebtInstrumentInterestRateEffectivePer...,cik:0000789019,2017-07-01T00:00:00,msft:NotesFourPointFivePercentDueFebruarySixTw...,0.04528

,concept,entity,period,unit,value
1728,us-gaap:InterestPaid,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,2400000000
1729,us-gaap:InterestPaid,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1600000000
1730,us-gaap:InterestPaid,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,1100000000

,concept,entity,period,unit,value
1731,us-gaap:DebtInstrumentUnamortizedDiscountPremi...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,658000000
1732,us-gaap:DebtInstrumentUnamortizedDiscountPremi...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,715000000

,concept,entity,period,unit,value
1733,us-gaap:LongTermDebtMaturitiesRepaymentsOfPrin...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,4000000000

,concept,entity,period,unit,value
1734,us-gaap:LongTermDebtMaturitiesRepaymentsOfPrin...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,5518000000

,concept,entity,period,unit,value
1735,us-gaap:LongTermDebtMaturitiesRepaymentsOfPrin...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,3750000000

,concept,entity,period,unit,value
1736,us-gaap:LongTermDebtMaturitiesRepaymentsOfPrin...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,8044000000

,concept,entity,period,unit,value
1737,us-gaap:LongTermDebtMaturitiesRepaymentsOfPrin...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,2750000000

,concept,entity,period,unit,value
1738,us-gaap:LongTermDebtMaturitiesRepaymentsOfPrin...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,52836000000

,concept,entity,period,value
1739,us-gaap:EffectiveIncomeTaxRateReconciliationAt...,cik:0000789019,2017-07-01T00:00:00/2018-01-01T00:00:00,0.35
1740,us-gaap:EffectiveIncomeTaxRateReconciliationAt...,cik:0000789019,2018-01-01T00:00:00/2018-07-01T00:00:00,0.21
1741,us-gaap:EffectiveIncomeTaxRateReconciliationAt...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,0.281
1772,us-gaap:EffectiveIncomeTaxRateReconciliationAt...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,0.350
1773,us-gaap:EffectiveIncomeTaxRateReconciliationAt...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,0.350

,concept,entity,period,us-gaap:IncomeTaxAuthorityAxis,unit,value
1743,us-gaap:IncomeTaxReconciliationRepatriationOfF...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:TaxCutsAndJobsActMember,iso4217:USD,17900000000

,concept,entity,period,us-gaap:IncomeTaxAuthorityAxis,unit,value
1744,us-gaap:IncomeTaxReconciliationChangeInEnacted...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:TaxCutsAndJobsActMember,iso4217:USD,-4200000000

,concept,entity,period,unit,value
1745,us-gaap:CurrentFederalTaxExpenseBenefit,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,19764000000
1746,us-gaap:CurrentFederalTaxExpenseBenefit,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,2739000000
1747,us-gaap:CurrentFederalTaxExpenseBenefit,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,545000000

,concept,entity,period,unit,value
1748,us-gaap:CurrentStateAndLocalTaxExpenseBenefit,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,934000000
1749,us-gaap:CurrentStateAndLocalTaxExpenseBenefit,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,30000000
1750,us-gaap:CurrentStateAndLocalTaxExpenseBenefit,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,136000000

,concept,entity,period,unit,value
1751,us-gaap:CurrentForeignTaxExpenseBenefit,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,4348000000
1752,us-gaap:CurrentForeignTaxExpenseBenefit,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,2472000000
1753,us-gaap:CurrentForeignTaxExpenseBenefit,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,1940000000

,concept,entity,period,unit,value
1754,us-gaap:CurrentIncomeTaxExpenseBenefit,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,25046000000
1755,us-gaap:CurrentIncomeTaxExpenseBenefit,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,5241000000
1756,us-gaap:CurrentIncomeTaxExpenseBenefit,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,2621000000

,concept,entity,period,unit,value
1757,us-gaap:DeferredFederalIncomeTaxExpenseBenefit,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-4292000000
1758,us-gaap:DeferredFederalIncomeTaxExpenseBenefit,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-554000000
1759,us-gaap:DeferredFederalIncomeTaxExpenseBenefit,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,1919000000

,concept,entity,period,unit,value
1760,us-gaap:DeferredStateAndLocalIncomeTaxExpenseB...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-458000000
1761,us-gaap:DeferredStateAndLocalIncomeTaxExpenseB...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,269000000
1762,us-gaap:DeferredStateAndLocalIncomeTaxExpenseB...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,111000000

,concept,entity,period,unit,value
1763,us-gaap:DeferredForeignIncomeTaxExpenseBenefit,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,-393000000
1764,us-gaap:DeferredForeignIncomeTaxExpenseBenefit,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,-544000000
1765,us-gaap:DeferredForeignIncomeTaxExpenseBenefit,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,449000000

,concept,entity,period,unit,value
1766,us-gaap:IncomeLossFromContinuingOperationsBefo...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,11527000000
1767,us-gaap:IncomeLossFromContinuingOperationsBefo...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,6843000000
1768,us-gaap:IncomeLossFromContinuingOperationsBefo...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,5125000000

,concept,entity,period,unit,value
1769,us-gaap:IncomeLossFromContinuingOperationsBefo...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,24947000000
1770,us-gaap:IncomeLossFromContinuingOperationsBefo...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,23058000000
1771,us-gaap:IncomeLossFromContinuingOperationsBefo...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,20514000000

,concept,entity,period,value
1774,us-gaap:EffectiveIncomeTaxRateReconciliationFo...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,-0.078
1775,us-gaap:EffectiveIncomeTaxRateReconciliationFo...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,-0.116
1776,us-gaap:EffectiveIncomeTaxRateReconciliationFo...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,-0.145

,concept,entity,period,value
1777,msft:EffectiveIncomeTaxRateReconciliationTaxCu...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,0.377
1778,msft:EffectiveIncomeTaxRateReconciliationTaxCu...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,0
1779,msft:EffectiveIncomeTaxRateReconciliationTaxCu...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,0

,concept,entity,period,value
1780,msft:EffectiveIncomeTaxRateReconciliationPhone...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,0
1781,msft:EffectiveIncomeTaxRateReconciliationPhone...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,-0.057
1782,msft:EffectiveIncomeTaxRateReconciliationPhone...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,0.010

,concept,entity,period,value
1783,msft:EffectiveIncomeTaxRateReconciliationDeduc...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,0.025
1784,msft:EffectiveIncomeTaxRateReconciliationDeduc...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,0.021
1785,msft:EffectiveIncomeTaxRateReconciliationDeduc...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,0.016

,concept,entity,period,value
1786,msft:EffectiveIncomeTaxRateReconciliationInter...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,0.012
1787,msft:EffectiveIncomeTaxRateReconciliationInter...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,0.014
1788,msft:EffectiveIncomeTaxRateReconciliationInter...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,0.009

,concept,entity,period,value
1789,us-gaap:EffectiveIncomeTaxRateReconciliationOt...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,-0.021
1790,us-gaap:EffectiveIncomeTaxRateReconciliationOt...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,-0.022
1791,us-gaap:EffectiveIncomeTaxRateReconciliationOt...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,-0.009

,concept,entity,period,value
1792,us-gaap:EffectiveIncomeTaxRateContinuingOperat...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,0.546
1793,us-gaap:EffectiveIncomeTaxRateContinuingOperat...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,0.148
1794,us-gaap:EffectiveIncomeTaxRateContinuingOperat...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,0.199

,concept,entity,period,us-gaap:IncomeTaxAuthorityAxis,value
1795,msft:ForeignEarningsTaxedAtRatesLowerThanUsRate,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:RegionalOperatingCentersMember,0.87
1796,msft:ForeignEarningsTaxedAtRatesLowerThanUsRate,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:RegionalOperatingCentersMember,0.76
1797,msft:ForeignEarningsTaxedAtRatesLowerThanUsRate,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,msft:RegionalOperatingCentersMember,0.91

,concept,entity,period,unit,value
1798,us-gaap:DeferredTaxAssetsTaxDeferredExpenseCom...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,460000000
1815,us-gaap:DeferredTaxAssetsTaxDeferredExpenseCom...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,777000000

,concept,entity,period,unit,value
1799,us-gaap:DeferredTaxAssetsTaxDeferredExpenseRes...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1832000000
1816,us-gaap:DeferredTaxAssetsTaxDeferredExpenseRes...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,1859000000

,concept,entity,period,unit,value
1800,msft:DeferredTaxAssetsOperatingLossAndTaxCredi...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,3369000000
1817,msft:DeferredTaxAssetsOperatingLossAndTaxCredi...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,4809000000

,concept,entity,period,unit,value
1801,msft:DeferredTaxAssetsDepreciationAndAmortization,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,351000000
1818,msft:DeferredTaxAssetsDepreciationAndAmortization,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,53000000

,concept,entity,period,unit,value
1802,us-gaap:DeferredTaxAssetsOther,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,56000000
1819,us-gaap:DeferredTaxAssetsOther,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,255000000

,concept,entity,period,unit,value
1803,us-gaap:DeferredTaxAssetsGross,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,6068000000
1820,us-gaap:DeferredTaxAssetsGross,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,7753000000

,concept,entity,period,unit,value
1804,us-gaap:DeferredTaxAssetsValuationAllowance,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,3186000000
1821,us-gaap:DeferredTaxAssetsValuationAllowance,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,3310000000

,concept,entity,period,unit,value
1805,us-gaap:DeferredTaxAssetsNet,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,2882000000
1822,us-gaap:DeferredTaxAssetsNet,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,4443000000

,concept,entity,period,unit,value
1806,us-gaap:DeferredTaxLiabilitiesUndistributedFor...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0
1823,us-gaap:DeferredTaxLiabilitiesUndistributedFor...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,1134000000

,concept,entity,period,unit,value
1807,msft:DeferredTaxLiabilitiesUnrealizedGainsInve...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,0
1824,msft:DeferredTaxLiabilitiesUnrealizedGainsInve...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,1384000000

,concept,entity,period,unit,value
1808,us-gaap:DeferredTaxLiabilitiesTaxDeferredIncome,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,639000000
1825,us-gaap:DeferredTaxLiabilitiesTaxDeferredIncome,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,5760000000

,concept,entity,period,unit,value
1809,msft:DeferredTaxLiabilitiesDepreciationAndAmor...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1103000000
1826,msft:DeferredTaxLiabilitiesDepreciationAndAmor...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,1630000000

,concept,entity,period,unit,value
1810,us-gaap:DeferredTaxLiabilitiesOther,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,312000000
1827,us-gaap:DeferredTaxLiabilitiesOther,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,21000000

,concept,entity,period,unit,value
1811,us-gaap:DeferredIncomeTaxLiabilities,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,2054000000
1828,us-gaap:DeferredIncomeTaxLiabilities,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,9929000000

,concept,entity,period,unit,value
1812,us-gaap:DeferredTaxAssetsLiabilitiesNet,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,828000000

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,unit,value
1813,us-gaap:DeferredTaxAssetsLiabilitiesNetNoncurrent,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,iso4217:USD,1369000000
1830,us-gaap:DeferredTaxAssetsLiabilitiesNetNoncurrent,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentAssetsMember,iso4217:USD,248000000

,concept,entity,period,unit,value,srt:RestatementAxis,us-gaap:AdjustmentsForNewAccountingPronouncementsAxis
1829,us-gaap:DeferredTaxLiabilities,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,5486000000,NaN,NaN
1832,us-gaap:DeferredTaxLiabilities,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,7400000000,srt:RestatementAdjustmentMember,us-gaap:AccountingStandardsUpdate201409Member

,concept,entity,period,us-gaap:IncomeTaxAuthorityAxis,unit,value
1833,us-gaap:OperatingLossCarryforwards,cik:0000789019,2018-07-01T00:00:00,us-gaap:DomesticCountryMember,iso4217:USD,257000000
1834,us-gaap:OperatingLossCarryforwards,cik:0000789019,2018-07-01T00:00:00,us-gaap:StateAndLocalJurisdictionMember,iso4217:USD,1400000000
1835,us-gaap:OperatingLossCarryforwards,cik:0000789019,2018-07-01T00:00:00,us-gaap:ForeignCountryMember,iso4217:USD,11400000000

,concept,entity,period,us-gaap:IncomeTaxAuthorityAxis,us-gaap:TaxPeriodAxis,value
1836,msft:OperatingLossCarryforwardsExpirationYear,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:FederalAndStateMember,us-gaap:EarliestTaxYearMember,2019
1837,msft:OperatingLossCarryforwardsExpirationYear,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:FederalAndStateMember,us-gaap:LatestTaxYearMember,2038

,concept,entity,period,unit,value
1838,us-gaap:IncomeTaxesPaidNet,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,5500000000
1839,us-gaap:IncomeTaxesPaidNet,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,2400000000
1840,us-gaap:IncomeTaxesPaidNet,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,3900000000

,concept,entity,period,unit,value
1841,us-gaap:UnrecognizedTaxBenefits,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,11961000000
1842,us-gaap:UnrecognizedTaxBenefits,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,11737000000
1843,us-gaap:UnrecognizedTaxBenefits,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,10164000000
1863,us-gaap:UnrecognizedTaxBenefits,cik:0000789019,2015-07-01T00:00:00,iso4217:USD,9599000000

,concept,entity,period,unit,value
1844,us-gaap:UnrecognizedTaxBenefitsThatWouldImpact...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,11300000000
1845,us-gaap:UnrecognizedTaxBenefitsThatWouldImpact...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,10200000000
1846,us-gaap:UnrecognizedTaxBenefitsThatWouldImpact...,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,8800000000

,concept,entity,period,unit,value
1847,us-gaap:UnrecognizedTaxBenefitsIncomeTaxPenalt...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,3000000000
1848,us-gaap:UnrecognizedTaxBenefitsIncomeTaxPenalt...,cik:0000789019,2017-07-01T00:00:00,iso4217:USD,2300000000
1849,us-gaap:UnrecognizedTaxBenefitsIncomeTaxPenalt...,cik:0000789019,2016-07-01T00:00:00,iso4217:USD,1900000000

,concept,entity,period,unit,value
1850,us-gaap:UnrecognizedTaxBenefitsIncomeTaxPenalt...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,688000000
1851,us-gaap:UnrecognizedTaxBenefitsIncomeTaxPenalt...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,399000000
1852,us-gaap:UnrecognizedTaxBenefitsIncomeTaxPenalt...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,163000000

,concept,entity,period,unit,value
1853,us-gaap:UnrecognizedTaxBenefitsDecreasesResult...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,193000000
1858,us-gaap:UnrecognizedTaxBenefitsDecreasesResult...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,4000000
1864,us-gaap:UnrecognizedTaxBenefitsDecreasesResult...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,201000000

,concept,entity,period,unit,value
1854,us-gaap:UnrecognizedTaxBenefitsIncreasesResult...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,1445000000
1859,us-gaap:UnrecognizedTaxBenefitsIncreasesResult...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1277000000
1865,us-gaap:UnrecognizedTaxBenefitsIncreasesResult...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,1086000000

,concept,entity,period,unit,value
1855,us-gaap:UnrecognizedTaxBenefitsIncreasesResult...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,151000000
1860,us-gaap:UnrecognizedTaxBenefitsIncreasesResult...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,397000000
1866,us-gaap:UnrecognizedTaxBenefitsIncreasesResult...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,115000000

,concept,entity,period,unit,value
1856,us-gaap:UnrecognizedTaxBenefitsDecreasesResult...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,1176000000
1861,us-gaap:UnrecognizedTaxBenefitsDecreasesResult...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,49000000
1867,us-gaap:UnrecognizedTaxBenefitsDecreasesResult...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,317000000

,concept,entity,period,unit,value
1857,us-gaap:UnrecognizedTaxBenefitsReductionsResul...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,3000000
1862,us-gaap:UnrecognizedTaxBenefitsReductionsResul...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,48000000
1868,us-gaap:UnrecognizedTaxBenefitsReductionsResul...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,118000000

,concept,entity,period,us-gaap:IncomeTaxAuthorityNameAxis,us-gaap:TaxPeriodAxis,value
1869,us-gaap:IncomeTaxExaminationYearUnderExamination,cik:0000789019,2011-01-01T00:00:00/2011-04-01T00:00:00,us-gaap:InternalRevenueServiceIRSMember,us-gaap:EarliestTaxYearMember,2004
1870,us-gaap:IncomeTaxExaminationYearUnderExamination,cik:0000789019,2011-01-01T00:00:00/2011-04-01T00:00:00,us-gaap:InternalRevenueServiceIRSMember,us-gaap:LatestTaxYearMember,2006
1871,us-gaap:IncomeTaxExaminationYearUnderExamination,cik:0000789019,2015-07-01T00:00:00/2015-10-01T00:00:00,us-gaap:InternalRevenueServiceIRSMember,us-gaap:EarliestTaxYearMember,2007
1872,us-gaap:IncomeTaxExaminationYearUnderExamination,cik:0000789019,2015-07-01T00:00:00/2015-10-01T00:00:00,us-gaap:InternalRevenueServiceIRSMember,us-gaap:LatestTaxYearMember,2009
1873,us-gaap:IncomeTaxExaminationYearUnderExamination,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,us-gaap:InternalRevenueServiceIRSMember,us-gaap:EarliestTaxYearMember,2010
1874,us-gaap:IncomeTaxExaminationYearUnderExamination,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,us-gaap:InternalRevenueServiceIRSMember,us-gaap:LatestTaxYearMember,2013

,concept,entity,period,us-gaap:IncomeTaxAuthorityNameAxis,us-gaap:TaxPeriodAxis,value,us-gaap:IncomeTaxAuthorityAxis
1875,us-gaap:OpenTaxYear,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:InternalRevenueServiceIRSMember,us-gaap:EarliestTaxYearMember,2010,NaN
1876,us-gaap:OpenTaxYear,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:InternalRevenueServiceIRSMember,us-gaap:LatestTaxYearMember,2017,NaN
1877,us-gaap:OpenTaxYear,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,us-gaap:EarliestTaxYearMember,1996,us-gaap:ForeignCountryMember
1878,us-gaap:OpenTaxYear,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,us-gaap:LatestTaxYearMember,2017,us-gaap:ForeignCountryMember

,concept,entity,period,us-gaap:RestructuringPlanAxis,unit,value
1879,us-gaap:RestructuringAndRelatedCostNumberOfPos...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:TwentySixteenRestructuringPlanMember,msft:Position,4700

,concept,entity,period,us-gaap:RestructuringPlanAxis,unit,value,us-gaap:RestructuringCostAndReserveAxis
1880,us-gaap:RestructuringCharges,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,msft:TwentySixteenRestructuringPlanMember,iso4217:USD,501000000,NaN
1882,us-gaap:RestructuringCharges,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:TwentySeventeenRestructuringPlanMember,iso4217:USD,306000000,us-gaap:EmployeeSeveranceMember
2305,us-gaap:RestructuringCharges,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,msft:SalesAndMarketingRestructuringPlanMember,iso4217:USD,306000000,us-gaap:EmployeeSeveranceMember

,concept,entity,period,us-gaap:RestructuringPlanAxis,value
1881,us-gaap:RestructuringAndRelatedActivitiesCompl...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:TwentySixteenRestructuringPlanMember,2017-06-30
1883,us-gaap:RestructuringAndRelatedActivitiesCompl...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:TwentySeventeenRestructuringPlanMember,2018-06-30

,concept,entity,period,unit,value
1892,msft:ContractWithCustomerLiabilityRevenueDeferred,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,61142000000

,concept,entity,period,unit,value
1893,us-gaap:ContractWithCustomerLiabilityRevenueRe...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,55078000000

,concept,entity,period,unit,value
1894,us-gaap:RevenueRemainingPerformanceObligation,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,73000000000

,concept,entity,period,us-gaap:RevenueRemainingPerformanceObligationExpectedTimingOfSatisfactionStartDateAxis,value
1895,us-gaap:RevenueRemainingPerformanceObligationP...,cik:0000789019,2018-07-01T00:00:00,2018-07-01,0.60

,concept,entity,period,us-gaap:RevenueRemainingPerformanceObligationExpectedTimingOfSatisfactionStartDateAxis,value
1896,us-gaap:RevenueRemainingPerformanceObligationE...,cik:0000789019,2018-07-01T00:00:00,2018-07-01,P12M

,concept,entity,period,srt:RangeAxis,value
1897,msft:LesseeOperatingAndFinanceLeasesRemainingL...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MinimumMember,P1Y
1898,msft:LesseeOperatingAndFinanceLeasesRemainingL...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MaximumMember,P20Y

,concept,entity,period,srt:RangeAxis,value
1899,us-gaap:LesseeOperatingLeaseRenewalTerm,cik:0000789019,2018-07-01T00:00:00,srt:MaximumMember,P5Y

,concept,entity,period,srt:RangeAxis,value
1900,us-gaap:LesseeFinanceLeaseRenewalTerm1,cik:0000789019,2018-07-01T00:00:00,srt:MaximumMember,P5Y

,concept,entity,period,srt:RangeAxis,value
1901,msft:LesseeOperatingAndFinanceLeasesOptionsToT...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MaximumMember,P1Y

,concept,entity,period,unit,value
1902,us-gaap:OperatingLeaseCost,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,1585000000
1903,us-gaap:OperatingLeaseCost,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1412000000
1904,us-gaap:OperatingLeaseCost,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,936000000

,concept,entity,period,unit,value
1905,us-gaap:FinanceLeaseRightOfUseAssetAmortization,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,243000000
1906,us-gaap:FinanceLeaseRightOfUseAssetAmortization,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,104000000
1907,us-gaap:FinanceLeaseRightOfUseAssetAmortization,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,28000000

,concept,entity,period,unit,value
1908,us-gaap:FinanceLeaseInterestExpense,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,175000000
1909,us-gaap:FinanceLeaseInterestExpense,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,68000000
1910,us-gaap:FinanceLeaseInterestExpense,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,28000000

,concept,entity,period,unit,value
1911,msft:FinanceLeaseCost,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,418000000
1912,msft:FinanceLeaseCost,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,172000000
1913,msft:FinanceLeaseCost,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,56000000

,concept,entity,period,unit,value
1914,us-gaap:OperatingLeasePayments,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,1522000000
1915,us-gaap:OperatingLeasePayments,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1157000000
1916,us-gaap:OperatingLeasePayments,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,936000000

,concept,entity,period,unit,value
1917,us-gaap:FinanceLeaseInterestPaymentOnLiability,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,175000000
1918,us-gaap:FinanceLeaseInterestPaymentOnLiability,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,68000000
1919,us-gaap:FinanceLeaseInterestPaymentOnLiability,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,28000000

,concept,entity,period,unit,value
1920,us-gaap:FinanceLeasePrincipalPayments,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,144000000
1921,us-gaap:FinanceLeasePrincipalPayments,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,46000000
1922,us-gaap:FinanceLeasePrincipalPayments,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,6000000

,concept,entity,period,unit,value
1923,us-gaap:RightOfUseAssetObtainedInExchangeForOp...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,1571000000
1924,us-gaap:RightOfUseAssetObtainedInExchangeForOp...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1270000000
1925,us-gaap:RightOfUseAssetObtainedInExchangeForOp...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,1062000000

,concept,entity,period,unit,value
1926,us-gaap:RightOfUseAssetObtainedInExchangeForFi...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,1933000000
1927,us-gaap:RightOfUseAssetObtainedInExchangeForFi...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1773000000
1928,us-gaap:RightOfUseAssetObtainedInExchangeForFi...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,413000000

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,unit,value
1929,us-gaap:OperatingLeaseLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,iso4217:USD,1399000000
1930,us-gaap:OperatingLeaseLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,iso4217:USD,1423000000
1931,us-gaap:OperatingLeaseLiability,cik:0000789019,2018-07-01T00:00:00,msft:OperatingLeaseLiabilitiesMember,iso4217:USD,5568000000
1932,us-gaap:OperatingLeaseLiability,cik:0000789019,2017-07-01T00:00:00,msft:OperatingLeaseLiabilitiesMember,iso4217:USD,5372000000
1933,us-gaap:OperatingLeaseLiability,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,6967000000
1934,us-gaap:OperatingLeaseLiability,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,6795000000

,concept,entity,period,us-gaap:BalanceSheetLocationAxis,unit,value
1941,us-gaap:FinanceLeaseLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,iso4217:USD,176000000
1942,us-gaap:FinanceLeaseLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherCurrentLiabilitiesMember,iso4217:USD,113000000
1943,us-gaap:FinanceLeaseLiability,cik:0000789019,2018-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,iso4217:USD,4125000000
1944,us-gaap:FinanceLeaseLiability,cik:0000789019,2017-07-01T00:00:00,us-gaap:OtherNoncurrentLiabilitiesMember,iso4217:USD,2425000000
1945,us-gaap:FinanceLeaseLiability,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,4301000000
1946,us-gaap:FinanceLeaseLiability,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,2538000000

,concept,entity,period,value
1947,us-gaap:OperatingLeaseWeightedAverageRemaining...,cik:0000789019,2018-07-01T00:00:00,P7Y
1948,us-gaap:OperatingLeaseWeightedAverageRemaining...,cik:0000789019,2017-07-01T00:00:00,P7Y

,concept,entity,period,value
1949,us-gaap:FinanceLeaseWeightedAverageRemainingLe...,cik:0000789019,2018-07-01T00:00:00,P13Y
1950,us-gaap:FinanceLeaseWeightedAverageRemainingLe...,cik:0000789019,2017-07-01T00:00:00,P13Y

,concept,entity,period,value
1951,us-gaap:OperatingLeaseWeightedAverageDiscountR...,cik:0000789019,2018-07-01T00:00:00,0.027
1952,us-gaap:OperatingLeaseWeightedAverageDiscountR...,cik:0000789019,2017-07-01T00:00:00,0.025

,concept,entity,period,value
1953,us-gaap:FinanceLeaseWeightedAverageDiscountRat...,cik:0000789019,2018-07-01T00:00:00,0.052
1954,us-gaap:FinanceLeaseWeightedAverageDiscountRat...,cik:0000789019,2017-07-01T00:00:00,0.047

,concept,entity,period,unit,value
1955,us-gaap:LesseeOperatingLeaseLiabilityPaymentsD...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1492000000

,concept,entity,period,unit,value
1956,us-gaap:LesseeOperatingLeaseLiabilityPaymentsD...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1347000000

,concept,entity,period,unit,value
1957,us-gaap:LesseeOperatingLeaseLiabilityPaymentsD...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1086000000

,concept,entity,period,unit,value
1958,us-gaap:LesseeOperatingLeaseLiabilityPaymentsD...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,902000000

,concept,entity,period,unit,value
1959,us-gaap:LesseeOperatingLeaseLiabilityPaymentsD...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,721000000

,concept,entity,period,unit,value
1960,us-gaap:LesseeOperatingLeaseLiabilityPaymentsD...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,2157000000

,concept,entity,period,unit,value
1961,us-gaap:LesseeOperatingLeaseLiabilityPaymentsDue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,7705000000

,concept,entity,period,unit,value
1962,us-gaap:LesseeOperatingLeaseLiabilityUndiscoun...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,738000000

,concept,entity,period,unit,value
1963,us-gaap:FinanceLeaseLiabilityPaymentsDueNextTw...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,386000000

,concept,entity,period,unit,value
1964,us-gaap:FinanceLeaseLiabilityPaymentsDueYearTwo,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,393000000

,concept,entity,period,unit,value
1965,us-gaap:FinanceLeaseLiabilityPaymentsDueYearThree,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,401000000

,concept,entity,period,unit,value
1966,us-gaap:FinanceLeaseLiabilityPaymentsDueYearFour,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,408000000

,concept,entity,period,unit,value
1967,us-gaap:FinanceLeaseLiabilityPaymentsDueYearFive,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,410000000

,concept,entity,period,unit,value
1968,us-gaap:FinanceLeaseLiabilityPaymentsDueAfterY...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,4036000000

,concept,entity,period,unit,value
1969,us-gaap:FinanceLeaseLiabilityPaymentsDue,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,6034000000

,concept,entity,period,unit,value
1970,us-gaap:FinanceLeaseLiabilityUndiscountedExces...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1733000000

,concept,entity,period,us-gaap:LeaseArrangementTypeAxis,unit,value
1971,us-gaap:UnrecordedUnconditionalPurchaseObligat...,cik:0000789019,2018-07-01T00:00:00,msft:OperatingLeaseMember,iso4217:USD,594000000
1972,us-gaap:UnrecordedUnconditionalPurchaseObligat...,cik:0000789019,2018-07-01T00:00:00,msft:FinanceLeaseMember,iso4217:USD,2400000000

,concept,entity,period,srt:RangeAxis,value
1973,us-gaap:LesseeOperatingLeaseLeaseNotYetCommenc...,cik:0000789019,2018-07-01T00:00:00,srt:MinimumMember,P1Y
1974,us-gaap:LesseeOperatingLeaseLeaseNotYetCommenc...,cik:0000789019,2018-07-01T00:00:00,srt:MaximumMember,P20Y

,concept,entity,period,srt:RangeAxis,value
1975,us-gaap:LesseeFinanceLeaseLeaseNotYetCommenced...,cik:0000789019,2018-07-01T00:00:00,srt:MinimumMember,P1Y
1976,us-gaap:LesseeFinanceLeaseLeaseNotYetCommenced...,cik:0000789019,2018-07-01T00:00:00,srt:MaximumMember,P20Y

,concept,entity,period,unit,value
1977,us-gaap:LossContingencyAccrualCarryingValueCur...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,323000000

,concept,entity,period,unit,value
1978,us-gaap:LossContingencyRangeOfPossibleLossPort...,cik:0000789019,2018-07-01T00:00:00,iso4217:USD,1100000000

,concept,entity,period,unit,value
1981,us-gaap:StockIssuedDuringPeriodSharesNewIssues,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,xbrli:shares,68000000
1982,us-gaap:StockIssuedDuringPeriodSharesNewIssues,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,xbrli:shares,70000000
1983,us-gaap:StockIssuedDuringPeriodSharesNewIssues,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,xbrli:shares,75000000

,concept,entity,period,unit,value,us-gaap:ShareRepurchaseProgramAxis
1984,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,xbrli:shares,99000000,NaN
1985,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,xbrli:shares,170000000,NaN
1986,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,xbrli:shares,294000000,NaN
1990,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2017-07-01T00:00:00/2017-10-01T00:00:00,xbrli:shares,22000000,msft:ShareRepurchaseProgramTwentySixteenMember
1991,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,xbrli:shares,22000000,msft:ShareRepurchaseProgramTwentySixteenMember
1992,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2018-01-01T00:00:00/2018-04-01T00:00:00,xbrli:shares,34000000,msft:ShareRepurchaseProgramTwentySixteenMember
1993,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,xbrli:shares,21000000,msft:ShareRepurchaseProgramTwentySixteenMember
1999,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2016-07-02T00:00:00/2016-10-01T00:00:00,xbrli:shares,63000000,msft:ShareRepurchaseProgramTwentyThirteenMember
2000,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2016-10-01T00:00:00/2017-01-01T00:00:00,xbrli:shares,59000000,msft:ShareRepurchaseProgramTwentyThirteenMember
2001,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2017-01-01T00:00:00/2017-04-01T00:00:00,xbrli:shares,25000000,msft:ShareRepurchaseProgramTwentySixteenMember
2002,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,xbrli:shares,23000000,msft:ShareRepurchaseProgramTwentySixteenMember
2008,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2015-07-01T00:00:00/2015-10-01T00:00:00,xbrli:shares,89000000,msft:ShareRepurchaseProgramTwentyThirteenMember
2009,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2015-10-01T00:00:00/2016-01-01T00:00:00,xbrli:shares,66000000,msft:ShareRepurchaseProgramTwentyThirteenMember
2010,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2016-01-01T00:00:00/2016-04-01T00:00:00,xbrli:shares,69000000,msft:ShareRepurchaseProgramTwentyThirteenMember
2011,us-gaap:StockRepurchasedDuringPeriodShares,cik:0000789019,2016-04-01T00:00:00/2016-07-01T00:00:00,xbrli:shares,70000000,msft:ShareRepurchaseProgramTwentyThirteenMember

,concept,entity,period,us-gaap:ShareRepurchaseProgramAxis,unit,value
1987,us-gaap:StockRepurchaseProgramAuthorizedAmount1,cik:0000789019,2013-09-17T00:00:00,msft:ShareRepurchaseProgramTwentyThirteenMember,iso4217:USD,40000000000
1988,us-gaap:StockRepurchaseProgramAuthorizedAmount1,cik:0000789019,2016-09-21T00:00:00,msft:ShareRepurchaseProgramTwentySixteenMember,iso4217:USD,40000000000

,concept,entity,period,us-gaap:ShareRepurchaseProgramAxis,unit,value
1989,us-gaap:StockRepurchaseProgramRemainingAuthori...,cik:0000789019,2018-07-01T00:00:00,msft:ShareRepurchaseProgramTwentySixteenMember,iso4217:USD,28200000000

,concept,entity,period,value
2017,us-gaap:DividendsPayableDateDeclaredDayMonthAn...,cik:0000789019,2017-07-01T00:00:00/2017-10-01T00:00:00,2017-09-19
2018,us-gaap:DividendsPayableDateDeclaredDayMonthAn...,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,2017-11-29
2019,us-gaap:DividendsPayableDateDeclaredDayMonthAn...,cik:0000789019,2018-01-01T00:00:00/2018-04-01T00:00:00,2018-03-12
2020,us-gaap:DividendsPayableDateDeclaredDayMonthAn...,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,2018-06-13
2021,us-gaap:DividendsPayableDateDeclaredDayMonthAn...,cik:0000789019,2016-07-02T00:00:00/2016-10-01T00:00:00,2016-09-20
2022,us-gaap:DividendsPayableDateDeclaredDayMonthAn...,cik:0000789019,2016-10-01T00:00:00/2017-01-01T00:00:00,2016-11-30
2023,us-gaap:DividendsPayableDateDeclaredDayMonthAn...,cik:0000789019,2017-01-01T00:00:00/2017-04-01T00:00:00,2017-03-14
2024,us-gaap:DividendsPayableDateDeclaredDayMonthAn...,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,2017-06-13

,concept,entity,period,value
2033,us-gaap:DividendsPayableDateOfRecordDayMonthAn...,cik:0000789019,2017-07-01T00:00:00/2017-10-01T00:00:00,2017-11-16
2034,us-gaap:DividendsPayableDateOfRecordDayMonthAn...,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,2018-02-15
2035,us-gaap:DividendsPayableDateOfRecordDayMonthAn...,cik:0000789019,2018-01-01T00:00:00/2018-04-01T00:00:00,2018-05-17
2036,us-gaap:DividendsPayableDateOfRecordDayMonthAn...,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,2018-08-16
2037,us-gaap:DividendsPayableDateOfRecordDayMonthAn...,cik:0000789019,2016-07-02T00:00:00/2016-10-01T00:00:00,2016-11-17
2038,us-gaap:DividendsPayableDateOfRecordDayMonthAn...,cik:0000789019,2016-10-01T00:00:00/2017-01-01T00:00:00,2017-02-16
2039,us-gaap:DividendsPayableDateOfRecordDayMonthAn...,cik:0000789019,2017-01-01T00:00:00/2017-04-01T00:00:00,2017-05-18
2040,us-gaap:DividendsPayableDateOfRecordDayMonthAn...,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,2017-08-17

,concept,entity,period,value
2049,us-gaap:DividendPayableDateToBePaidDayMonthAnd...,cik:0000789019,2017-07-01T00:00:00/2017-10-01T00:00:00,2017-12-14
2050,us-gaap:DividendPayableDateToBePaidDayMonthAnd...,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,2018-03-08
2051,us-gaap:DividendPayableDateToBePaidDayMonthAnd...,cik:0000789019,2018-01-01T00:00:00/2018-04-01T00:00:00,2018-06-14
2052,us-gaap:DividendPayableDateToBePaidDayMonthAnd...,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,2018-09-13
2053,us-gaap:DividendPayableDateToBePaidDayMonthAnd...,cik:0000789019,2016-07-02T00:00:00/2016-10-01T00:00:00,2016-12-08
2054,us-gaap:DividendPayableDateToBePaidDayMonthAnd...,cik:0000789019,2016-10-01T00:00:00/2017-01-01T00:00:00,2017-03-09
2055,us-gaap:DividendPayableDateToBePaidDayMonthAnd...,cik:0000789019,2017-01-01T00:00:00/2017-04-01T00:00:00,2017-06-08
2056,us-gaap:DividendPayableDateToBePaidDayMonthAnd...,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,2017-09-14

,concept,entity,period,us-gaap:StatementEquityComponentsAxis,unit,value
2060,us-gaap:OciBeforeReclassificationsNetOfTaxAttr...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,218000000
2061,us-gaap:OciBeforeReclassificationsNetOfTaxAttr...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,328000000
2062,us-gaap:OciBeforeReclassificationsNetOfTaxAttr...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,351000000
2079,us-gaap:OciBeforeReclassificationsNetOfTaxAttr...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,-1146000000
2080,us-gaap:OciBeforeReclassificationsNetOfTaxAttr...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,517000000
2081,us-gaap:OciBeforeReclassificationsNetOfTaxAttr...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,219000000

,concept,entity,period,us-gaap:IncomeStatementLocationAxis,us-gaap:StatementEquityComponentsAxis,unit,value
2063,us-gaap:ReclassificationFromAociCurrentPeriodB...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:SalesMember,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,185000000
2064,us-gaap:ReclassificationFromAociCurrentPeriodB...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:SalesMember,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,555000000
2065,us-gaap:ReclassificationFromAociCurrentPeriodB...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:SalesMember,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,625000000
2082,us-gaap:ReclassificationFromAociCurrentPeriodB...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:NonoperatingIncomeExpenseMember,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,2309000000
2083,us-gaap:ReclassificationFromAociCurrentPeriodB...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:NonoperatingIncomeExpenseMember,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,2513000000
2084,us-gaap:ReclassificationFromAociCurrentPeriodB...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:NonoperatingIncomeExpenseMember,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,688000000

,concept,entity,period,us-gaap:StatementEquityComponentsAxis,unit,value
2066,us-gaap:ReclassificationFromAociCurrentPeriodTax,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,6000000
2067,us-gaap:ReclassificationFromAociCurrentPeriodTax,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,9000000
2068,us-gaap:ReclassificationFromAociCurrentPeriodTax,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,36000000
2085,us-gaap:ReclassificationFromAociCurrentPeriodTax,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,738000000
2086,us-gaap:ReclassificationFromAociCurrentPeriodTax,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,880000000
2087,us-gaap:ReclassificationFromAociCurrentPeriodTax,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,241000000

,concept,entity,period,us-gaap:StatementEquityComponentsAxis,unit,value
2069,us-gaap:ReclassificationFromAociCurrentPeriodN...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,179000000
2070,us-gaap:ReclassificationFromAociCurrentPeriodN...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,546000000
2071,us-gaap:ReclassificationFromAociCurrentPeriodN...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,589000000
2088,us-gaap:ReclassificationFromAociCurrentPeriodN...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,1571000000
2089,us-gaap:ReclassificationFromAociCurrentPeriodN...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,1633000000
2090,us-gaap:ReclassificationFromAociCurrentPeriodN...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,447000000

,concept,entity,period,us-gaap:StatementEquityComponentsAxis,unit,value
2102,us-gaap:OtherComprehensiveIncomeLossBeforeRecl...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,11000000
2103,us-gaap:OtherComprehensiveIncomeLossBeforeRecl...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,4000000
2104,us-gaap:OtherComprehensiveIncomeLossBeforeRecl...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,24000000
2105,us-gaap:OtherComprehensiveIncomeLossBeforeRecl...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,-427000000
2106,us-gaap:OtherComprehensiveIncomeLossBeforeRecl...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,267000000
2107,us-gaap:OtherComprehensiveIncomeLossBeforeRecl...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,120000000

,concept,entity,period,us-gaap:StatementEquityComponentsAxis,unit,value
2108,us-gaap:OtherComprehensiveIncomeLossTaxPortion...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,5000000
2109,us-gaap:OtherComprehensiveIncomeLossTaxPortion...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,-5000000
2110,us-gaap:OtherComprehensiveIncomeLossTaxPortion...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:AccumulatedNetGainLossFromDesignatedOr...,iso4217:USD,-12000000
2111,us-gaap:OtherComprehensiveIncomeLossTaxPortion...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,-1165000000
2112,us-gaap:OtherComprehensiveIncomeLossTaxPortion...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,-613000000
2113,us-gaap:OtherComprehensiveIncomeLossTaxPortion...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,msft:AccumulatedNetUnrealizedGainLossOnInvestm...,iso4217:USD,-121000000
2114,us-gaap:OtherComprehensiveIncomeLossTaxPortion...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:AccumulatedTranslationAdjustmentAndOtherM...,iso4217:USD,0
2115,us-gaap:OtherComprehensiveIncomeLossTaxPortion...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,msft:AccumulatedTranslationAdjustmentAndOtherM...,iso4217:USD,9000000
2116,us-gaap:OtherComprehensiveIncomeLossTaxPortion...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,msft:AccumulatedTranslationAdjustmentAndOtherM...,iso4217:USD,-33000000

,concept,entity,period,us-gaap:AwardTypeAxis,unit,value,us-gaap:PlanNameAxis
2117,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2018-07-01T00:00:00,us-gaap:RestrictedStockMember,xbrli:shares,381000000,NaN
2118,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2018-07-01T00:00:00,us-gaap:RestrictedStockMember,xbrli:shares,308000000,msft:TwentySeventeenStockPlanMember
2173,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2018-07-01T00:00:00,us-gaap:EmployeeStockMember,xbrli:shares,116000000,NaN

,concept,entity,period,unit,value
2119,us-gaap:AllocatedShareBasedCompensationExpense,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,3940000000
2120,us-gaap:AllocatedShareBasedCompensationExpense,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,3266000000
2121,us-gaap:AllocatedShareBasedCompensationExpense,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,2668000000

,concept,entity,period,unit,value
2122,us-gaap:EmployeeServiceShareBasedCompensationT...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,823000000
2123,us-gaap:EmployeeServiceShareBasedCompensationT...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,1066000000
2124,us-gaap:EmployeeServiceShareBasedCompensationT...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,882000000

,concept,entity,period,srt:RangeAxis,us-gaap:AwardTypeAxis,value,us-gaap:PlanNameAxis
2125,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MinimumMember,us-gaap:RestrictedStockMember,P4Y,NaN
2126,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MaximumMember,us-gaap:RestrictedStockMember,P5Y,NaN
2127,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,us-gaap:RestrictedStockUnitsRSUMember,P4Y,msft:ExecutiveIncentivePlanMember
2128,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,NaN,us-gaap:PerformanceSharesMember,P3Y,msft:ExecutiveIncentivePlanMember

,concept,entity,period,srt:RangeAxis,unit,value
2129,msft:ShareBasedCompensationArrangementByShareB...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MinimumMember,iso4217:USD/xbrli:shares,0.39
2130,msft:ShareBasedCompensationArrangementByShareB...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,srt:MinimumMember,iso4217:USD/xbrli:shares,0.36
2131,msft:ShareBasedCompensationArrangementByShareB...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,srt:MinimumMember,iso4217:USD/xbrli:shares,0.31
2132,msft:ShareBasedCompensationArrangementByShareB...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MaximumMember,iso4217:USD/xbrli:shares,0.42
2133,msft:ShareBasedCompensationArrangementByShareB...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,srt:MaximumMember,iso4217:USD/xbrli:shares,0.39
2134,msft:ShareBasedCompensationArrangementByShareB...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,srt:MaximumMember,iso4217:USD/xbrli:shares,0.36

,concept,entity,period,value
2135,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,0.017
2136,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,0.012
2137,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,0.011

,concept,entity,period,value
2138,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,0.029
2139,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,0.022
2140,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,0.018

,concept,entity,period,us-gaap:AwardTypeAxis,unit,value
2141,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00,us-gaap:RestrictedStockMember,xbrli:shares,201000000
2145,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2018-07-01T00:00:00,us-gaap:RestrictedStockMember,xbrli:shares,174000000

,concept,entity,period,us-gaap:AwardTypeAxis,unit,value
2142,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:RestrictedStockMember,xbrli:shares,70000000
2151,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:PerformanceSharesMember,xbrli:shares,3000000
2152,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:PerformanceSharesMember,xbrli:shares,2000000
2153,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:PerformanceSharesMember,xbrli:shares,1000000

,concept,entity,period,us-gaap:AwardTypeAxis,unit,value
2143,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:RestrictedStockMember,xbrli:shares,80000000

,concept,entity,period,us-gaap:AwardTypeAxis,unit,value
2144,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:RestrictedStockMember,xbrli:shares,17000000

,concept,entity,period,us-gaap:AwardTypeAxis,unit,value
2146,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00,us-gaap:RestrictedStockMember,iso4217:USD/xbrli:shares,46.32
2150,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2018-07-01T00:00:00,us-gaap:RestrictedStockMember,iso4217:USD/xbrli:shares,57.85

,concept,entity,period,us-gaap:AwardTypeAxis,unit,value
2147,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:RestrictedStockMember,iso4217:USD/xbrli:shares,75.88
2156,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:RestrictedStockMember,iso4217:USD/xbrli:shares,55.64
2157,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:RestrictedStockMember,iso4217:USD/xbrli:shares,41.51

,concept,entity,period,us-gaap:AwardTypeAxis,unit,value
2148,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:RestrictedStockMember,iso4217:USD/xbrli:shares,45.74

,concept,entity,period,us-gaap:AwardTypeAxis,unit,value
2149,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:RestrictedStockMember,iso4217:USD/xbrli:shares,53.41

,concept,entity,period,us-gaap:AwardTypeAxis,unit,value
2154,us-gaap:EmployeeServiceShareBasedCompensationN...,cik:0000789019,2018-07-01T00:00:00,us-gaap:RestrictedStockMember,iso4217:USD,7000000000

,concept,entity,period,us-gaap:AwardTypeAxis,value
2155,us-gaap:EmployeeServiceShareBasedCompensationN...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:RestrictedStockMember,P3Y

,concept,entity,period,us-gaap:AwardTypeAxis,unit,value
2158,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:RestrictedStockMember,iso4217:USD,6600000000
2159,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:RestrictedStockMember,iso4217:USD,4800000000
2160,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:RestrictedStockMember,iso4217:USD,3900000000

,concept,entity,period,us-gaap:AwardTypeAxis,value
2161,us-gaap:SharebasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,us-gaap:EmployeeStockMember,0.90
2162,us-gaap:SharebasedCompensationArrangementBySha...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,us-gaap:EmployeeStockMember,0.90
2163,us-gaap:SharebasedCompensationArrangementBySha...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,us-gaap:EmployeeStockMember,0.90

,concept,entity,period,us-gaap:AwardTypeAxis,value
2164,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2018-07-01T00:00:00,us-gaap:EmployeeStockMember,0.15
2165,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2017-07-01T00:00:00,us-gaap:EmployeeStockMember,0.15
2166,us-gaap:ShareBasedCompensationArrangementBySha...,cik:0000789019,2016-07-01T00:00:00,us-gaap:EmployeeStockMember,0.15

,concept,entity,period,unit,value
2167,us-gaap:StockIssuedDuringPeriodSharesEmployeeS...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,xbrli:shares,13000000
2168,us-gaap:StockIssuedDuringPeriodSharesEmployeeS...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,xbrli:shares,13000000
2169,us-gaap:StockIssuedDuringPeriodSharesEmployeeS...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,xbrli:shares,15000000

,concept,entity,period,unit,value
2170,msft:StockIssuedEmployeeStockPurchasePlanAvera...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD/xbrli:shares,76.40
2171,msft:StockIssuedEmployeeStockPurchasePlanAvera...,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD/xbrli:shares,56.36
2172,msft:StockIssuedEmployeeStockPurchasePlanAvera...,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD/xbrli:shares,44.83

,concept,entity,period,value
2174,us-gaap:DefinedContributionPlanEmployerMatchin...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,0.50

,concept,entity,period,srt:RangeAxis,us-gaap:DeferredCompensationArrangementWithIndividualPostretirementBenefitsByTypeOfDeferredCompensationAxis,value
2175,us-gaap:DefinedContributionPlanEmployerMatchin...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,srt:MaximumMember,msft:IRSCompensationLimitMember,0.50

,concept,entity,period,unit,value
2176,us-gaap:DefinedContributionPlanCostRecognized,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,iso4217:USD,807000000
2177,us-gaap:DefinedContributionPlanCostRecognized,cik:0000789019,2016-07-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,734000000
2178,us-gaap:DefinedContributionPlanCostRecognized,cik:0000789019,2015-07-01T00:00:00/2016-07-01T00:00:00,iso4217:USD,549000000

,concept,entity,period,value
2200,us-gaap:SegmentReportingDisclosureOfMajorCusto...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,No sales to an individual cust

,concept,entity,period,srt:StatementGeographicalAxis,unit,value
2237,us-gaap:NoncurrentAssets,cik:0000789019,2018-07-01T00:00:00,country:US,iso4217:USD,44501000000
2238,us-gaap:NoncurrentAssets,cik:0000789019,2017-07-01T00:00:00,country:US,iso4217:USD,42730000000
2239,us-gaap:NoncurrentAssets,cik:0000789019,2016-07-01T00:00:00,country:US,iso4217:USD,25145000000
2240,us-gaap:NoncurrentAssets,cik:0000789019,2018-07-01T00:00:00,country:IE,iso4217:USD,12843000000
2241,us-gaap:NoncurrentAssets,cik:0000789019,2017-07-01T00:00:00,country:IE,iso4217:USD,12889000000
2242,us-gaap:NoncurrentAssets,cik:0000789019,2016-07-01T00:00:00,country:IE,iso4217:USD,2099000000
2243,us-gaap:NoncurrentAssets,cik:0000789019,2018-07-01T00:00:00,country:LU,iso4217:USD,6856000000
2244,us-gaap:NoncurrentAssets,cik:0000789019,2017-07-01T00:00:00,country:LU,iso4217:USD,6854000000
2245,us-gaap:NoncurrentAssets,cik:0000789019,2016-07-01T00:00:00,country:LU,iso4217:USD,6868000000
2246,us-gaap:NoncurrentAssets,cik:0000789019,2018-07-01T00:00:00,msft:OtherCountriesMember,iso4217:USD,15682000000
2247,us-gaap:NoncurrentAssets,cik:0000789019,2017-07-01T00:00:00,msft:OtherCountriesMember,iso4217:USD,13044000000
2248,us-gaap:NoncurrentAssets,cik:0000789019,2016-07-01T00:00:00,msft:OtherCountriesMember,iso4217:USD,11047000000
2249,us-gaap:NoncurrentAssets,cik:0000789019,2018-07-01T00:00:00,NaN,iso4217:USD,79882000000
2250,us-gaap:NoncurrentAssets,cik:0000789019,2017-07-01T00:00:00,NaN,iso4217:USD,75517000000
2251,us-gaap:NoncurrentAssets,cik:0000789019,2016-07-01T00:00:00,NaN,iso4217:USD,45159000000

,concept,entity,period,us-gaap:IncomeTaxAuthorityAxis,unit,value
2302,msft:IncomeTaxExpenseBenefitEffectOnEarningsPe...,cik:0000789019,2017-10-01T00:00:00/2018-01-01T00:00:00,msft:TaxCutsAndJobsActMember,iso4217:USD/xbrli:shares,1.78
2303,msft:IncomeTaxExpenseBenefitEffectOnEarningsPe...,cik:0000789019,2018-04-01T00:00:00/2018-07-01T00:00:00,msft:TaxCutsAndJobsActMember,iso4217:USD/xbrli:shares,-0.01
2304,msft:IncomeTaxExpenseBenefitEffectOnEarningsPe...,cik:0000789019,2017-07-01T00:00:00/2018-07-01T00:00:00,msft:TaxCutsAndJobsActMember,iso4217:USD/xbrli:shares,1.75

,concept,entity,period,unit,value
2306,msft:RestructuringEffectOnOperatingIncomeLossA...,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,306000000

,concept,entity,period,unit,value
2307,msft:RestructuringEffectOnEarningsAfterTax,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,iso4217:USD,243000000

,concept,entity,period,unit,value
2308,msft:RestructuringEffectOnEarningsPerShareAfte...,cik:0000789019,2017-04-01T00:00:00/2017-07-01T00:00:00,iso4217:USD/xbrli:shares,0.04

        concept  noteId language                           value
2309  xbrl:note  f36008    en-us  Reflects the net charge (benef
2310  xbrl:note  f35991    en-us  On December 8, 2016, we acquir
2311  xbrl:note  f36063    en-us  Goodwill was assigned to our P
2312  xbrl:note  f36066    en-us  Convertible senior notes issue
2313  xbrl:note  f36014    en-us  These amounts represent the im
2314  xbrl:note  f36069    en-us  Includes goodwill related to L
2315  xbrl:note  f36126    en-us  Includes billings to OEMs and
2316  xbrl:note  f36072    en-us  Euro-denominated debt securiti
2317  xbrl:note  f36121    en-us  Includes 3 million, 2 million,
2318  xbrl:note  f35997    en-us  Includes $306 million of emplo
2319  xbrl:note  f36000    en-us  Reflects the net charge (benef

In [14]:
for (lConcept, lDF) in lDataFrameByConcept.items():
    if(lDF.shape[0] > 5):
        print("###### Concept info " + lConcept + " " + str(lDF.shape) + " ####################")
        print(lConcept, lDF.columns)
        for col in lDF.columns:
            print((lConcept , col, lDF[col].value_counts().to_dict()))

###### Concept info us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax (66, 11) ####################
us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax Index(['concept', 'entity', 'period', 'srt:ProductOrServiceAxis', 'unit',
       'value', 'srt:RestatementAxis',
       'us-gaap:AdjustmentsForNewAccountingPronouncementsAxis',
       'us-gaap:StatementBusinessSegmentsAxis',
       'srt:StatementGeographicalAxis',
       'msft:ProductsOrServicesSecondaryCategorizationAxis'],
      dtype='object')
('us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax', 'concept', {'us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax': 66})
('us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax', 'entity', {'cik:0000789019': 66})
('us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax', 'period', {'2016-07-01T00:00:00/2017-07-01T00:00:00': 20, '2015-07-01T00:00:00/2016-07-01T00:00:00': 20, '2017-07-01T00:00:00/2018-07-01T00:00:00': 18, '2017-07-01T00:00:00/2017-10-01T00:00:00': 1, '2017-10-01T00:00:00/2018-01-01T00:00:00': 1, '2018-01-01T00:00:00/2018-04-01T00:00:00': 1, '2018-04-01T00:00:00/2018-07-01T00:00:00': 1, '2016-07-02T00:00:00/2016-10-01T00:00:00': 1, '2016-10-01T00:00:00/2017-01-01T00:00:00': 1, '2017-01-01T00:00:00/2017-04-01T00:00:00': 1, '2017-04-01T00:00:00/2017-07-01T00:00:00': 1})
('us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax', 'srt:ProductOrServiceAxis', {'us-gaap:ProductMember': 3, 'us-gaap:ServiceOtherMember': 3, 'msft:OfficeProductsAndCloudServicesMember': 3, 'msft:ServerProductsAndCloudServicesMember': 3, 'msft:WindowsMember': 3, 'msft:GamingMember': 3, 'msft:SearchAdvertisingMember': 3, 'msft:EnterpriseServicesMember': 3, 'msft:DevicesMember': 3, 'msft:LinkedInCorporationMember': 3, 'msft:OtherProductsAndServicesMember': 3})
('us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax', 'unit', {'iso4217:USD': 66})
('us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax', 'value', {'64497000000': 1, '5259000000': 1, '18593000000': 1, '17548000000': 1, '10353000000': 1, '9051000000': 1, '9202000000': 1, '7012000000': 1, '6219000000': 1, '5428000000': 1, '5846000000': 1, '5542000000': 1, '5659000000': 1, '5134000000': 1, '5062000000': 1, '7888000000': 1, '2271000000': 1, '63811000000': 1, '0': 1, '2793000000': 1, '2611000000': 1, '2499000000': 1, '23200000000': 1, '14900000000': 1, '9500000000': 1, '24538000000': 1, '28918000000': 1, '26819000000': 1, '30085000000': 1, '21928000000': 1, '25826000000': 1, '23212000000': 1, '19518000000': 1, '19062000000': 1, '21649000000': 1, '26129000000': 1, '67336000000': 1, '45863000000': 1, '32760000000': 1, '23818000000': 1, '110360000000': 1, '96571000000': 1, '91154000000': 1, '89950000000': 1, '6621000000': 1, '85320000000': 1, '5834000000': 1, '35865000000': 1, '29870000000': 1, '25792000000': 1, '32219000000': 1, '27407000000': 1, '24952000000': 1, '42276000000': 1, '39294000000': 1, '40410000000': 1, '55926000000': 1, '51078000000': 1, '46416000000': 1, '54434000000': 1, '45493000000': 1, '44738000000': 1, '28316000000': 1, '25573000000': 1, '23868000000': 1, '25605000000': 1})
('us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax', 'srt:RestatementAxis', {'srt:ScenarioPreviouslyReportedMember': 2, 'srt:RestatementAdjustmentMember': 2})
('us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax', 'us-gaap:AdjustmentsForNewAccountingPronouncementsAxis', {'us-gaap:AccountingStandardsUpdate201409Member': 2})
('us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax', 'us-gaap:StatementBusinessSegmentsAxis', {'msft:ProductivityAndBusinessProcessesMember': 3, 'msft:IntelligentCloudMember': 3, 'msft:MorePersonalComputingMember': 3})
('us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax', 'srt:StatementGeographicalAxis', {'country:US': 3, 'us-gaap:NonUsMember': 3})
('us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax', 'msft:ProductsOrServicesSecondaryCategorizationAxis', {'msft:CommercialCloudMember': 3})
###### Concept info us-gaap:CostOfGoodsAndServicesSold (9, 6) ####################
us-gaap:CostOfGoodsAndServicesSold Index(['concept', 'entity', 'period', 'srt:ProductOrServiceAxis', 'unit',
       'value'],
      dtype='object')
('us-gaap:CostOfGoodsAndServicesSold', 'concept', {'us-gaap:CostOfGoodsAndServicesSold': 9})
('us-gaap:CostOfGoodsAndServicesSold', 'entity', {'cik:0000789019': 9})
('us-gaap:CostOfGoodsAndServicesSold', 'period', {'2017-07-01T00:00:00/2018-07-01T00:00:00': 3, '2016-07-01T00:00:00/2017-07-01T00:00:00': 3, '2015-07-01T00:00:00/2016-07-01T00:00:00': 3})
('us-gaap:CostOfGoodsAndServicesSold', 'srt:ProductOrServiceAxis', {'us-gaap:ProductMember': 3, 'us-gaap:ServiceOtherMember': 3})
('us-gaap:CostOfGoodsAndServicesSold', 'unit', {'iso4217:USD': 9})
('us-gaap:CostOfGoodsAndServicesSold', 'value', {'15420000000': 1, '15175000000': 1, '17880000000': 1, '22933000000': 1, '19086000000': 1, '14900000000': 1, '38353000000': 1, '34261000000': 1, '32780000000': 1})
###### Concept info us-gaap:GrossProfit (11, 5) ####################
us-gaap:GrossProfit Index(['concept', 'entity', 'period', 'unit', 'value'], dtype='object')
('us-gaap:GrossProfit', 'concept', {'us-gaap:GrossProfit': 11})
('us-gaap:GrossProfit', 'entity', {'cik:0000789019': 11})
('us-gaap:GrossProfit', 'period', {'2017-07-01T00:00:00/2018-07-01T00:00:00': 1, '2016-07-01T00:00:00/2017-07-01T00:00:00': 1, '2015-07-01T00:00:00/2016-07-01T00:00:00': 1, '2017-07-01T00:00:00/2017-10-01T00:00:00': 1, '2017-10-01T00:00:00/2018-01-01T00:00:00': 1, '2018-01-01T00:00:00/2018-04-01T00:00:00': 1, '2018-04-01T00:00:00/2018-07-01T00:00:00': 1, '2016-07-02T00:00:00/2016-10-01T00:00:00': 1, '2016-10-01T00:00:00/2017-01-01T00:00:00': 1, '2017-01-01T00:00:00/2017-04-01T00:00:00': 1, '2017-04-01T00:00:00/2017-07-01T00:00:00': 1})
('us-gaap:GrossProfit', 'unit', {'iso4217:USD': 11})
('us-gaap:GrossProfit', 'value', {'72007000000': 1, '62310000000': 1, '58374000000': 1, '16260000000': 1, '17854000000': 1, '17550000000': 1, '20343000000': 1, '14084000000': 1, '15925000000': 1, '15152000000': 1, '17149000000': 1})
###### Concept info us-gaap:OperatingIncomeLoss (23, 7) ####################
us-gaap:OperatingIncomeLoss Index(['concept', 'entity', 'period', 'unit', 'value',
       'srt:ConsolidationItemsAxis', 'us-gaap:StatementBusinessSegmentsAxis'],
      dtype='object')
('us-gaap:OperatingIncomeLoss', 'concept', {'us-gaap:OperatingIncomeLoss': 23})
('us-gaap:OperatingIncomeLoss', 'entity', {'cik:0000789019': 23})
('us-gaap:OperatingIncomeLoss', 'period', {'2017-07-01T00:00:00/2018-07-01T00:00:00': 5, '2016-07-01T00:00:00/2017-07-01T00:00:00': 5, '2015-07-01T00:00:00/2016-07-01T00:00:00': 5, '2017-07-01T00:00:00/2017-10-01T00:00:00': 1, '2017-10-01T00:00:00/2018-01-01T00:00:00': 1, '2018-01-01T00:00:00/2018-04-01T00:00:00': 1, '2018-04-01T00:00:00/2018-07-01T00:00:00': 1, '2016-07-02T00:00:00/2016-10-01T00:00:00': 1, '2016-10-01T00:00:00/2017-01-01T00:00:00': 1, '2017-01-01T00:00:00/2017-04-01T00:00:00': 1, '2017-04-01T00:00:00/2017-07-01T00:00:00': 1})
('us-gaap:OperatingIncomeLoss', 'unit', {'iso4217:USD': 23})
('us-gaap:OperatingIncomeLoss', 'value', {'35058000000': 1, '0': 1, '6723000000': 1, '7905000000': 1, '6715000000': 1, '10379000000': 1, '8292000000': 1, '8679000000': 1, '7708000000': 1, '-1110000000': 1, '-306000000': 1, '6183000000': 1, '29025000000': 1, '8815000000': 1, '10610000000': 1, '9249000000': 1, '9127000000': 1, '11524000000': 1, '11756000000': 1, '11389000000': 1, '12924000000': 1, '26078000000': 1, '7682000000': 1})
('us-gaap:OperatingIncomeLoss', 'srt:ConsolidationItemsAxis', {'us-gaap:OperatingSegmentsMember': 9, 'msft:CorporateAndReconcilingItemsMember': 3})
('us-gaap:OperatingIncomeLoss', 'us-gaap:StatementBusinessSegmentsAxis', {'msft:ProductivityAndBusinessProcessesMember': 3, 'msft:IntelligentCloudMember': 3, 'msft:MorePersonalComputingMember': 3})
###### Concept info us-gaap:IncomeTaxExpenseBenefit (10, 8) ####################
us-gaap:IncomeTaxExpenseBenefit Index(['concept', 'entity', 'period', 'unit', 'value', 'srt:RestatementAxis',
       'us-gaap:AdjustmentsForNewAccountingPronouncementsAxis',
       'us-gaap:IncomeTaxAuthorityAxis'],
      dtype='object')
('us-gaap:IncomeTaxExpenseBenefit', 'concept', {'us-gaap:IncomeTaxExpenseBenefit': 10})
('us-gaap:IncomeTaxExpenseBenefit', 'entity', {'cik:0000789019': 10})
('us-gaap:IncomeTaxExpenseBenefit', 'period', {'2016-07-01T00:00:00/2017-07-01T00:00:00': 3, '2015-07-01T00:00:00/2016-07-01T00:00:00': 3, '2017-07-01T00:00:00/2018-07-01T00:00:00': 2, '2017-10-01T00:00:00/2018-01-01T00:00:00': 1, '2018-04-01T00:00:00/2018-07-01T00:00:00': 1})
('us-gaap:IncomeTaxExpenseBenefit', 'unit', {'iso4217:USD': 10})
('us-gaap:IncomeTaxExpenseBenefit', 'value', {'19903000000': 1, '4412000000': 1, '5100000000': 1, '1945000000': 1, '2467000000': 1, '2953000000': 1, '2147000000': 1, '13700000000': 1, '13800000000': 1, '-104000000': 1})
('us-gaap:IncomeTaxExpenseBenefit', 'srt:RestatementAxis', {'srt:ScenarioPreviouslyReportedMember': 2, 'srt:RestatementAdjustmentMember': 2})
('us-gaap:IncomeTaxExpenseBenefit', 'us-gaap:AdjustmentsForNewAccountingPronouncementsAxis', {'us-gaap:AccountingStandardsUpdate201409Member': 2})
('us-gaap:IncomeTaxExpenseBenefit', 'us-gaap:IncomeTaxAuthorityAxis', {'msft:TaxCutsAndJobsActMember': 3})
###### Concept info us-gaap:NetIncomeLoss (18, 8) ####################
us-gaap:NetIncomeLoss Index(['concept', 'entity', 'period', 'unit', 'value',
       'us-gaap:StatementEquityComponentsAxis', 'srt:RestatementAxis',
       'us-gaap:AdjustmentsForNewAccountingPronouncementsAxis'],
      dtype='object')
('us-gaap:NetIncomeLoss', 'concept', {'us-gaap:NetIncomeLoss': 18})
('us-gaap:NetIncomeLoss', 'entity', {'cik:0000789019': 18})
('us-gaap:NetIncomeLoss', 'period', {'2016-07-01T00:00:00/2017-07-01T00:00:00': 4, '2015-07-01T00:00:00/2016-07-01T00:00:00': 4, '2017-07-01T00:00:00/2018-07-01T00:00:00': 2, '2017-07-01T00:00:00/2017-10-01T00:00:00': 1, '2017-10-01T00:00:00/2018-01-01T00:00:00': 1, '2018-01-01T00:00:00/2018-04-01T00:00:00': 1, '2018-04-01T00:00:00/2018-07-01T00:00:00': 1, '2016-07-02T00:00:00/2016-10-01T00:00:00': 1, '2016-10-01T00:00:00/2017-01-01T00:00:00': 1, '2017-01-01T00:00:00/2017-04-01T00:00:00': 1, '2017-04-01T00:00:00/2017-07-01T00:00:00': 1})
('us-gaap:NetIncomeLoss', 'unit', {'iso4217:USD': 18})
('us-gaap:NetIncomeLoss', 'value', {'16571000000': 2, '25489000000': 2, '20539000000': 2, '21204000000': 1, '4285000000': 1, '16798000000': 1, '3741000000': 1, '6576000000': 1, '-6302000000': 1, '7424000000': 1, '8873000000': 1, '5667000000': 1, '6267000000': 1, '5486000000': 1, '8069000000': 1})
('us-gaap:NetIncomeLoss', 'us-gaap:StatementEquityComponentsAxis', {'us-gaap:RetainedEarningsMember': 3})
('us-gaap:NetIncomeLoss', 'srt:RestatementAxis', {'srt:ScenarioPreviouslyReportedMember': 2, 'srt:RestatementAdjustmentMember': 2})
('us-gaap:NetIncomeLoss', 'us-gaap:AdjustmentsForNewAccountingPronouncementsAxis', {'us-gaap:AccountingStandardsUpdate201409Member': 2})
###### Concept info us-gaap:EarningsPerShareBasic (11, 5) ####################
us-gaap:EarningsPerShareBasic Index(['concept', 'entity', 'period', 'unit', 'value'], dtype='object')
('us-gaap:EarningsPerShareBasic', 'concept', {'us-gaap:EarningsPerShareBasic': 11})
('us-gaap:EarningsPerShareBasic', 'entity', {'cik:0000789019': 11})
('us-gaap:EarningsPerShareBasic', 'period', {'2017-07-01T00:00:00/2018-07-01T00:00:00': 1, '2016-07-01T00:00:00/2017-07-01T00:00:00': 1, '2015-07-01T00:00:00/2016-07-01T00:00:00': 1, '2017-07-01T00:00:00/2017-10-01T00:00:00': 1, '2017-10-01T00:00:00/2018-01-01T00:00:00': 1, '2018-01-01T00:00:00/2018-04-01T00:00:00': 1, '2018-04-01T00:00:00/2018-07-01T00:00:00': 1, '2016-07-02T00:00:00/2016-10-01T00:00:00': 1, '2016-10-01T00:00:00/2017-01-01T00:00:00': 1, '2017-01-01T00:00:00/2017-04-01T00:00:00': 1, '2017-04-01T00:00:00/2017-07-01T00:00:00': 1})
('us-gaap:EarningsPerShareBasic', 'unit', {'iso4217:USD/xbrli:shares': 11})
('us-gaap:EarningsPerShareBasic', 'value', {'2.15': 1, '3.29': 1, '2.59': 1, '0.85': 1, '-0.82': 1, '0.96': 1, '1.15': 1, '0.73': 1, '0.81': 1, '0.71': 1, '1.05': 1})
###### Concept info us-gaap:EarningsPerShareDiluted (15, 7) ####################
us-gaap:EarningsPerShareDiluted Index(['concept', 'entity', 'period', 'unit', 'value', 'srt:RestatementAxis',
       'us-gaap:AdjustmentsForNewAccountingPronouncementsAxis'],
      dtype='object')
('us-gaap:EarningsPerShareDiluted', 'concept', {'us-gaap:EarningsPerShareDiluted': 15})
('us-gaap:EarningsPerShareDiluted', 'entity', {'cik:0000789019': 15})
('us-gaap:EarningsPerShareDiluted', 'period', {'2016-07-01T00:00:00/2017-07-01T00:00:00': 3, '2015-07-01T00:00:00/2016-07-01T00:00:00': 3, '2017-07-01T00:00:00/2018-07-01T00:00:00': 1, '2017-07-01T00:00:00/2017-10-01T00:00:00': 1, '2017-10-01T00:00:00/2018-01-01T00:00:00': 1, '2018-01-01T00:00:00/2018-04-01T00:00:00': 1, '2018-04-01T00:00:00/2018-07-01T00:00:00': 1, '2016-07-02T00:00:00/2016-10-01T00:00:00': 1, '2016-10-01T00:00:00/2017-01-01T00:00:00': 1, '2017-01-01T00:00:00/2017-04-01T00:00:00': 1, '2017-04-01T00:00:00/2017-07-01T00:00:00': 1})
('us-gaap:EarningsPerShareDiluted', 'unit', {'iso4217:USD/xbrli:shares': 15})
('us-gaap:EarningsPerShareDiluted', 'value', {'2.13': 1, '3.25': 1, '2.56': 1, '2.71': 1, '0.54': 1, '2.10': 1, '0.46': 1, '0.84': 1, '-0.82': 1, '0.95': 1, '1.14': 1, '0.72': 1, '0.80': 1, '0.70': 1, '1.03': 1})
('us-gaap:EarningsPerShareDiluted', 'srt:RestatementAxis', {'srt:ScenarioPreviouslyReportedMember': 2, 'srt:RestatementAdjustmentMember': 2})
('us-gaap:EarningsPerShareDiluted', 'us-gaap:AdjustmentsForNewAccountingPronouncementsAxis', {'us-gaap:AccountingStandardsUpdate201409Member': 2})
###### Concept info us-gaap:CommonStockDividendsPerShareDeclared (11, 5) ####################
us-gaap:CommonStockDividendsPerShareDeclared Index(['concept', 'entity', 'period', 'unit', 'value'], dtype='object')
('us-gaap:CommonStockDividendsPerShareDeclared', 'concept', {'us-gaap:CommonStockDividendsPerShareDeclared': 11})
('us-gaap:CommonStockDividendsPerShareDeclared', 'entity', {'cik:0000789019': 11})
('us-gaap:CommonStockDividendsPerShareDeclared', 'period', {'2017-07-01T00:00:00/2018-07-01T00:00:00': 1, '2016-07-01T00:00:00/2017-07-01T00:00:00': 1, '2015-07-01T00:00:00/2016-07-01T00:00:00': 1, '2017-07-01T00:00:00/2017-10-01T00:00:00': 1, '2017-10-01T00:00:00/2018-01-01T00:00:00': 1, '2018-01-01T00:00:00/2018-04-01T00:00:00': 1, '2018-04-01T00:00:00/2018-07-01T00:00:00': 1, '2016-07-02T00:00:00/2016-10-01T00:00:00': 1, '2016-10-01T00:00:00/2017-01-01T00:00:00': 1, '2017-01-01T00:00:00/2017-04-01T00:00:00': 1, '2017-04-01T00:00:00/2017-07-01T00:00:00': 1})
('us-gaap:CommonStockDividendsPerShareDeclared', 'unit', {'iso4217:USD/xbrli:shares': 11})
('us-gaap:CommonStockDividendsPerShareDeclared', 'value', {'0.42': 4, '0.39': 4, '1.68': 1, '1.56': 1, '1.44': 1})
###### Concept info us-gaap:OtherComprehensiveIncomeLossNetOfTaxPortionAttributableToParent (15, 6) ####################
us-gaap:OtherComprehensiveIncomeLossNetOfTaxPortionAttributableToParent Index(['concept', 'entity', 'period', 'unit', 'value',
       'us-gaap:StatementEquityComponentsAxis'],
      dtype='object')
('us-gaap:OtherComprehensiveIncomeLossNetOfTaxPortionAttributableToParent', 'concept', {'us-gaap:OtherComprehensiveIncomeLossNetOfTaxPortionAttributableToParent': 15})
('us-gaap:OtherComprehensiveIncomeLossNetOfTaxPortionAttributableToParent', 'entity', {'cik:0000789019': 15})
('us-gaap:OtherComprehensiveIncomeLossNetOfTaxPortionAttributableToParent', 'period', {'2017-07-01T00:00:00/2018-07-01T00:00:00': 5, '2016-07-01T00:00:00/2017-07-01T00:00:00': 5, '2015-07-01T00:00:00/2016-07-01T00:00:00': 5})
('us-gaap:OtherComprehensiveIncomeLossNetOfTaxPortionAttributableToParent', 'unit', {'iso4217:USD': 15})
('us-gaap:OtherComprehensiveIncomeLossNetOfTaxPortionAttributableToParent', 'value', {'-2856000000': 2, '-1167000000': 2, '-728000000': 2, '39000000': 1, '-218000000': 1, '-238000000': 1, '-2717000000': 1, '-1116000000': 1, '-228000000': 1, '-178000000': 1, '167000000': 1, '-262000000': 1})
('us-gaap:OtherComprehensiveIncomeLossNetOfTaxPortionAttributableToParent', 'us-gaap:StatementEquityComponentsAxis', {'us-gaap:AccumulatedOtherComprehensiveIncomeMember': 3, 'us-gaap:AccumulatedNetGainLossFromDesignatedOrQualifyingCashFlowHedgesMember': 3, 'msft:AccumulatedNetUnrealizedGainLossOnInvestmentMember': 3, 'msft:AccumulatedTranslationAdjustmentAndOtherMember': 3})
###### Concept info us-gaap:CashAndCashEquivalentsAtCarryingValue (26, 6) ####################
us-gaap:CashAndCashEquivalentsAtCarryingValue Index(['concept', 'entity', 'period', 'unit', 'value',
       'us-gaap:InvestmentTypeAxis'],
      dtype='object')
('us-gaap:CashAndCashEquivalentsAtCarryingValue', 'concept', {'us-gaap:CashAndCashEquivalentsAtCarryingValue': 26})
('us-gaap:CashAndCashEquivalentsAtCarryingValue', 'entity', {'cik:0000789019': 26})
('us-gaap:CashAndCashEquivalentsAtCarryingValue', 'period', {'2018-07-01T00:00:00': 12, '2017-07-01T00:00:00': 12, '2016-07-01T00:00:00': 1, '2015-07-01T00:00:00': 1})
('us-gaap:CashAndCashEquivalentsAtCarryingValue', 'unit', {'iso4217:USD': 26})
('us-gaap:CashAndCashEquivalentsAtCarryingValue', 'value', {'0': 11, '11946000000': 1, '7663000000': 1, '6510000000': 1, '5595000000': 1, '3942000000': 1, '246000000': 1, '2215000000': 1, '1865000000': 1, '3678000000': 1, '3624000000': 1, '1478000000': 1, '69000000': 1, '972000000': 1, '16000000': 1, '1504000000': 1})
('us-gaap:CashAndCashEquivalentsAtCarryingValue', 'us-gaap:InvestmentTypeAxis', {'us-gaap:CashMember': 2, 'us-gaap:MoneyMarketFundsMember': 2, 'us-gaap:CommercialPaperMember': 2, 'us-gaap:CertificatesOfDepositMember': 2, 'us-gaap:USGovernmentAgenciesDebtSecuritiesMember': 2, 'us-gaap:ForeignGovernmentDebtSecuritiesMember': 2, 'us-gaap:AssetBackedSecuritiesMember': 2, 'us-gaap:CorporateDebtSecuritiesMember': 2, 'us-gaap:USStatesAndPoliticalSubdivisionsMember': 2, 'us-gaap:EquitySecuritiesMember': 2, 'msft:OtherSecurityInvestmentsMember': 2})
###### Concept info us-gaap:AvailableForSaleSecuritiesCurrent (24, 6) ####################
us-gaap:AvailableForSaleSecuritiesCurrent Index(['concept', 'entity', 'period', 'unit', 'value',
       'us-gaap:InvestmentTypeAxis'],
      dtype='object')
('us-gaap:AvailableForSaleSecuritiesCurrent', 'concept', {'us-gaap:AvailableForSaleSecuritiesCurrent': 24})
('us-gaap:AvailableForSaleSecuritiesCurrent', 'entity', {'cik:0000789019': 24})
('us-gaap:AvailableForSaleSecuritiesCurrent', 'period', {'2018-07-01T00:00:00': 12, '2017-07-01T00:00:00': 12})
('us-gaap:AvailableForSaleSecuritiesCurrent', 'unit', {'iso4217:USD': 24})
('us-gaap:AvailableForSaleSecuritiesCurrent', 'value', {'0': 7, '121822000000': 1, '1000000': 1, '4835000000': 1, '3931000000': 1, '3761000000': 1, '111828000000': 1, '386000000': 1, '250000000': 1, '307000000': 1, '125318000000': 1, '6912000000': 1, '3859000000': 1, '5173000000': 1, '105079000000': 1, '193000000': 1, '298000000': 1, '327000000': 1})
('us-gaap:AvailableForSaleSecuritiesCurrent', 'us-gaap:InvestmentTypeAxis', {'us-gaap:CashMember': 2, 'us-gaap:MoneyMarketFundsMember': 2, 'us-gaap:CommercialPaperMember': 2, 'us-gaap:CertificatesOfDepositMember': 2, 'us-gaap:USGovernmentAgenciesDebtSecuritiesMember': 2, 'us-gaap:ForeignGovernmentDebtSecuritiesMember': 2, 'us-gaap:AssetBackedSecuritiesMember': 2, 'us-gaap:CorporateDebtSecuritiesMember': 2, 'us-gaap:USStatesAndPoliticalSubdivisionsMember': 2, 'us-gaap:EquitySecuritiesMember': 2, 'msft:OtherSecurityInvestmentsMember': 2})
###### Concept info us-gaap:LongTermInvestments (24, 6) ####################
us-gaap:LongTermInvestments Index(['concept', 'entity', 'period', 'unit', 'value',
       'us-gaap:InvestmentTypeAxis'],
      dtype='object')
('us-gaap:LongTermInvestments', 'concept', {'us-gaap:LongTermInvestments': 24})
('us-gaap:LongTermInvestments', 'entity', {'cik:0000789019': 24})